### DISCUSSION TITLE
Local plugin for python

### DISCUSSION THREAD

**Discussion by caydenwei** [bufbuild/buf#2676] [Q&A] [answered]
How can I execute 'buf generate' without the remote plugin in PYTHON? It's typically hard to build in an environment without internet access.

This is my original buf.gen.yaml file, Is there any way to convert to us local plugin

```
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/protocolbuffers/python
    out: generated
  - plugin: buf.build/grpc/python:v1.58.0
    out: generated
```

**Comment by timostamm** [comment]
Remote plugins are regular Protobuf plugins (typically a simple executable named protoc-gen-foo, where "foo" is the language name). If you prefer to use local plugins, you have to install them yourself, and use them in buf.gen.yaml without the protoc-gen- prefix:

```diff
version: v1
plugins:
  - plugin: foo # calls the executable protoc-gen-foo
    out: gen
```

See the documentation [here](https://buf.build/docs/configuration/v1/buf-gen-yaml#plugin).


In case of python, you can make this change to use the local plugin:

```diff
version: v1
plugins:
- - plugin: buf.build/protocolbuffers/python:v25.1
+ - plugin: python
    out: gen
```

However, python is a special case because the plugin is built into `protoc`. So you have to download and install a release of `protoc` from [here](https://github.com/protocolbuffers/protobuf/releases) for local code generation. Also see the [documentation for the protoc_path option](https://buf.build/docs/configuration/v1/buf-gen-yaml#protoc_path).

**Reply by caydenwei** [reply]
Thank you for your response. However, the method you provided only generates the _pb2.py files, and the _pb2_grpc.py files are not generated.

Additionally, I could not find any documentation that demonstrates how to convert a command like the following to a buf.gen.yaml file:

```
python -m grpc_tools.protoc -I$src_dir --python_out=$gen_dir --grpc_python_out=$gen_dir $src_dir/*.proto
```

Here is my original buf.gen.yaml file, I am struggle to generate the gRPC codes locally. (convert plugin  buf.build/grpc/python:v1.58.0 to local )

```
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/protocolbuffers/python
    out: generated
  - plugin: buf.build/grpc/python:v1.58.0
    out: generated
```
