### DISCUSSION TITLE
Does ignore_only work?

### DISCUSSION THREAD

**Discussion by megasuperlexa** [bufbuild/buf#2891] [Q&A] [answered]
I am using the following section in my `buf.yaml`
```
lint:
  use:
    - MINIMAL
  ignore_only:
    ENUM_VALUE_PREFIX:
      - integrations
      - "clients/*"
      - internals/**
```
 
but whichever format I am using, files from `integrations`, `clients` and `intenals` are still produce same linting errors about enums. I am using this guide https://buf.build/docs/configuration/v1/buf-yaml#ignore_only  
Where I guess `foo` and `bar` are directory names?
