### DISCUSSION TITLE
Use buf to generate definitions for dependencies

### DISCUSSION THREAD

**Discussion by metaturso** [bufbuild/buf#2970] [Q&A] [answered]
Hi,

I've recently discovered the `buf` tool and was wondering, can I use it to pull in and compile a protobuf definition in a project that doesn't have any .proto files of its own?

My project depends on a third-party API that ships with a `buf.yaml` file and publishes their module on the BSR. I can compile the SDK in the target language using the command:

```bash
buf generate https://github.com/third-party/api.git
# alternatively pulling the module from BSR
buf generate buf.build/third-party/api
``` 

When I call `buf generate` with a module name as shown above, the code is generated according to the `buf.gen.yaml` configuration and the SDK in the target language shows up inside the `var/` directory. Perfect. Now, I would like to declare the dependency in the YAML configuration instead:

```yaml
# buf.yaml in my project
version: v1
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
deps:
  - buf.build/third-party/api

# buf.gen.yaml
version: v1
plugins:
  - name: php
    out: var/
```

However, when I run `buf generate` without arguments nothing happens. Here's an example of what I get

```bash
buf mod update
buf generate --debug --verbose
DEBUG	get_ref	{"duration": "38.037µs"}
DEBUG	get_config	{"duration": "147.738µs"}
DEBUG	get_config	{"duration": "491.131µs"}
DEBUG	get_config	{"duration": "79.544µs"}
DEBUG	get_module_config	{"duration": "1.626034ms"}
DEBUG	command	{"duration": "43.218858ms"}
Failure: no .proto target files found
```

Any advice?
