### DISCUSSION TITLE
generate purerpc code

### DISCUSSION THREAD

**Discussion by ledmonster** [bufbuild/buf#3464] [Q&A] [answered]
I want to generate code for purerpc. [purerpc](https://github.com/python-trio/purerpc) provides `protoc-gen-purerpc` plugin. How can I configure buf.gen.yaml for purerpc code generation?

purerpc is very useful when I integrate gRPC with [trio](https://github.com/python-trio/trio) async library.

**Comment by timostamm** [comment, marked as answer]
This will get you started:

```yaml
version: v2
plugins:
  - local: protoc-gen-purerpc
    out: gen
```

See https://buf.build/docs/configuration/v2/buf-gen-yaml/ for details.
