### ISSUE TITLE
Issue with same proto file in different modules

### ISSUE THREAD

**Issue by jon-whit** [bufbuild/buf#1001]
I'm having an issue integrating buf with my current project structure. I have a project laid out like the following:

```
customers/
  proto/
    customer/
      customer.proto
    service/
      # defines package customers and imports `proto/errormessages`
      service.proto 
    buf.yaml

proto/
  errormessages/
    errormessages.proto
  service/
    # defines package service and imports errormessages
    service.proto
  buf.yaml

buf.gen.yaml
buf.work.yaml
```

```
# buf.work.yaml
version: v1
directories:
  - proto
  - customers/proto
```

```
# buf.gen.yaml
version: v1
plugins:
  - remote: buf.build/protocolbuffers/plugins/go:v1.27.1-1
    out: proto/
    opt: paths=source_relative
  - remote: buf.build/grpc/plugins/go:v1.1.0-1
    out: proto/
    opt:
      - paths=source_relative
  - remote: buf.build/jirkad/plugins/protoc-gen-validate:v0.6.1
    out: proto/
    opt:
      - paths=source_relative
      - lang=go
  - remote: buf.build/grpc-ecosystem/plugins/grpc-gateway:v2.8.0-1
    out: proto/
    opt:
      - paths=source_relative
      - logtostderr=true
  - remote: buf.build/grpc-ecosystem/plugins/openapiv2:v2.8.0-1
    out: docs/openapiv2
  - remote: buf.build/jon-whit/plugins/protoc-gen-doc:v1.5.1
    out: docs/
    opt:
      - markdown,api.md
```
I recognize this isn't a project structure that follows best-practices, but I'm trying to introduce buf in an incremental way (the next step would be to restructure the protobuf module layout to follow best-practices).

When I try to generate the stubs I get the following error:
```
➜  buf generate
Failure: service/service.proto exists in multiple locations: customers/proto/service/service.proto proto/service/service.proto
```
