### ISSUE TITLE
`no such file or directory` message when generating code with plugin

### ISSUE THREAD

**Issue by kevinbarbour** [bufbuild/buf#1006]
I am generating code via buf and using the protoc-gen-validate plugin from the BSR. The generation works fine, including code generated by the plugin, but I see the following error each time I run `buf gen`:

`2022/03/14 13:17:04  info Can't load validate/validate.proto, err=open validate/validate.proto: no such file or directory, ignoring (want to make PR?)`

The buf.yaml describes the dependency (along with two other dependencies I don't get this error for):
```yaml
version: v1
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/envoyproxy/protoc-gen-validate
```

And the proto file performs the import like so:

```proto
import "validate/validate.proto";
```

Any idea why this might be happening? If I try to change the import to any other path, such as including the package name, then it actually fails with a file not found error, but as it is now we just see this can't load warning and everything else works as expected.
