### ISSUE TITLE
Different between protoc and buf output for JavaScript

### ISSUE THREAD

**Issue by eberkund** [bufbuild/buf#1012]
I noticed that buf generates the following code:

```javascript
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));
```

whereas protoc generates this instead:

```javascript
var global = Function('return this')();
```

Is there any specific reason for this difference? This is causing issues for me with vitest.

**Comment by bufdev** [comment]
Can you provide specific reproduction steps, including what versions of `buf` and `protoc` are on your `$PATH`?

**Comment by eberkund** [comment]
Using remote plugin with specified version has the same result:

```yaml
plugins:
  - remote: buf.build/protocolbuffers/plugins/js:v3.20.0-1
    out: frontend/src
    opt:
      - import_style=commonjs
```

Coming from the following prototool config:
```yaml
plugins:
    - name: js
      flags: import_style=commonjs
      output: ../frontend/src/generated
```

protoc version:

```
⟩ protoc --version
libprotoc 3.19.4
```
