### ISSUE TITLE
buf + dependabot Integration

### ISSUE THREAD

**Issue by hasit** [bufbuild/buf#1022]
It would be good to have `buf + dependabot` integration so that protobuf dependencies managed by `buf` can be updated at a regular period.

Something like this:

```
# /path/to/.github/dependabot.yaml
  # Buf
  - package-ecosystem: "buf"
    directory: "/path/to/api"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 20
```

I'd be happy to help further on this feature request.

Ref: [dependabot config](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)

cc: @robbertvanginkel
