### ISSUE TITLE
Add the ability to extend buf.yaml files from other buf.yaml files

### ISSUE THREAD

**Issue by wdfinch** [bufbuild/buf#1058]
Workspaces are now the preferred approach to deal with separate logic groups of buf modules. This means that each directory defined in our `buf.work.yaml` file requires a new buf.yaml file for config. 

While this is a good approach and makes it easy for separate teams to manage their own modules, it also leads to a lot of copy and pasting of code. For example, across all my workspace groups, I want to have certain linting rules and settings. 

I would like to be able to write these once in a `buf.yaml` file at the workspace root and simply import this into the `buf.yaml` files. This would serve as a base for the settings to use and then I could overwrite any settings in that groups specific buf.yaml file.

I could see this working as follows:

workspace.buf.yaml - present at the root of the workspace
```yaml
version: v1
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
```

buf.yaml - present in one of my module group managed by the workspace
```yaml
extends: ../workspace.buf.yaml
name: buf.build/petland/dogapis
deps:
  - buf.build/googleapis/googleapis
```

I use this same pattern in my tsconfig.json files in typescript and it's really nice.

https://www.typescriptlang.org/tsconfig#extends
