### ISSUE TITLE
Support directory strategy for remote plugins

### ISSUE THREAD

**Issue by jsok** [bufbuild/buf#1067]
This seems to be purposely disabled:

https://github.com/bufbuild/buf/blob/4e717bd3bfbc5e8b8303d6890d71a476782f41f7/private/buf/bufgen/config.go#L135-L138

This is as much a question as it is a request, because it breaks certain protoc plugins (e.g. [twirp](https://github.com/twitchtv/twirp/blob/ff7d9f87d8598707f3465c80ee5dec1ba8520310/protoc-gen-twirp/generator.go#L181-L216)).

If it's not possible to support, what's the recommended workaround?

## Example

```yaml
version: v1
plugins:
  - remote: buf.build/demolab/plugins/twirp:v8.1.1-1
    out: go
    opt:
      - paths=source_relative
```
