### ISSUE TITLE
Failure: branch is not main.

### ISSUE THREAD

**Issue by sangeethRazorpay** [bufbuild/buf#1068]
Getting the following error on Buf generate
`Failure: branch is not main.`

Buf version : 0.56
Go version : go1.17.8 darwin/arm64
System PATH variable : /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/sangeeth.mukundan/go/bin:/opt/homebrew/bin
 
Buf.yaml
```
version: v1beta1
name: buf.build/org_name/repo_name
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
build:
  roots:
    - proto
```
    
buf.gen.yaml
```
version: v1
managed:
  enabled: true
  go_package_prefix:
    default:  github.com/org_name/repo_name/rpc
    override:
      buf.build/grpc-ecosystem/grpc-gateway: github.com/grpc-ecosystem/grpc-gateway/v2
    except:
      - buf.build/googleapis/googleapis
plugins:
  - name: go
    out: rpc
    opt:
      - paths=source_relative
  - name: go-grpc
    out: rpc
    opt:
      - paths=source_relative
  - name: grpc-gateway
    out: rpc
    opt:
      - paths=source_relative
  - name: twirp
    out: rpc
    opt:
      - paths=source_relative
  - name: openapiv2
    out: docs
    opt:
      - generate_unbound_methods=true
      - disable_default_errors=true
      - allow_merge=false
      - include_package_in_tags=false
      - json_names_for_fields=false
      - include_package_in_tags=true
      - fqn_for_openapi_name=true
```

Please help out!! Stuck on this since last 2 days
