### ISSUE TITLE
Remote plugin throwing no such file or directory

### ISSUE THREAD

**Issue by chandraaditya** [bufbuild/buf#1069]
I am trying to create a remote plugin for [https://github.com/srikrsna/protoc-gen-gotag](https://github.com/srikrsna/protoc-gen-gotag) as I would like to use it without having to install it on every system. 

So I created a Dockerfile like this:
```
FROM golang as builder

ENV GOOS=linux GOARCH=amd64 CGO_ENABLED=0

RUN go install github.com/srikrsna/protoc-gen-gotag@latest

FROM scratch

COPY --from=builder /go/bin /

ENTRYPOINT ["/protoc-gen-gotag"]
```
Then I ran the following two commands 
```
docker build -f Dockerfile -t plugins.buf.build/chandraaditya/gotag:v0.55.0-2 .
docker push plugins.buf.build/chandraaditya/gotag:v0.55.0-2
```
And everything worked fine till here. And the plugin was published. 

Now I updated my ```buf.gen.go.tag.yaml``` file like so
```
version: v1
plugins:
  - remote: buf.build/chandraaditya/plugins/gotag
    out: .
    opt:
      - paths=source_relative
      - outdir=gen/go
      - xxx=graphql+"-" bson+"-"
```

And when I run ```buf generate``` I get the following error
```
Failure: Plugin "buf.build/chandraaditya/plugins/gotag:v0.55.0-2" exited with non-zero status 1: [error] [gotag]: open gen/go/product/categories/models/v1/categories.pb.go: no such file or directory
```

So the thing with this plugin is that it is supposed to be run after generating the files, so I have a ```buf.gen.go.yaml``` which I run before this. 

The weirdest part of this is that if I switch out the remote plugin for a local one, like so:
```
name: gotag
```
everything works just fine, so I'm confused as to where I'm going wrong in this process. 

The buf version I have is 1.3.1.
