### ISSUE TITLE
Remote Generation File Duplication

### ISSUE THREAD

**Issue by Jake-RoundrockIO** [bufbuild/buf#1151]
I'm currently experiencing an issue with my remote-generated npm packages where they are not referencing module dependencies via their package, as described [here](https://docs.buf.build/bsr/remote-generation/js#import-rewrites), and instead duplicating the required files within the module.

For example:

I have 3 modules (A, B, and C) where A references B and C. When remote generating the code using the `grpc/web` template, A registers B and C as dependencies in its `package.json` and correctly references them via `@buf/grpc_web_...`. When using my template (using a plugin based on [stephenh/ts-proto](https://github.com/stephenh/ts-proto)) A still registers B and C in its `package.json`, but includes the relevant files from B and C in its own package and references them with relative paths rather than the `@buf/...` module imports.

When testing both the `grpc/web` and my plugin locally, they both output the exact same directory structure, the only difference being that my files were named `file.pb.ts` and the `grpc/web` files are named `file_grpc_pb.js`. The file names should not be a problem though according to the table provided [here](https://docs.buf.build/bsr/remote-generation/js#import-rewrites) and I tested this by setting up my files to output as just `file.ts` and still encountered the same issue.

My only other thought is that the plugin requires `strategy: all` and I don't know what effect that may have on remote generation.

For reference:
My plugin: [`buf.build/jake-roundrock/plugins/ts-proto:v1.112.2-0`](https://buf.build/jake-roundrock/plugins/ts-proto)
- Plugin Dockerfile
```Dockerfile
FROM node:16-alpine as builder

RUN npm install -g ts-proto

ENTRYPOINT ["protoc-gen-ts_proto"]
```

- Template
```yml
- remote: buf.build/jake-roundrock/plugins/ts-proto:v1.112.2-0
    out: gen/proto/ts
    opt:
      - env=node
      - exportCommonSymbols=false
      - unrecognizedEnum=false
      - useOptionals=messages
      - fileSuffix=.pb
      - forceLong=number
      - returnObservable=false
      - addGrpcMetadata=true
      - addNestjsRestParameter=true
      - nestJs=true
      - outputServices=grpc-js
      - esModuleInterop=true
```

Slack discussion: https://bufbuild.slack.com/archives/CRZ680FUH/p1653068813317959
