### ISSUE TITLE
gofullmethods output is in gen/proto/go

### ISSUE THREAD

**Issue by vyskocilm** [bufbuild/buf#1152]
Hi, we do use https://github.com/go-tooling/protoc-gen-gofullmethods generator. When calling via `buf` the file ends up directly in `gen/proto/go`

```
gen/proto/go/
├── pet
│   └── v1
│       ├── pet_grpc.pb.go
│       └── pet.pb.go
└── pet.fullmethods.pb.go
```

```yaml
# buf.gen.yaml
  - name: gofullmethods
    out: gen/proto/go
```

Is there any way how to affect the output location for this generator from buf?
