### ISSUE TITLE
Override protoc-gen-java path in buf.gen.yaml doesn't work

### ISSUE THREAD

**Issue by xierunzi** [bufbuild/buf#1155]
I declare two plugins(`protoc-gen-java` and `protoc-gen-grpc-java`) in my `buf.gen.yaml`, and I want to override their path. 
After calling the `buf generate` , I found the `protoc-gen-grpc-java` works. But the `protoc-gen-java` doesn't work. And there is an error message after generating. 
I have tried serveral times and it seems `buf generate` can only works when `protoc-gen-java` is in $PATH.

Details:
OS: Mac OS X
buf version: 1.4.0
buf.gen.yaml
```
version: v1
managed:
  enabled: true
  java_multiple_files: true
plugins:
  - name: java
    out: temp
    path: ./protoc-gen-java
  - name: grpc-java
    out: temp
    path: ./protoc-gen-grpc-java
```
my work dir:
```
$ ls
buf.gen.yaml         protoc-gen-grpc-java protoc-gen-java
```
error message
```
$ buf generate --include-imports bapis.net/ad/account.bid:buf
Failure: plugin java: proto: cannot parse invalid wire-format data
```

**Comment by bufdev** [comment]
What happens if you change `name: java` to `name: foo`?

**Comment by xierunzi** [comment]
Still doesn't work and same error message.
`buf.gen.yaml`
```
version: v1
managed:
  enabled: true
  java_multiple_files: true
  java_package_prefix: com.bapis
plugins:
  - name: foo
    out: target/generated-sources/protobuf/java
    path: ./foo
  - name: grpc-java
    out: target/generated-sources/protobuf/grpc-java
    path: ./protoc-gen-grpc-java
```
my work dir
```
$ ls
buf.gen.yaml         foo                  protoc-gen-grpc-java protoc-gen-java
```

**Comment by xierunzi** [comment]
ok, I may misunderstand.
```
version: v1
managed:
  enabled: true
  java_multiple_files: true
  java_package_prefix: com.bapis
plugins:
  - name: java
    out: temp
    path: ./protoc-gen-java
  - name: grpc-java
    out: temp
    path: ./protoc-gen-grpc-java
```
Fails agian with `buf.gen.yaml` below. And I'm certainly sure that the plugin works if I don't override the path.

> I'm going to guess that you'll run into the same error but it will help rule out that there's this strange interaction with the protoc-gen-java plugin.

Agree.

**Comment by xierunzi** [comment]
Supplement of successful case.
```
version: v1
managed:
  enabled: true
  java_multiple_files: true
  java_package_prefix: com.bapis
plugins:
  - name: java
    out: temp
   # path: ./protoc-gen-java
  - name: grpc-java
    out: temp
    path: ./protoc-gen-grpc-java
```
```
$ which protoc
/usr/local/bin/protoc
```
```
$ buf generate bapis.net/ad/account.bid:buf && ls
ad/account/bid/api.proto: warning: Import google/api/annotations.proto is unused.
buf.gen.yaml         foo                  protoc-gen-grpc-java protoc-gen-java      temp
```

**Comment by xierunzi** [comment]
Yes, I  successfully compile a proto by the binary in my work dir.

**Comment by bufdev** [comment]
> $ ./protoc-gen-java --java_out=./temp temp.proto

This isn't a `protoc` plugin. `protoc` plugins take a `CodeGeneratorRequest` on stdin, and a `CodeGeneratorResponse` is sent on stdout. https://docs.buf.build/reference/images#plugins

It appears you just have renamed `protoc` to `protoc-gen-java`, is this correct? Or is something else going on?

**Comment by xierunzi** [comment]
Well, spent some time on `protoc` and `protoc` plugins just now.
> This isn't a protoc plugin.

True, but `protoc` can generate without additional plugin in cpp, java, js, php, python e.g..It seems that `protoc-gen-go` is more special then other languages. I tried to find the plugin called `protoc-gen-java`, but only found 'protoc-gen-javalite' which is for android. 

I use the `buf.gen.yaml` below, and nothing heppend.
```
version: v1
managed:
  enabled: true
  java_multiple_files: true
  java_package_prefix: com.bapis
plugins:
  - name: grpc-java
    out: temp
    path: ./protoc-gen-grpc-java

```
```
$ buf generate bapis.net/gogo/protobuf:buf

$ tree
.
├── buf.gen.yaml
├── foo
├── protoc
├── protoc-gen-grpc-java
├── protoc-gen-java
├── protoc-gen-javalite
├── temp
└── temp.proto

1 directory, 7 files
```
Can `buf generate` provides some flags to generate java codes like `protoc --java_out`?  Or else I can only use `buf.gen.yaml` below to generate java codes. And it's still confused why it could work. 

```
version: v1
managed:
  enabled: true
  java_multiple_files: true
  java_package_prefix: com.bapis
plugins:
  - name: java
    out: temp
   # path: not to override path, use protoc in $PATH
  - name: grpc-java
    out: temp
    path: ./protoc-gen-grpc-java
```
