### ISSUE TITLE
buf:lint:ignore does not work on ENUM_FIRST_VALUE_ZERO

### ISSUE THREAD

**Issue by afeinman-snap** [bufbuild/buf#1186]
Using buf 1.5.0
No matter where I try placing the comment
```proto
// buf:lint:ignore ENUM_FIRST_VALUE_ZERO
```
it does not seem to have any effect:
```proto
enum Test {
// buf:lint:ignore ENUM_FIRST_VALUE_ZERO
 FIRST = 10;
 SECOND = 20;
}
```
```sh
$ buf_test % ~/Downloads/buf-Darwin-x86_64 lint . --config buf.yaml
test/test.proto:8:10:First enum value "FIRST" should have a numeric value of 0
```

The config file:
```yaml
version: v1
name: ""
build:
  excludes: []
lint:
  allow_comment_ignores: true
  use:
    - BASIC
```
[test.zip](https://github.com/bufbuild/buf/files/8873157/test.zip)
