### ISSUE TITLE
buf.build/grpc/plugins/kotlin:v1.3.0-1 is corrupt

### ISSUE THREAD

**Issue by wingsofovnia** [bufbuild/buf#1196]
`buf.gen.yaml`:
```
version: v1
managed:
  enabled: true
plugins:
  - remote: buf.build/protocolbuffers/plugins/kotlin:v21.1.0-1
    out: bin/kotlin
  - remote: buf.build/grpc/plugins/kotlin:v1.3.0-1
    out: bin/kotlin
```

Output:
```
❯ buf build && buf generate
Failure: plugin "buf.build/grpc/plugins/kotlin:v1.3.0-1" exited with non-zero status 1: Error: Invalid or corrupt jarfile /app/protoc-gen-grpc-kotlin-jdk7.jar
```

Workaround: use previous version (`v1.2.1-1`):
