### ISSUE TITLE
JS/TS Remote Generation Module Fails to Rewrite Dependency Paths

### ISSUE THREAD

**Issue by Jake-RoundrockIO** [bufbuild/buf#1197]
Tangential issue of #1151 

I have 3 modules (A, B, and C) where A references B and C. When using my template (using this [plugin](https://buf.build/stephenh/plugins/ts-proto) based on [stephenh/ts-proto](https://github.com/stephenh/ts-proto)) A correctly registers B and C in its `package.json` and doesn't include their files in the module itself, but continues to reference them with relative paths rather than rewriting them with the `@buf/...` module imports.

### Template

```yaml
- remote: buf.build/jake-roundrock/plugins/ts-proto:v1.112.2-0
    out: gen/proto/ts
    opt:
      - env=node
      - exportCommonSymbols=false
      - unrecognizedEnum=false
      - useOptionals=messages
      - fileSuffix=.pb
      - forceLong=number
      - returnObservable=false
      - addGrpcMetadata=true
      - addNestjsRestParameter=true
      - nestJs=true
      - outputServices=grpc-js
      - esModuleInterop=true
      - emitImportedFiles=false
```

### Proto modules
```
A
├ x
│ └ v1
│   └ x.proto
└ buf.yaml
B
├ y
│ └ v1
│   └ y.proto
└ buf.yaml
C
├ z
│ └ v1
│   └ z.proto
└ buf.yaml
```

### Generated modules
```
A
├ x
│ └ v1
│   └ x.pb.ts
└ package.json
B
├ y
│ └ v1
│   └ y.pb.ts
└ package.json
C
├ z
│ └ v1
│   └ z.pb.ts
└ package.json
```
