### ISSUE TITLE
Allow extra metadata in buf.yaml

### ISSUE THREAD

**Issue by wingsofovnia** [bufbuild/buf#1216]
It can be handy to have extra fields/labels/annotations/metadata in `buf.xml` which private tools rely on. Currently, adding a foreign field to `buf.xml` fails `buf`:
```
line 2: field myfield not found in type bufconfig.ExternalConfigV1
```
It would be nice to make `buf` ignore unknown fields. Another option would be adding `metadata` fields or alike:
```
version: v1
name: buf.build/test/app
metadata:
  key1: value1
  key2: value2
```
