### ISSUE TITLE
Reduce Workspace import scopes via explicit dependencies

### ISSUE THREAD

**Issue by wingsofovnia** [bufbuild/buf#1217]
My understanding is that when building (linting etc.) a workspace, all modules are passed as includes. That allows importing Protobuf files from other local modules. 

However, Workspaces do not allow:
 - Straightforward dependency tree resolution. There is no metadata in `buf.yaml` available which allows understanding what protos are needed to build a specific module in a workspace.
 - Reducing the import scope. Each module can import anything in the workspace.

Since https://github.com/bufbuild/buf/issues/1039 is apparently a wont-fix, could we have dependencies designated for workspaces (e.g. similar to NPM [Local Paths](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#local-paths))? This will allow building local module dependency tree and reduce visibility.

```yaml
# buf.work.yaml
version: v1
directories:
  - common
  - app1
  - app2

---
# common/buf.yaml
version: v1
name: company.com/team/common

---
# app1/buf.yaml
version: v1
name: company.com/team/app1
deps:
  - "workspace: common" # or "work: common" or "dir: common" or "local: common"?

---
# app2/buf.yaml
version: v1
name: company.com/team/app2
```

So that protos in `app1` can imports protos from `common` but not `app2`.

### Workarounds
To limit the import scope, `v1beta1`'s `build.roots` can be used, however, they are no longer recommended way of handling multi-module workspaces.
To create a dependency tree, Buf image from `buf build` can be analyzed.

**Comment by bufdev** [comment]
Workspaces are specifically designed as a local concept where you can import anything inside the workspace, and more to the point, Modules should not be Workspace-aware. We don't want to add anything to `buf.yaml` that changes this. Within `buf.yaml`, you have your `deps`, which tells you what other Modules you need to build the Module controlled by `buf.yaml`, and you have your `buf.lock` to tell you what versions you need.

**Comment by wingsofovnia** [comment]
@bufdev, I agree to "modules should not be Workspace-aware" but your comment doesn't really address the main issue of limiting import scope. This was just an example of how this can be done and ideally it would be https://github.com/bufbuild/buf/issues/1039, i.e. `app1/buf.yaml` becomes:
```yaml
version: v1
name: company.com/team/app1
deps:
  - "company.com/team/common"
```

I understand workspaces are supposed to be a local concept but that doesn't mean dependencies do not exist locally.
