### ISSUE TITLE
Issue with running breaking change detection with --limit-to-input-files

### ISSUE THREAD

**Issue by deveshkandpal24121990** [bufbuild/buf#123]
I'm trying to setup buf with bazel and I'm having a difficult time trying to understand what's the right way to setup breaking change detection. 

What I am trying to do is run :

```

buf check breaking --input-config buf.yaml / 
 --against-input-config buf.yaml  / 
--input protos/serviceA / 
 --against_input '.git#branch=master'  / 
--limit-to-input-files

```
My buf.yaml looks like this ( explicitly passing `--against-input-config`  because my master branch currently has no `buf.yaml` ) 

```

build:
  roots:
    - .
lint:
  use:
    - MINIMAL
  except:
    - PACKAGE_DIRECTORY_MATCH
    - PACKAGE_DEFINED
breaking:
  use:
    - WIRE

```

The error I am getting is this ->

```
against-input: targetPathsAllowNotExistOnWalk set but targetPaths not specified

```
couldn't understand what's the issue here. Appreciate all the help!
