### ISSUE TITLE
Linter not respecting ignore paths

### ISSUE THREAD

**Issue by kostyay** [bufbuild/buf#126]
Hey
My buf.yaml is configured like this:
```yaml
lint:
  use:
    - DEFAULT
    - COMMENT_ENUM
    - COMMENT_MESSAGE
    - COMMENT_RPC
    - COMMENT_SERVICE
    - PACKAGE_SAME_GO_PACKAGE
  except:
    - PACKAGE_DIRECTORY_MATCH
    - ONEOF_LOWER_SNAKE_CASE
    - PACKAGE_LOWER_SNAKE_CASE
  enum_zero_value_suffix: _INVALID
  ignore:
    - ./protoc-gen-gotag
    - ./protoc-gen-swagger
    - ./google
    - ./github.com/mwitkow
```

However I still get errors as such running `buf check lint`:
```
google/protobuf/unittest_custom_options.proto:108:12:*descriptorpb.OneofDescriptorProto protobuf_unittest.TestMessageWithCustomOptions.AnOneof: option (oneof_opt1): unrecognized extension oneof_opt1 of google.protobuf.OneofOptions
google/protobuf/unittest_custom_options.proto:301:44:message protobuf_unittest.VariousComplexOptions: option (protobuf_unittest.complex_opt3).complexoptiontype5.plugh: cannot set field plugh because complexoptiontype5 is not a message
google/protobuf/unittest_custom_options.proto:302:24:message protobuf_unittest.VariousComplexOptions: option (protobuf_unittest.complexopt6).xyzzy: cannot set field xyzzy because .protobuf_unittest.complexopt6 is not a message
```

Am I doing anything wrong? I thought everything under `google` should be ignored.

Thanks

**Comment by bufdev** [comment]
See https://buf.build/docs/lint-configuration#ignore the "relative to the root" component. Does that help?

**Comment by kostyay** [comment]
No
It still doesnt work
File file where buf.yaml is is the root (its in `/tmp/buf` in this case).
All the other packages are inside `/tmp/buf`, for example `/tmp/buf/google`

I tried removing the `./` but it still fails:
```yaml
build:
  roots:
    - ./
lint:
  use:
    - DEFAULT
    - COMMENT_ENUM
    - COMMENT_MESSAGE
    - COMMENT_RPC
    - COMMENT_SERVICE
    - PACKAGE_SAME_GO_PACKAGE
  except:
    - PACKAGE_DIRECTORY_MATCH
    - ONEOF_LOWER_SNAKE_CASE
    - PACKAGE_LOWER_SNAKE_CASE
  enum_zero_value_suffix: _INVALID
  ignore:
    - protoc-gen-gotag
    - protoc-gen-swagger
    - google
```

This is the directory structure:
```
.
├── buf.yaml
├── github.com
│   ├── mwitkow
│   │   └── go-proto-validators
│   │       └── validator.proto
│   └── kostyay
├── google
│   ├── api
│   │   ├── annotations.proto
│   │   ├── http.proto
│   │   └── httpbody.proto
│   └── protobuf
│       ├── any.proto
│       ├── api.proto
│       ├── descriptor.proto
│       ├── duration.proto
│       ├── empty.proto
│       ├── field_mask.proto
│       ├── source_context.proto
│       ├── struct.proto
│       ├── timestamp.proto
│       ├── type.proto
│       ├── unittest.proto
│       ├── unittest_arena.proto
│       ├── unittest_custom_options.proto
│       ├── unittest_drop_unknown_fields.proto
│       ├── unittest_embed_optimize_for.proto
│       ├── unittest_empty.proto
│       ├── unittest_enormous_descriptor.proto
│       ├── unittest_import.proto
│       ├── unittest_import_lite.proto
│       ├── unittest_import_public.proto
│       ├── unittest_import_public_lite.proto
│       ├── unittest_lazy_dependencies.proto
│       ├── unittest_lazy_dependencies_custom_option.proto
│       ├── unittest_lazy_dependencies_enum.proto
│       ├── unittest_lite.proto
│       ├── unittest_lite_imports_nonlite.proto
│       ├── unittest_mset.proto
│       ├── unittest_mset_wire_format.proto
│       ├── unittest_no_field_presence.proto
│       ├── unittest_no_generic_services.proto
│       ├── unittest_optimize_for.proto
│       ├── unittest_preserve_unknown_enum.proto
│       ├── unittest_preserve_unknown_enum2.proto
│       ├── unittest_proto3.proto
│       ├── unittest_proto3_arena.proto
│       ├── unittest_proto3_arena_lite.proto
│       ├── unittest_proto3_lite.proto
│       ├── unittest_proto3_optional.proto
│       ├── unittest_well_known_types.proto
│       └── wrappers.proto
├── protoc-gen-gotag
│   └── tagger
│       └── tagger.proto
└── protoc-gen-swagger
    └── options
        ├── annotations.proto
        └── openapiv2.proto
```

**Comment by bufdev** [comment]
You need to ignore these files from build, not just from lint (which relies on build). You shouldn't need to build all of https://github.com/protocolbuffers/protobuf/tree/master/src/google/protobuf. You can ignore directories with https://buf.build/docs/build-configuration#excludes, however my assumption is you are just looking to include the Well-Known Types? If so, Buf automatically includes them. That is, if you need to import any of the following files:

```
.
└── google
    └── protobuf
        ├── any.proto
        ├── api.proto
        ├── compiler
        │   └── plugin.proto
        ├── descriptor.proto
        ├── duration.proto
        ├── empty.proto
        ├── field_mask.proto
        ├── source_context.proto
        ├── struct.proto
        ├── timestamp.proto
        ├── type.proto
        └── wrappers.proto
```

You can do so automatically without these files being on disk.

**Comment by kostyay** [comment]
I use a tool called protodep to manage proto dependencies (3rd party and internal). It builds the entire proto layout for each microservice in our ecosystem.

It was not clear from the documentation that lint relies on excludes of the build. Perhaps you should update it. The following comment "We do not recommend using this option in general, however in some situations it is unavoidable." made me not want to use the exclude feature.

I will check it and report back.

**Comment by kostyay** [comment]
`excludes` doesnt work because now my proto files which are dependant on those excludes dont compile

buf.yaml
```yaml
build:
  excludes:
    - protoc-gen-gotag
    - protoc-gen-swagger
    - google
    - github.com/mwitkow
lint:
  use:
    - DEFAULT
    - COMMENT_ENUM
    - COMMENT_MESSAGE
    - COMMENT_RPC
    - COMMENT_SERVICE
    - PACKAGE_SAME_GO_PACKAGE
  except:
    - PACKAGE_DIRECTORY_MATCH
    - ONEOF_LOWER_SNAKE_CASE
    - PACKAGE_LOWER_SNAKE_CASE
  enum_zero_value_suffix: _INVALID
  ignore:
    - protoc-gen-gotag
    - protoc-gen-swagger
    - google
    - github.com/mwitkow
breaking:
  use:
    - PACKAGE
  ignore:
    - protoc-gen-gotag
    - protoc-gen-swagger
    - google
    - github.com/mwitkow
```

`buf check lint`

```
github.com/kostyay/proj1/api/internal-api/v1/f00.proto:6:8:github.com/mwitkow/go-proto-validators/validator.proto: does not exist
```

**Comment by bufdev** [comment]
We can't recommend protodep here - I think this exposes some of the key issues it has.

Linting relies on the build result, and all of protocolbuffers/protobuf is not meant to be built. The `lint.ignore` option will ignore files properly, assuming you have a working build. What you're attempting to do here is build all of protocolbuffers/protobuf.

**Comment by kostyay** [comment]
Basically as a workaround I can just remove protocolbuffers/protobuf before building?

**Comment by bufdev** [comment]
I am not sure - do you rely on any non-Well-Known-Type files from protocolbuffers/protobuf? That is the key question here.

**Comment by kostyay** [comment]
> I am not sure - do you rely on any non-Well-Known-Type files from protocolbuffers/protobuf? That is the key question here.

No I don't

**Comment by bufdev** [comment]
Then yes, per [above comment](https://github.com/bufbuild/buf/issues/126#issuecomment-671977061), you do not need to (and should not) include protocolbuffers/protobuf in your build, as this will (and should) cause issues.

**Comment by bufdev** [comment]
Closing unless there are further concerns, thanks!

**Comment by lordnynex** [comment]
I'm at a total loss here. I've spent way too long trying to get this to work. It's really driving me crazy. I don't understand how else I can use buf without duplicating third party protos. 

 I've got a similar structure from inside the `proto/` dir.

```
⚡ tree .
.
├── buf.yml
├── google
│   └── api
│       ├── annotations.proto
│       ├── http.proto
│       └── httpbody.proto
```

```yaml
build:
  roots:
    - .
  ignore:
    - google
  excludes:
    - google
lint:
  roots:
    - .
  ignore:
    - google
  use:
    - DEFAULT
    - UNARY_RPC
  except:
    - PACKAGE_DIRECTORY_MATCH
  enum_zero_value_suffix: _UNSPECIFIED
  rpc_allow_same_request_response: false
  rpc_allow_google_protobuf_empty_requests: false
  rpc_allow_google_protobuf_empty_responses: false
  service_suffix: Service
breaking:
  use:
    - WIRE_JSON
```
