### ISSUE TITLE
Generate workspace modules in the appropriate folder

### ISSUE THREAD

**Issue by tomasweigenast** [bufbuild/buf#1278]
When I define two packages in a module, like this:
(ignore errors, their are thrown by the protoc-plugin VsCode extension)

![image](https://user-images.githubusercontent.com/31850785/178981999-9c2d5005-2dad-4208-aacd-3175fa00848c.png)

> buf.work.yaml
```yaml
version: v1
directories:
  - models
  - api
```

> buf.gen.yaml
```yaml
version: v1
plugins:
  - name: dart
    out: gen/protos/dart
    opt: paths=source_relative
```

When I run **buf generate**, it outputs all the generated protos from both packages into the same folder:
![image](https://user-images.githubusercontent.com/31850785/178982485-802aa361-1e50-4f23-847b-a7f69dcd4787.png)

First four files correspond to the **api** package, and the rest to then **models** package. They should be generated to a different folder, maybe **api** for the first, and **models** for the last one?
