### ISSUE TITLE
how to ignore field extension?

### ISSUE THREAD

**Issue by MelleKoningSGG** [bufbuild/buf#1279]
I'm having a proto file that contains the following extension:

fwupdate.proto
```
message Version {
      string extension = 4 [(nanopb).max_size = 20];
}
```

the nanopb.max_size is used somewhere else in code to verify the size of the string does not go beyond 20 chars.

However when running `buf lint` on this particular file the following error occurs:

```
api/fwupdate.proto:16:29:field fwupdate.Version.extension: unknown extension nanopb
```

what rule should be added to buf.yaml to ignore the (nanopb) extension? I'm assuming a new exception can be added to

buf.yaml
```
version: v1beta1
...
lint:
  use:
    - BASIC
  except:
    - ENUM_NO_ALLOW_ALIAS
     (some exception here)
```

**Comment by amckinney** [comment]
This isn't about ignoring a lint rule - the input you have is not compiling (I suspect that you would see the same error if you ran `buf build` instead of `buf lint`).

You'll need to make sure to import the file that defines the `(nanopb).max_size` option by specifying an `import <path>` statement at the top of your `.proto` file. Ideally, this dependency exists in the BSR and you can just add it as a dependency like so:

```yaml
# buf.yaml
version: v1
deps:
  - buf.build/<nanopb_org>/<nanopb_repository>
```

Run the following command to generate a `buf.lock`:

```sh
$ buf mod update
```

Then run the `buf lint` command again and you should be good to go.
