### ISSUE TITLE
Protoc Python GRPC plugin is not found

### ISSUE THREAD

**Issue by sirakav** [bufbuild/buf#1287]
I'm having issues generating code with the `grpc_python` plugin.

> buf.gen.yaml
```
version: v1
plugins:
  - name: python
    out: apps/proto/gen/python
  - name: grpc_python
    out: apps/proto/gen/python
```

Buf output
```sh
$ buf generate
Failure: plugin grpc_python: could not find protoc plugin for name grpc_python
```

While `protoc` generates code just fine:
```
$ python3 -m grpc_tools.protoc -I apps/proto --python_out=. --grpc_python_out=. apps/proto/helloworld.proto
$ ls helloworld_pb2*
helloworld_pb2.py      helloworld_pb2_grpc.py
```

Buf works with other Python plugins like `grpclib_python`, but not with `grpc_python`.
