### ISSUE TITLE
Ignore linting errors in third-party proto definitions

### ISSUE THREAD

**Issue by andrewparmet** [bufbuild/buf#133]
I'm trying to integrate buf into my existing protobuf workflow, which uses the protobuf-gradle-plugin to manage proto dependencies.

In essence as a developer you specify your protos in `src/main/proto` and protobuf-gradle-plugin assembles the set of dependencies in another folder, which by default is located at `build/extracted-include-protos/main`.

I'd like to lint my code and ignore linting errors in third-party code. I have a config:

```yaml
build:
  roots:
    - src/main/proto
    - build/extracted-include-protos/main
lint:
  ignore:
    - build/extracted-include-protos/main
  use:
    - DEFAULT
```

But buf still reports errors from third-party code. Am I misunderstanding the `lint/ignore` configuration?
