### ISSUE TITLE
Dart plugin does not generate well known types

### ISSUE THREAD

**Issue by tomasweigenast** [bufbuild/buf#1351]
The dart plugin does not generate well-known types such as Timestamp or Duration despite Im including and using them in my proto files.

buf.gen.yaml
```yaml
version: v1
plugins:
  - remote: buf.build/protocolbuffers/plugins/dart
    out: ./
``` 

buf.yaml
```yaml
version: v1
name: buf.build/myproject/protos
deps:
  - buf.build/googleapis/googleapis:bcdcd1dee95c4277b2edbae6c21332a2
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT

```
