### ISSUE TITLE
lint throw validate.proto exists in multiple locations error

### ISSUE THREAD

**Issue by xmlking** [bufbuild/buf#1356]
I am getting `validate.proto exists in multiple locations` error

not sure from where I am getting `go-sdk` version of `protoc-gen-validate` alos into my dependencies ie., `buf.lock`

```
buf lint                                                    
xyz.proto:6:8:validate/validate.proto exists in multiple locations: validate/validate.proto validate/validate.proto
```

my `buf.yml`

```
version: v1
name: buf.build/xyz/policyapis
deps:
  - buf.build/srikrsna/protoc-gen-gotag
  - buf.build/envoyproxy/protoc-gen-validate

lint:
  use:
    - DEFAULT
    - FILE_LOWER_SNAKE_CASE
breaking:
  use:
    - WIRE_JSON

```

my `buf.lock`
```
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: envoyproxy
    repository: protoc-gen-validate
    commit: 45685e052c7e406b9fbd441fc7a568a5
  - remote: buf.build
    owner: go-sdk
    repository: protoc-gen-validate
    commit: 49246dc23b1b4ba98e36c9ce8eb8fd0c
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: 80720a488c9a414bb8d4a9f811084989
  - remote: buf.build
    owner: srikrsna
    repository: protoc-gen-gotag
    commit: 04b38c6f540d4d2fa9cfd49ae01ae73b
```
