### ISSUE TITLE
Bump version of Go plugin 1.27.1 to 1.28.1

### ISSUE THREAD

**Issue by dewey** [bufbuild/buf#1361]
Hey, I'm not sure if that's the place to ask, but I couldn't find a plugin specific issue tracker. I'm switching to the remote plugin in my buf.gen.yaml file and after running `bug generate` it's downgrading the version. Here are my `buf.gen.yaml` files.

Before:
```
plugins:
 - name: go
   out: gen/proto/go
   opt: paths=source_relative
 - name: go-grpc
   out: gen/proto/go
   opt:
     - paths=source_relative
     - require_unimplemented_servers=false
```

After:

```
plugins:
  - remote: buf.build/library/plugins/go:v1.27.1-1
    out: gen/proto/go
    opt: paths=source_relative
  - remote: buf.build/grpc/plugins/go:v1.2.0-1
    out: gen/proto/go
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false
```

It looks like the latest version on https://buf.build/library/plugins/go is `v1.27.1-1` while the latest version on https://github.com/protocolbuffers/protobuf-go is [v1.28.1](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.28.1).

Is that the reason, or am I using the wrong plugin?

Thanks!
