### ISSUE TITLE
php managed mode is not work

### ISSUE THREAD

**Issue by bai-ming** [bufbuild/buf#1365]
I need use php_namespace to control the class name,
![image](https://user-images.githubusercontent.com/85221235/187138299-01dcc2d6-18b0-4787-abcc-414f0cefe9c6.png)
I follow the docs and write this code 
![image](https://user-images.githubusercontent.com/85221235/187138224-e3ab8033-3ecb-49f2-bf3f-e8b7fe9d561c.png)
but it doesn't work.
![image](https://user-images.githubusercontent.com/85221235/187138581-c78c3212-bfc2-48c9-881e-31f3176ab485.png)
so I find the type of the package.
![image](https://user-images.githubusercontent.com/85221235/187138808-45305d8e-81a8-40d9-b281-3e023492c00d.png)
Is PHP not support?

**Comment by timostamm** [comment]
Hey @bai-ming, managed mode is supported in managed mode, but there might be a misunderstanding how it works.
Managed mode sets options for you automatically, which means you don't need to specify any configuration, except enabling managed mode:

```yaml
version: v1
managed:
  enabled: true
plugins:
  - remote: buf.build/grpc/plugins/php:v1.48.0-1
    out: slave
  - remote: buf.build/protocolbuffers/plugins/php:v21.5.0-1
    out: slave
```

Let's say you want to generate our [demo service](https://buf.build/bufbuild/eliza):

```shell
buf generate buf.build/bufbuild/eliza
```

This will give you the following output:

```bash
.
├── buf.gen.yaml
└── slave
    └── Buf
        └── Connect
            └── Demo
                └── Eliza
                    └── V1
                        ├── ConverseRequest.php
                        ├── ConverseResponse.php
                        ├── ElizaServiceClient.php
                        ├── GPBMetadata
                        │   └── Eliza.php
                        ├── IntroduceRequest.php
                        ├── IntroduceResponse.php
                        ├── SayRequest.php
                        └── SayResponse.php
```

`buf` sets the file options `php_namespace` and `php_metadata_namespace` automatically, based on the protobuf package names.

If you don't want that, you have two options:
1. Don't use managed mode, and set the file options yourself in the protobuf source files.
2. Use an override.

An override in managed mode for PHP looks like this:

```yaml
version: v1
managed:
  enabled: true
  override:
    PHP_NAMESPACE:
      buf/connect/demo/eliza/v1/eliza.proto: eastblue
    PHP_METADATA_NAMESPACE:
      buf/connect/demo/eliza/v1/eliza.proto: eastblue\GPBMetadata
plugins:
  - remote: buf.build/grpc/plugins/php:v1.48.0-1
    out: slave
  - remote: buf.build/protocolbuffers/plugins/php:v21.5.0-1
    out: slave
```

The output is:

```bash
.
├── buf.gen.yaml
├── buf.gen.yaml-o
└── slave
    └── eastblue
        ├── ConverseRequest.php
        ├── ConverseResponse.php
        ├── ElizaServiceClient.php
        ├── GPBMetadata
        │   └── Eliza.php
        ├── IntroduceRequest.php
        ├── IntroduceResponse.php
        ├── SayRequest.php
        └── SayResponse.php
```

Note that you have to set the override for each file. 

Hope this helps you get started. I'm closing this issue because everything seems to work.
