### ISSUE TITLE
BSR tags for googleapis/googleapis are missing 

### ISSUE THREAD

**Issue by andremarianiello** [bufbuild/buf#1380]
My buf commands have started producing
```
Failure: buf.build/googleapis/googleapis:8abb121752d4454db5546c3b4653b450
```

Here is my buf.lock file
```
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: envoyproxy
    repository: protoc-gen-validate
    commit: dc09a417d27241f7b069feae2cd74a0e
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: 8abb121752d4454db5546c3b4653b450
  - remote: buf.build
    owner: grpc-ecosystem
    repository: grpc-gateway
    commit: ff83506eb9cc4cf8972f49ce87e6ed3e
 ```
 
 https://buf.build/googleapis/googleapis/tags/main contains only two tags, both from today 
![image](https://user-images.githubusercontent.com/3359229/188727579-cc21bd27-a029-4ecb-b983-ab7a32974b88.png)

Seems like something deleted all tags from before today? Does anyone have any idea what is going on?
