### ISSUE TITLE
Cannot generate, network errors

### ISSUE THREAD

**Issue by wrossmorrow** [bufbuild/buf#1382]
Related to https://github.com/bufbuild/buf/issues/824 and https://github.com/bufbuild/buf/issues/294

Cannot `generate` with a network error. I've had a lot of success and it has just stopped working. 

Original context deadline error: 
```
buf -v generate buf.build/googleapis/googleapis --path google/api/annotations.proto --path google/api/http.proto --path google/rpc/error_details.proto --path google/rpc/status.proto --path google/rpc/code.proto
Failure: Post "https://api.buf.build/buf.alpha.registry.v1alpha1.GenerateService/GeneratePlugins": context deadline exceeded
```

I switched some `generate` orders and tried `--timeout`: 
```
buf -v generate buf.build/envoyproxy/protoc-gen-validate --timeout 5m
Failure: the server hosted at that remote is unavailable.
```

I can reach `api.buf.build`: 
```
$ curl -I https://api.buf.build/
HTTP/2 404 
vary: Accept-Encoding
date: Tue, 06 Sep 2022 23:03:47 GMT
server: envoy
```

Latest version: 
```
$ buf --version
1.7.0
```

`buf.yaml`: 
```
version: v1
name: buf.build/my-company/protos
build:
  excludes:
    - demo
deps:
  - buf.build/googleapis/googleapis
  - buf.build/envoyproxy/protoc-gen-validate
lint:
  use:
    - DEFAULT
breaking:
  ignore_unstable_packages: true
  use:
    - FILE
```

`buf.lock`: 
```
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: envoyproxy
    repository: protoc-gen-validate
    commit: 45685e052c7e406b9fbd441fc7a568a5
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: 62f35d8aed1149c291d606d958a7ce32
```

`buf.gen.yaml`:
```
version: v1
managed: 
  enabled: true
plugins:
  - remote: buf.build/protocolbuffers/plugins/python:v3.19.1-1
    out: generated/python/standard
  - remote: buf.build/grpc/plugins/python:v1.41.1-1
    out: generated/python/standard
  - remote: buf.build/jeffsawatzky/plugins/mypy-protobuf:v3.2.0-1
    out: generated/python/standard
  - remote: buf.build/jeffsawatzky/plugins/mypy-grpc-protobuf:v3.2.0-1
    out: generated/python/standard
  - remote: buf.build/grpc-ecosystem/plugins/openapiv2:v2.11.2-1
    out: generated/openapi
```
