### ISSUE TITLE
`buf mod update` should disregard `buf.yaml#name` in workspaces

### ISSUE THREAD

**Issue by wingsofovnia** [bufbuild/buf#1384]
As many other users, I recently discovered my local [workspace](https://docs.buf.build/reference/workspaces) is broken due to https://github.com/bufbuild/buf/issues/1380:
```
❯ buf lint team-project
Failure: buf.build/googleapis/googleapis:cac7f97f0d3a4c3d9d2004f475c0553c: does not exist
```

I tried updating the dependency but got this:
```
❯ buf mod update team-project
Failure:
```

Which after updating to the latest buf turned into:
```
❯ buf mod update team-project
Failure: 404 Not Found
```

By trial and error I found out removing `team-project/buf.yaml#name` solves the issue:
```yaml
version: v1
# name: example.com/team/project # uncomment me after running buf mod update
deps:
  - buf.build/googleapis/googleapis
```

Although `name` is not needed in local workspaces, which mine is, I am using non-`buf.build` repo (`example.com`) for analyzing which inter-module dependencies are local and which ones come from `buf.build` (external) by looking at a Buf image (`ModuleInfo`).

I believe `buf mod update` should disregard `name` in workspaces/unpublished modules/custom domains and do only and exactly what its `--help` says: `Update a module's dependencies by updating the buf.lock file`.
