### ISSUE TITLE
Error message when using absolute imports

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [bufbuild/buf#1406]
When I run `buf lint` I get:

> api/services/control/control.proto:5:8:buf.build/gogo/protobuf/gogoproto/gogo.proto: does not exist

Which seems strange to me because I explicitly specified it in `/buf.yaml`:
```yaml
version: v1
name: buf.build/moby/buildkit
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
deps:
- buf.build/gogo/protobuf
build:
  excludes:
  - vendor
```

So in `api/services/control/control.proto` neither works:

```proto
import "gogo/protobuf/gogoproto/gogo.proto";
import "buf.build/gogo/protobuf/gogoproto/gogo.proto";
```
