### ISSUE TITLE
Failure: buf.build/googleapis/googleapis:8f04c867ddf14e13a231d5119b8ebb8b: does not exist

### ISSUE THREAD

**Issue by acrazing** [bufbuild/buf#1409]
It seems that `buf.build/googleapis/googleapis` was recreated and `buf.build/envoyproxy/protoc-gen-validate` depended on an old version.

This is my `buf.lock` file content:

```yaml
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: envoyproxy
    repository: protoc-gen-validate
    commit: 45685e052c7e406b9fbd441fc7a568a5
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: 8d7204855ec14631a499bd7393ce1970
```
