### ISSUE TITLE
Publish JSON schemas for various yaml and lock configuration files

### ISSUE THREAD

**Issue by mxplusb** [bufbuild/buf#1413]
Are the configuration schemas published anywhere? It'd be helpful if I could configure vscode/Goland to use the configuration schemas when editing `buf{.gen,.work}.yaml` files, then basic linting is available.

**Comment by robbertvanginkel** [comment]
We have human readable documentation for these files at:

- https://docs.buf.build/configuration/v1/buf-yaml
- https://docs.buf.build/configuration/v1/buf-lock
- https://docs.buf.build/configuration/v1/buf-gen-yaml
- https://docs.buf.build/configuration/v1/buf-work-yaml

I don't believe we publish any machine readable schema's for that today. What machine readable format would you need for your editor of choice to be able to interpret it?

**Comment by mxplusb** [comment]
The standard JSON schema syntax should be fine, since that's what most editors support. JSON schemas can be used to validate YAML as well, so I don't think there would be a need. You can also represent multiple schemas in a single file, which makes it easier to maintain. 

I'm only asking as it's a low-hanging fruit for a better dev experience, the website reference has definitely helped too 🙂

**Comment by felschr** [comment]
Ideally the schemas will (also) be published on https://www.schemastore.org/json/.
Some tools can then automatically pull them based on the filename, e.g. [yaml-language-server](https://github.com/redhat-developer/yaml-language-server).

**Comment by stefanvanburen** [comment]
I contributed support upstream for buf.yaml, buf.gen.yaml, and buf.work.yaml over in https://github.com/SchemaStore/schemastore/pull/3310. (I skipped buf.lock as it's not meant to be edited manually.) I'm happy to continue maintaining these as we adjust the formats, although they don't change very often!

If you see issues with the schema, please report those [upstream](https://github.com/SchemaStore/schemastore) - since the schemas are published there (at least, for now), isn't anything we can do in this repo - and feel free to tag me.

@bufdev I think we can close this one for now.

**Comment by Goldziher** [comment]
seems to work!

for this yaml:

```yaml
version: v1
build:
    excludes: [node_modules]
lint:
    use:
        - DEFAULT
        - COMMENTS
        - PACKAGE_NO_IMPORT_CYCLE
    except:
        - RPC_REQUEST_RESPONSE_UNIQUE
        - RPC_REQUEST_STANDARD_NAME
        - RPC_RESPONSE_STANDARD_NAME
    service_suffix: Service
    allow_comment_ignores: true
breaking:
    use:
        - FILE
```

One issue -- it doesn't like `PACKAGE_NO_IMPORT_CYCLE`:

```text
Schema validation: Value should be one of: "DEFAULT", "BASIC", "MINIMAL", "COMMENTS", "UNARY_RPC", "DIRECTORY_SAME_PACKAGE", "PACKAGE_DEFINED", "PACKAGE_DIRECTORY_MATCH", "PACKAGE_SAME_DIRECTORY", "ENUM_PASCAL_CASE", "ENUM_VALUE_UPPER_SNAKE_CASE", "FIELD_LOWER_SNAKE_CASE", "MESSAGE_PASCAL_CASE", "ONEOF_LOWER_SNAKE_CASE", "PACKAGE_LOWER_SNAKE_CASE", "RPC_PASCAL_CASE", "SERVICE_PASCAL_CASE", "PACKAGE_SAME_CSHARP_NAMESPACE", "PACKAGE_SAME_GO_PACKAGE", "PACKAGE_SAME_JAVA_MULTIPLE_FILES", "PACKAGE_SAME_JAVA_PACKAGE", "PACKAGE_SAME_PHP_NAMESPACE", "PACKAGE_SAME_RUBY_PACKAGE", "PACKAGE_SAME_SWIFT_PREFIX", "ENUM_FIRST_VALUE_ZERO", "ENUM_NO_ALLOW_ALIAS", "IMPORT_NO_WEAK", "IMPORT_NO_PUBLIC", "IMPORT_USED", "ENUM_VALUE_PREFIX", "ENUM_ZERO_VALUE_SUFFIX", "FILE_LOWER_SNAKE_CASE", "RPC_REQUEST_RESPONSE_UNIQUE", "RPC_REQUEST_STANDARD_NAME", "RPC_RESPONSE_STANDARD_NAME", "PACKAGE_VERSION_SUFFIX", "SERVICE_SUFFIX"
```
