### ISSUE TITLE
generate a bad import `<gomodule>/google/api` for go by `buf generate` when use grpc-gateway

### ISSUE THREAD

**Issue by lazychanger** [bufbuild/buf#1421]
**env**
GOHOSTARCH: amd64
GOHOSTOS: darwin
buf version: 1.8.0
protoc-gen-go: v1.28.1
protoc: libprotoc 3.21.6
protoc-gen-grpc-gateway: Version dev, commit unknown, built at unknown

**buf.yaml**
```yaml
version: v1
name: buf.build/example/protobuf
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
lint:
  use:
    - DEFAULT
  ignore_only:
    RPC_REQUEST_RESPONSE_UNIQUE:
      - api/backendpb/v1/echo.proto
  allow_comment_ignores: true
breaking:
  use:
    - FILE
build:
  excludes:
    - vendor
```

**buf.gen.yaml**
```yaml
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: <gomodule>
plugins:
  - name: go
    out: .
    opt:
      - paths=source_relative
```

**dir**
```txt
| -api
| - - backendpb
| - - -v1
| - - - - echo.pb.go
| - - - - echo.proto
```

**example proto**
```protobuf
syntax = "proto3";

// Echo Service
//
// Echo Service API consists of a single service which returns
// a message.
package api.backendpb.v1;

import "google/api/annotations.proto";

// Embedded represents a message embedded in SimpleMessage.
message Embedded {
  oneof mark {
    int64 progress = 1;
    string note = 2;
  }
}

// SimpleMessage represents a simple message sent to the Echo service.
message SimpleMessage {
  // Id represents the message identifier.
  string id = 1;
  int64 num = 2;
  oneof code {
    int64 line_num = 3;
    string lang = 4;
  }
  Embedded status = 5;
  oneof ext {
    int64 en = 6;
    Embedded no = 7;
  }
}

// Echo service responds to incoming echo requests.
service EchoService {
  // Echo method receives a simple message and returns it.
  //
  // The message posted as the id parameter will also be
  // returned.
  rpc Echo(SimpleMessage) returns (SimpleMessage) {
    option (google.api.http) = {
      get: "/v1/example/echo/{id}"
    };
  }
}
```

**buf generated**
```go
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: api/backendpb/v1/echo.proto

// Echo Service
//
// Echo Service API consists of a single service which returns
// a message.

package backendpbv1

import (
	_ "<gomodule>/google/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

// more...

```
**protoc command**
```shell
 protoc -I . \          
-I ~/.cache/buf/v1/module/data/buf.build/googleapis/googleapis/8d7204855ec14631a499bd7393ce1970 \
-I ~/.cache/buf/v1/module/data/buf.build/grpc-ecosystem/grpc-gateway/bc28b723cd774c32b6fbc77621518765 \
--go_out=. \
./api/backendpb/v1/echo.proto 
```
**protoc generated**
```go
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: api/backendpb/v1/echo.proto

// Echo Service
//
// Echo Service API consists of a single service which returns
// a message.

package backendpbv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)
// more...
```

**problem**
As you can see, the first line of the generated GO file imports `_ "<gomodule>/google/api"` is wrong import. I am use the protoc to generated is true; i don't known what's happend.

**Comment by robbertvanginkel** [comment]
By using managed mode for go, all `go_package` file options get overrides based on your specified `default`, including proto files from module dependencies.

This is mostly the desired behavior, unless the protos have a canonical published version (which is the case for googleapis). For this, managed mode allows you to exclude dependent modules from overrides using the `except` setting: https://docs.buf.build/generate/managed-mode#except.
```diff
 managed:
   enabled: true
   java_multiple_files: false
   java_package_prefix: com
   java_string_check_utf8: false
   go_package_prefix:
     default: <gomodule>
+      except:
+        - buf.build/googleapis/googleapis
```

I'm not sure if grpc-gateway has a package of published protos along the lines of `google.golang.org/genproto`, if so you may want to set the except key there as well.

**Comment by lazychanger** [comment]
Thanks your help, it works
:)

**Comment by pd93** [comment]
For anyone stumbling across this recently (like me), the syntax for this has how changed due to the v2 schema:

```yaml
version: v2
 managed:
   enabled: true
   disable:
     # Disables all go_package changes for this module only
     - file_option: go_package
       module: buf.build/googleapis/googleapis
```
