### ISSUE TITLE
Support inputs in buf.gen.yaml

### ISSUE THREAD

**Issue by Aqours** [bufbuild/buf#1424]
## Usage Scenario

Generate multiple BSR modules

```
buf generate buf.build/googleapis/example1
buf generate buf.build/googleapis/example2
buf generate buf.build/googleapis/example3
```

## Expected

1. Support multiple input modules

```sh
buf generate buf.build/googleapis/example1 \
             buf.build/googleapis/example2 \
             buf.build/googleapis/example3
```

2. Support config in `buf.gen.yaml`

```yaml
version: v1
plugins:
  - name: xxx
modules:
  - buf.build/googleapis/example1
    buf.build/googleapis/example2
    buf.build/googleapis/example3
```

```
buf generate
```

**Comment by robbertvanginkel** [comment]
Regarding point 2, `buf.gen.yaml`'s intention is to be input agnostic and the current stance is that we will not support inputs in the generate config file (see also https://github.com/bufbuild/buf/issues/510). Similarly various parts of buf are designed to operate on one module at a time and there are no plans to support multi module inputs. If you have a need to have only one buf invocation, would `xargs -n1` suit your needs?

Based on  https://github.com/bufbuild/buf/issues/1407#issuecomment-1248761198 we may revisit the input agnostic idea of buf.gen.yaml in the future. This ticket is linked now and we'll take the feedback into account for those discussions.

**Comment by bufdev** [comment]
This isn't going to happen in the near-term, but is something we're reconsidering. Generally, we may want buf.gen.yaml files to be input-aware. Going to keep open for now.

**Comment by bufdev** [comment]
When looking at this issue in the future, we should also look at https://github.com/bufbuild/buf/issues/1407 - going to close that issue and track this only here.

**Comment by oliversun9** [comment]
`buf.gen.yaml` v2 supports [multiple inputs](https://buf.build/docs/configuration/v2/buf-gen-yaml#inputs) now. Your file may look like:
```
version: v2
plugins:
# ...
inputs:
  - module: buf.build/googleapis/example1
  - module: buf.build/googleapis/example2
  - module: buf.build/googleapis/example3
```

Before adding an inputs section, you can have the rest of your `buf.gen.yaml` ready by running [the migration command](https://buf.build/docs/migration-guides/migrate-v2-config-files):
```
buf config migrate
```
or
```
buf config migrate --buf-gen-yaml path/to/buf.gen.yaml
```
if your `buf.gen.yaml` is not at the current directory or named differently. Use the `--diff` flag to only display the difference between your upgraded and current file.
