### ISSUE TITLE
Download remote plugins failed

### ISSUE THREAD

**Issue by fangxlmr** [bufbuild/buf#1429]
I want to `buf generate` proto stubs for golang and python, and it ends up with error `Failure: Post "https://api.buf.build/buf.alpha.registry.v1alpha1.GenerateService/GeneratePlugins": context deadline exceeded`.

Besides, I stucked in this page for quite a time.

<img width="1898" alt="image" src="https://user-images.githubusercontent.com/37577088/191746380-9cde1b45-199e-4250-9a3a-86f307c56cee.png">

Is remote plugin download service down?

`buf.gen.yaml` is
```yaml
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: xxx
plugins:
  - remote: buf.build/protocolbuffers/plugins/go:v1.28.1-1
    out: .
    opt: paths=source_relative
  - remote: buf.build/grpc/plugins/go:v1.2.0-1
    out: .
    opt:
      - paths=source_relative
      - require_unimplemented_servers=true
  - remote: buf.build/protocolbuffers/plugins/python:v3.19.1-1
    out: .
  - remote: buf.build/grpc/plugins/python:v1.41.1-1
    out: .
```
