### ISSUE TITLE
How to use proto mapping

### ISSUE THREAD

**Issue by aqaurius6666** [bufbuild/buf#1454]
I have used plugin protoc-gen-gogo to generate go files. In some case, I want to re mapping .proto to other go packages.
For example:
```
protoc --gogo_opt paths=source_relative --gogo_out=plugins=grpc,Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types:. example.proto
```
This will remap any package from google/protobuf source to gogo/protobuf.

I have searched in issues, or google but have no clue. 

After random tries, I found a solution that:
```
plugins:
  - name: gogo
    out: plugins=grpc,Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types:../pkg/pb
    opt: 
      - paths=source_relative
```

Hope this will help you guys!!
