### ISSUE TITLE
Unable to use rust prost as remote plugin due to character limit

### ISSUE THREAD

**Issue by cortopy** [bufbuild/buf#1458]
Thanks to community efforts, it's now possible to use `buf` to generate rust code. The plugin for the [prost crate](https://github.com/neoeinstein/protoc-gen-prost) is also available as a remote plugin. It works really great, except prost may require a lot of annotations. Other languages support writing comments and indications in the proto definition files, but this is not the case with rust/ prost. So configuration may be bigger than in other cases.

For example, when I try to build with this template:

```yaml
version: v1
plugins:
  - remote: buf.build/prost/plugins/prost:v0.2.0-2
    out: gen
    opt:
      - type_attribute=.address.v1.Address=#[derive(serde::Deserialize\, serde::Serialize\, validator::Validate)]
      - field_attribute=.address.v1.Address.line1=#[validate(length(min = 2\, message = "First line of address is required"))]
      - field_attribute=.address.v1.Address.postal_code=#[validate(length(min = 2\, message = "Postcode is required"))]
      - field_attribute=.address.v1.Address.administrative_level2=#[validate(length(min = 2\, message = "City is required"))]
      - type_attribute=.address.v1.AddressDetails=#[derive(serde::Deserialize\, serde::Serialize\, validator::Validate)]
      - field_attribute=.address.v1.AddressDetails.name=#[validate(length(min = 2\, message = "First name is required"))]
```

I'm getting an error because the parameter `must be at least 1 and at most 512 characters`.

In fact, my `opt` section is 55 lines long, since I need to annotate a few types.

The template works fine when using locally installed plugin like:

```yaml
plugins:
  - name: prost
    out: gen
    opt:
```

Based on this, would it be possible to remove the char limit for remote plugins?
