### ISSUE TITLE
question: using buf requires to put vendor in import

### ISSUE THREAD

**Issue by marbar3778** [bufbuild/buf#15]
By using buf to be able to run linting or break checking I have to import things like so: `import "vendor/github.com/gogo/protobuf/gogoproto/gogo.proto";` is there a way to avoid having to use `vendor` 

here is the buf.yaml file:
```
build:
  roots:
    - .
  excludes:
    - vendor/github.com/tendermint
lint:
  use:
    - DEFAULT
    - COMMENTS
    - FILE_LOWER_SNAKE_CASE
  except:
    - UNARY_RPC
    - COMMENT_FIELD
    - PACKAGE_DIRECTORY_MATCH
  ignore:
    - vendor
breaking:
  use:
    - FILE
```

**Comment by bufdev** [comment]
Add `vendor/github.com/gogo/protobuf` as a root, however this means you can't have `.` as a root: https://buf.build/docs/build-configuration#root-requirements

The setup we'd recommend IF you took this path (see below):

- Have your main sources in a directory `proto`, and derive imports from there.
- Add your vendors as additional roots.

This would lead to:

```yaml
build:
  roots:
    - proto
    - vendor/github.com/gogo/protobuf
```

And then you can `import "gogoproto/gogo.proto"`. However, note that `lint.ignore` paths are relative to the roots: https://buf.build/docs/lint-configuration#ignore

So this is going to lead to an issue where all the other files in `github.com/gogo/protobuf` are difficult to ignore:

```
$ git remote -v
origin	https://github.com/gogo/protobuf (fetch)
origin	https://github.com/gogo/protobuf (push)
$ find . -name *.proto
./vanity/test/proto3.proto
./vanity/test/vanity.proto
./vanity/test/gogovanity.proto
./proto/test_proto/test.proto
./proto/proto3_proto/proto3.proto
./test/sizeunderscore/sizeunderscore.proto
./test/protobuffer/protobuffer.proto
./test/typedeclimport/subpkg/subpkg.proto
./test/typedeclimport/typedeclimport.proto
./test/issue427/issue427.proto
./test/issue411/issue411.proto
./test/embedconflict/em.proto
./test/embedconflict/er.proto
./test/embedconflict/en.proto
./test/embedconflict/eb.proto
./test/embedconflict/ee.proto
./test/embedconflict/ec.proto
./test/oneof3/combos/both/one.proto
./test/oneof3/combos/unmarshaler/one.proto
./test/oneof3/combos/neither/one.proto
./test/oneof3/combos/marshaler/one.proto
./test/oneof3/one.proto
./test/registration/registration.proto
./test/issue444/issue444.proto
./test/issue270/a/a1.proto
./test/issue270/a/a2.proto
./test/issue270/b/b.proto
./test/cachedsize/cachedsize.proto
./test/thetest.proto
./test/types/combos/both/types.proto
./test/types/combos/unmarshaler/types.proto
./test/types/combos/neither/types.proto
./test/types/combos/marshaler/types.proto
./test/types/types.proto
./test/protosize/protosize.proto
./test/enumcustomname/enumcustomname.proto
./test/proto3extension/proto3ext.proto
./test/enumstringer/enumstringer.proto
./test/unrecognizedgroup/unrecognizedgroup.proto
./test/merge/merge.proto
./test/issue530/issue530.proto
./test/group/group.proto
./test/example/example.proto
./test/xxxfields/xxxfields.proto
./test/combos/both/thetest.proto
./test/combos/unmarshaler/thetest.proto
./test/combos/marshaler/thetest.proto
./test/oneofembed/oneofembed.proto
./test/setextensionbytes/setextensionbytes.proto
./test/dashfilename/dash-filename.proto
./test/nopackage/nopackage.proto
./test/typedecl_all/typedeclall.proto
./test/unmarshalmerge/unmarshalmerge.proto
./test/importdedup/proto.proto
./test/importdedup/subpkg/subproto.proto
./test/unrecognized/unrecognized.proto
./test/deterministic/deterministic.proto
./test/empty-issue70/empty.proto
./test/issue435/issue435.proto
./test/issue262/timefail.proto
./test/enumdecl_all/enumdeclall.proto
./test/fuzztests/fuzz.proto
./test/issue630/issue630.proto
./test/int64support/object.proto
./test/importcustom-issue389/imported/a.proto
./test/importcustom-issue389/importing/c.proto
./test/packed/packed.proto
./test/required/requiredexample.proto
./test/issue42order/issue42.proto
./test/asymetric-issue125/asym.proto
./test/typedecl/typedecl.proto
./test/tags/tags.proto
./test/mapdefaults/combos/both/map.proto
./test/mapdefaults/combos/unmarshaler/map.proto
./test/mapdefaults/combos/neither/map.proto
./test/mapdefaults/combos/marshaler/map.proto
./test/mapdefaults/map.proto
./test/issue620/issue620.proto
./test/filedotname/file.dot.proto
./test/issue617/issue617.proto
./test/issue449/issue449.proto
./test/moredefaults/md.proto
./test/importduplicate/proto/proto.proto
./test/importduplicate/sortkeys/sortable.proto
./test/importduplicate/importduplicate.proto
./test/issue503/issue503.proto
./test/defaultconflict/df.proto
./test/defaultconflict/ne.proto
./test/defaultconflict/nx.proto
./test/defaultconflict/nc.proto
./test/defaultconflict/dg.proto
./test/issue330/issue330.proto
./test/mapsproto2/header.proto
./test/mapsproto2/combos/both/mapsproto2.proto
./test/mapsproto2/combos/unmarshaler/mapsproto2.proto
./test/mapsproto2/combos/neither/mapsproto2.proto
./test/mapsproto2/combos/marshaler/mapsproto2.proto
./test/mapsproto2/mapsproto2.proto
./test/indeximport-issue72/indeximport.proto
./test/indeximport-issue72/index/index.proto
./test/stdtypes/stdtypes.proto
./test/issue322/issue322.proto
./test/issue34/proto.proto
./test/oneof/combos/both/one.proto
./test/oneof/combos/unmarshaler/one.proto
./test/oneof/combos/neither/one.proto
./test/oneof/combos/marshaler/one.proto
./test/oneof/one.proto
./test/enumprefix/enumprefix.proto
./test/castvalue/castvalue.proto
./test/castvalue/combos/both/castvalue.proto
./test/castvalue/combos/unmarshaler/castvalue.proto
./test/castvalue/combos/marshaler/castvalue.proto
./test/sizerconflict/sizerconflict.proto
./test/issue312/issue312.proto
./test/issue312/events/events.proto
./test/casttype/combos/both/casttype.proto
./test/casttype/combos/unmarshaler/casttype.proto
./test/casttype/combos/neither/casttype.proto
./test/casttype/combos/marshaler/casttype.proto
./test/casttype/casttype.proto
./test/custombytesnonstruct/proto.proto
./test/data/data.proto
./test/issue8/proto.proto
./test/issue498/issue498.proto
./test/theproto3/header.proto
./test/theproto3/combos/both/theproto3.proto
./test/theproto3/combos/unmarshaler/theproto3.proto
./test/theproto3/combos/neither/theproto3.proto
./test/theproto3/combos/marshaler/theproto3.proto
./test/theproto3/theproto3.proto
./test/theproto3/footer.proto
./test/theproto3/maps.proto
./test/issue438/issue438.proto
./test/issue260/issue260.proto
./test/enumdecl/enumdecl.proto
./test/issue261/issue261.proto
./gogoproto/gogo.proto
./jsonpb/jsonpb_test_proto/test_objects.proto
./jsonpb/jsonpb_test_proto/more_test_objects.proto
./protoc-gen-gogo/testdata/extension_extra/extension_extra.proto
./protoc-gen-gogo/testdata/grpc/grpc.proto
./protoc-gen-gogo/testdata/grpc/grpc_empty.proto
./protoc-gen-gogo/testdata/multi/multi1.proto
./protoc-gen-gogo/testdata/multi/multi3.proto
./protoc-gen-gogo/testdata/multi/multi2.proto
./protoc-gen-gogo/testdata/import_public/b.proto
./protoc-gen-gogo/testdata/import_public/a.proto
./protoc-gen-gogo/testdata/import_public/sub/b.proto
./protoc-gen-gogo/testdata/import_public/sub/a.proto
./protoc-gen-gogo/testdata/import_public/importing/importing.proto
./protoc-gen-gogo/testdata/extension_user/extension_user.proto
./protoc-gen-gogo/testdata/imports/test_a_1/m1.proto
./protoc-gen-gogo/testdata/imports/test_a_1/m2.proto
./protoc-gen-gogo/testdata/imports/test_import_a1m2.proto
./protoc-gen-gogo/testdata/imports/fmt/m.proto
./protoc-gen-gogo/testdata/imports/test_import_all.proto
./protoc-gen-gogo/testdata/imports/test_b_1/m1.proto
./protoc-gen-gogo/testdata/imports/test_b_1/m2.proto
./protoc-gen-gogo/testdata/imports/test_import_a1m1.proto
./protoc-gen-gogo/testdata/imports/test_a_2/m3.proto
./protoc-gen-gogo/testdata/imports/test_a_2/m4.proto
./protoc-gen-gogo/testdata/my_test/test.proto
./protoc-gen-gogo/testdata/proto3/proto3.proto
./protoc-gen-gogo/testdata/extension_base/extension_base.proto
./protoc-gen-gogo/testdata/deprecated/deprecated.proto
./protobuf/google/protobuf/timestamp.proto
./protobuf/google/protobuf/field_mask.proto
./protobuf/google/protobuf/api.proto
./protobuf/google/protobuf/duration.proto
./protobuf/google/protobuf/struct.proto
./protobuf/google/protobuf/wrappers.proto
./protobuf/google/protobuf/source_context.proto
./protobuf/google/protobuf/any.proto
./protobuf/google/protobuf/type.proto
./protobuf/google/protobuf/empty.proto
./protobuf/google/protobuf/compiler/plugin.proto
./protobuf/google/protobuf/descriptor.proto
./conformance/internal/conformance_proto/conformance.proto
```

If you still want to stick with this setup, you'll have to ignore each directory relative to `github.com/gogo/protobuf`:

```yaml
build:
  roots:
    - proto
    - vendor/github.com/gogo/protobuf
lint:
  ignore:
    - conformance
    - gogoproto
    - jsonpb
    - proto
    - protobuf
    - protoc-gen-gogo
    - test
    - vanity
breaking:
  ignore:
    - conformance
    - gogoproto
    - jsonpb
    - proto
    - protobuf
    - protoc-gen-gogo
    - test
    - vanity
```

However, we don't recommend this strategy - this is relying on Golang tooling (i.e. the copy to `vendor`) to maintain your Protobuf file versioning.

Instead, we'd recommend:

- Copying `gogo.proto` to a `third_party/proto/gogoproto/gogo.proto` directory.
- Having the following config:

```yaml
build:
  roots:
    - proto
    - third_party/proto
lint:
  ignore:
    - gogoproto
breaking:
  ignore:
    - gogoproto
```

In the future, we hope to have paths for external dependencies with the [Buf Schema Registry](https://buf.build/docs/roadmap), however this is a work in progress.

**Comment by bufdev** [comment]
Another option if you stick with the `vendor` option is to add to `build.exclude`:

```yaml
build:
  roots:
    - proto
    - vendor/github.com/gogo/protobuf
  exclude:
    - github.com/gogo/protobuf/conformance
    - github.com/gogo/protobuf/jsonpb
    - github.com/gogo/protobuf/proto
    - github.com/gogo/protobuf/protobuf
    - github.com/gogo/protobuf/protoc-gen-gogo
    - github.com/gogo/protobuf/test
    - github.com/gogo/protobuf/vanity
```
