### ISSUE TITLE
cannot unmarshal !!str `buf.yml`

### ISSUE THREAD

**Issue by downright-ux** [bufbuild/buf#151]
When trying to us buf on one of my repo's it looks like it keeps running the default for lint and break check.
I have a yaml for basic testing in the same folder directory as what I want to test. I run the cmd's also within the directory.
I'm able to buf build with no issues also. Below is a configuration I used then switched to the other configuration lower down.
both of the configuration spit out the same details. Any help here would be great. Thank you.

FYI in the below information I removed company name and left with <company-name>

```
proto/src/main/proto/cloud/<company-name>/grpc/service/ads/admin/v1/ads_admin.proto:3:1:Files with package "cloud.<company-name>.grpc.service.ads.admin.v1" must be within a directory "cloud/<company-name>/grpc/service/ads/admin/v1" relative to root but were in directory "proto/src/main/proto/cloud/<company-name>/grpc/service/ads/admin/v1".
proto/src/main/proto/cloud/<company-name>/grpc/service/ads/admin/v1/ads_admin.proto:244:3:Enum zero value name "CHECKSUM_ALGORITHM_INVALID" should be suffixed with "_UNSPECIFIED".
proto/src/main/proto/cloud/<company-name>/grpc/service/ads/admin/v1/ads_admin.proto:358:9:Service name "AppDistributionAdmin" should be suffixed with "Service".
```

```
build:
  roots:
    - .
lint:
  use:
    - BASIC
    - FILE_LOWER_SNAKE_CASE
  except:
    - ENUM_NO_ALLOW_ALIAS
    - IMPORT_NO_PUBLIC
    - PACKAGE_DIRECTORY_MATCH
    - PACKAGE_SAME_DIRECTORY
    - PACKAGE_AFFINITY
breaking:
  use:
    - WIRE_JSON
  except:
    - SERVICE_NO_DELETE
    - FILE_NO_DELETE
    - MESSAGE_NO_DELETE
```

```
build:
  roots:
    - .
lint:
  use:
    - MINIMAL 
breaking:
  use:
    - WIRE_JSON
```

After running ```buf check ls-lint-checkers --config buf.yml``` I get the following error

```
config: could not unmarshal as JSON: invalid character 'b' looking for beginning of value
could not unmarshal as YAML: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `buf.yml` into bufconfig.ExternalConfig
```
