### ISSUE TITLE
Allow specifying a command line instead of just a path for plugins in `buf.gen.yaml`

### ISSUE THREAD

**Issue by espadolini** [bufbuild/buf#1557]
It would be neat if the `path` of a plugin could also include some arguments, so that it would be possible to do
```yaml
plugins:
  - name: go
    path: ["go", "run", "google.golang.org/protobuf/cmd/protoc-gen-go"]
    out: gen/proto
    opt: paths=source_relative
```

to always run the version of `protoc-gen-go` that matches the `google.golang.org/protobuf` in use (as specified by `go.mod`).
