### ISSUE TITLE
How to generate C# gRPC code from protos?

### ISSUE THREAD

**Issue by zhanjingjie** [bufbuild/buf#1568]
I'm trying to generate C# code from .proto files. So far I have only found the plugin to generate the messages code with the "csharp" plugin. And looks like there's no "csharp-grpc" plugin available. So what's the best way to generate gRPC code (server, client)?

Here's the current buf.gen.csharp.yaml.
`
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: XXXX
plugins:
  - name: csharp
    out: protos/gen/c#
`

**Comment by careless6666** [comment]
I'm not sure if this is a good way, but I do like this if I need to do it locally

`version: v1
plugins:
  - name: csharp
    out: gen/proto/csharp
    opt: base_namespace=
  - name: grpc_csharp_plugin
    out: gen/proto/csharp
    path: /Users/alex/.nuget/packages/grpc.tools/2.48.0/tools/macosx_x64/grpc_csharp_plugin
    
`

**Comment by pkwarren** [comment]
Here's an example using remote plugins:

```yaml
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/protocolbuffers/csharp
    out: protos/gen/c#
    opt: base_namespace=
  - plugin: buf.build/grpc/csharp
    out: protos/gen/c#
```

See https://buf.build/grpc/csharp and https://buf.build/protocolbuffers/csharp for more details.
