### ISSUE TITLE
buf breaking: google/api/annotations.proto: does not exist

### ISSUE THREAD

**Issue by happyalu** [bufbuild/buf#1570]
I'm using buf (1.9.0) with this layout:

```
.
├── buf.gen.yaml
├── proto
│   ├── buf.lock
│   ├── buf.yaml
│   └── dir/with/protofiles
```

```
❯ cat proto/buf.yaml
version: v1
deps:
  - buf.build/googleapis/googleapis
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
```

I can get other buf commands to work, but not `buf breaking`.
```
works: buf generate proto
works: buf build proto
works: buf build .git#branch=master,subdir=proto
works: buf lint .git#branch=master,subdir=proto
```

fails:
```
buf breaking --against .git#branch=master,subdir=proto
google/api/annotations.proto: does not exist
```

I'd prefer to use the buf modules rather than have googleapis in a workspace. What am I doing wrong?
