### ISSUE TITLE
Example generate usage with vendor files and gRPC-gateway

### ISSUE THREAD

**Issue by casimcdaniels** [bufbuild/buf#166]
Trying out buf.build and so far it's pretty neat! I had one issue that is unclear from documentation - how does one go about using the `generate` command with vendored files?

**Here's my attempt**

I'm trying to generate grpc-gateway + openapiv2 stubs. My project organization:

```
project
  - proto/
     - service/
       - v1/
         - service.proto
     - third_party/
         google/
```

My service.proto contains an import statement for `google/api/annotations.proto`. 

`buf.yaml`
```yaml
version: v1beta1
build:
  roots:
    - service
    - third_party
lint:
  use:
    - DEFAULT
  service_suffix: API
  ignore:
    - google
breaking:
  use:
    - WIRE_JSON
```

`buf.gen.yaml`
```yaml
version: v1beta1
plugins:
  - name: go
    out: gen

  - name: go-grpc
    out: gen

  # Here is the problem
  - name: grpc-gateway
    out: gen
```

Finally, I run `buf generate` in the `proto` directory and get the following
```bash
F1019 18:21:31.855751    9456 main.go:114] Cannot set flag 
F1019 18:21:31.857266    9457 main.go:114] Cannot set flag 
F1019 18:21:31.858238    9458 main.go:114] Cannot set flag 
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc00038b100, 0xc0000ca700, 0x3c, 0x40)
        /Users/.../vendor/github.com/golang/glog/glog.go:769 +0xb9

```

To match the protoc command, I set `paths=source_relative` in opts and got the following error:
```plugin grpc-gateway: inconsistent package names: code errdetails; inconsistent package names: annotations httpbody``` 

In addition, the third_party google files are being generated as well as if they are standalone protobufs, which I don't think is correct.
<br>

It seems to me that since the third_party is within the context, the buf generate command is trying to generate them, and because the vendor proto files output to different go packages within the same protobuf package, there is an inconsistency issue. I can't exclude the `third_party` from build in the yaml because then it's not longer importable.

At this point, I'm not sure I can use `buf generate` and have to fallback to using protoc instead, unless I'm missing something.
