### ISSUE TITLE
invalid memory address or nil pointer dereference when running buf mod update

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [bufbuild/buf#1673]
With `buf.yaml`:
```yaml
version: v1
name: github.com/private/foo
deps:
- buf.build/envoyproxy/envoy
breaking:
  use:
  - FILE
lint:
  use:
  - DEFAULT
```

Output is:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xac203e]

goroutine 23 [running]:
github.com/bufbuild/connect-go.(*connectUnaryClientConn).validateResponse(0xc0001cf300, 0xc0000be480)
        github.com/bufbuild/connect-go@v1.1.0/protocol_connect.go:423 +0xafe
github.com/bufbuild/connect-go.(*duplexHTTPCall).makeRequest(0xc00044b780)
        github.com/bufbuild/connect-go@v1.1.0/duplex_http_call.go:257 +0xcc
created by github.com/bufbuild/connect-go.(*duplexHTTPCall).ensureRequestMade.func1
        github.com/bufbuild/connect-go@v1.1.0/duplex_http_call.go:233 +0x5a
```
