### ISSUE TITLE
Cannot generate js code with option

### ISSUE THREAD

**Issue by XSAM** [bufbuild/buf#170]
`buf.gen.yaml` file:

```yaml
version: v1beta1

plugins:
  - name: js
    out: foo
    opt: import_style=commonjs,binary
```

I got this result:

```bash
$ buf generate
Unknown flag: --js_opt
plugin js: exit status 1
```
-----

Buf version: 0.28.0
Protoc version: 3.6.1
