### ISSUE TITLE
Linter does not recognize v0 as a valid version

### ISSUE THREAD

**Issue by easyCZ** [bufbuild/buf#172]
When running the linter on a file which is in the v0 directory, and sets the package name as `package public.clusters.v0`, the linter outputs 
```
api/proto/public/clusters/v0/clusters.proto:2:1:Package name "public.clusters.v0" should be suffixed with a correctly formed version, such as "public.clusters.v0.v1"
```

When the version is changed to v1, the linter ends up being happy again. In this case, I believe `v0` should be recognised as a valid version as it's often used in many APIs for the very first implementation.

Additional info for repro:
tree:
```
.
└── api/proto/public
    └── clusters
        └── v0
            └── clusters.proto
```
```proto
// api/proto/public/clusters/v0/clusters.proto

syntax = "proto3";
package public.clusters.v0;

/// ...
```

```yaml
# buf.yaml, in repo root
version: v1beta1
build:
  roots:
    - public
lint:
  use:
    - DEFAULT

```

```yaml
# buf.gen.yaml, in repo root
version: v1beta1

# The plugins to run.
plugins:
  - name: go
    out: api/gen/go


```
