### ISSUE TITLE
v1.11.0 managed bufgen fails when more than 10 plugins configured

### ISSUE THREAD

**Issue by yottta** [bufbuild/buf#1720]
Hi there,

**Buf version**: v1.11.0

**Description**
Considering the following `buf.gen.yaml`:
```
version: v1
managed:
  enabled: true
plugins:
  - remote: buf.build/protocolbuffers/plugins/go:v1.27.1-1
    out: gen/go
    opt: 
      - paths=source_relative
... (10 more plugins)
```

When running `buf generate` with v1.11.0, it fails with:
```
Failure: too many remote plugins in a single request: got 11, limit is 10
```
which is returned by [this](https://github.com/bufbuild/buf/blob/8cac1d5749a630d9b7c233821a795c399ba75780/private/buf/bufgen/generator.go#L343) call.

It looks it is related to #1661.
