### ISSUE TITLE
generating gRPC stubs for various languages

### ISSUE THREAD

**Issue by jon-whit** [bufbuild/buf#173]
I would like to use `buf generate` to also generate gRPC stubs for my gRPC service. Are there any examples on how to do this?

I tried something like this:

```
# buf.gen.yaml
version: v1beta1

plugins:
  - name: java
    out: genproto/java
    opt: --plugin=protoc-gen-grpc-java=genproto/java --grpc-java_out=genproto/java
```

but I get the error:
```
--java_out: eventhub/pubsub/v1alpha1/pubsub.proto: Unknown generator option: --plugin
plugin java: exit status 1
```

Is this currently supported, and if so are there some good examples you can point me to?

**Comment by johanbrandhorst** [comment]
Hi Jonathan, thanks for using buf! There's clearly been a misunderstanding around how to use the generation directives, let me guess what you probably wanted:
```yaml
version: v1beta1

plugins:
  - name: grpc-java
    out: genproto/java
    # I'm not sure about this one, but your `protoc-gen-grpc-java=genproto/java` implies that this is
    # the path to your java grpc generator. If that is wrong, this should be the path to your java grpc generator
    # binary.
    path: genproto/java
```

If you think the documentation at https://docs.buf.build/generate-usage/ can be improved, we'd love to have your feedback!

Closing as I think this is resolved, but let me know if you need more help, and feel free to drop by [our public Slack](https://join.slack.com/t/bufbuild/shared_invite/zt-f5k547ki-VDs_iC4TblNCu7ubhRD17w) if you want more synchronous assistance!
