### ISSUE TITLE
add support for "java lite" output

### ISSUE THREAD

**Issue by ZeeD** [bufbuild/buf#1780]
`protoc` support the generation of [java "lite"](https://github.com/protocolbuffers/protobuf/blob/main/java/lite.md) output.
my understanding is that is possible to do it prefixing `lite:` before the output dir.

but if I try to set `out: lite:..` in `buf.gen.yaml` the prefix is treated as a normal filename.

how can I tell `buf` to have the same behavior of `protoc --java_out=lite:...` ?

**Comment by bufdev** [comment]
Use options https://docs.buf.build/configuration/v1/buf-gen-yaml#opt

```yaml
# buf.gen.yaml
version: v1
plugins:
  - plugin: java
     out: ...
     opt: lite
```
