### ISSUE TITLE
How to use buf without changing directory structure?

### ISSUE THREAD

**Issue by kostyay** [bufbuild/buf#1782]
Hello
It appears that in order for buf to work properly it forces me to change my service directory structure having to put all my protos in a subdirectory with the service name as the root.

I've created a repository demonstrating the issue here: https://github.com/kostyay/buf-question

In that repo you will find 3 directories each representing a separate repository in my actual organizational project.
For the sake of simplicity I've put them in a signle GH repo to demonstrate the issue.
Each directory is a service with its own BSR repo.

Pet and Owner are both published to BSR.
I would like `buisness` to reference both pet and owner, however due to my current directory structure it is not possible.
https://github.com/kostyay/buf-question/blob/main/buisness/api/service.proto#L4-L5

Ultimately it would be great if I could somehow define a top level directory for dependencies in such way so they would be available via a sub directory
```yaml
version: v1
name: buf.build/kostyay/buisness
deps:
  - buf.build/kostyay/owners:
     as: owners
     
  - buf.build/kostyay/pets:
     as: pets
```

Then I could import
```proto3
import "pets/service.proto";
```

Thanks in advance.
