### ISSUE TITLE
invalid example config in docs

### ISSUE THREAD

**Issue by slimsag** [bufbuild/buf#179]
(I would've sent a PR but couldn't find if your docsite is OSS anywhere)

https://docs.buf.build/tour-6 says to use this config:

```
plugins:
  - name: java
    out: java
  - name: cpp
    out: cpp
```

But it is missing the version specifier:

```
$ buf generate
buf.gen.yaml has no version set. Please add "version: v1beta1"
```
