### ISSUE TITLE
Feature Request: support globbing in ignore paths

### ISSUE THREAD

**Issue by sgtsquiggs** [bufbuild/buf#182]
We have a mix of old protobuf and new protobuf - all new code is adhering to a higher linting standard. We have an easily globbed pattern to tell if the code is new/old so it would be helpful if ignore paths in buf.yaml supported globbing.

**Comment by bufdev** [comment]
We'd strongly prefer not to allow globbing, both as it trends dangerously close to regexes, and because it encourages a pattern we want everyone to move away from. Globbing means you want to ignore individual files in a directory, and we think that files within a given directory should all be treated the same - one package per directory, one directory per package, all files should assume to be commonly built. While linting is a bit orthogonal here, it does discourage this principle.

That's not a "no", but to see if we can work around it, have you tried `buf check lint --error-format=config-ignore-yaml`? This will produce output that you can copy/paste into your buf.yaml to ignore current issues on a per-file basis. For example (partial result):

```yaml
version: v1beta1
lint:
  ignore_only:
    ENUM_NO_ALLOW_ALIAS:
      - google/appengine/v1/app_yaml.proto
      - google/appengine/v1beta/app_yaml.proto
      - google/cloud/recommendationengine/v1beta1/catalog.proto
      - google/cloud/websecurityscanner/v1/scan_config_error.proto
      - google/cloud/websecurityscanner/v1beta/scan_config_error.proto
      - google/storage/v1/storage.proto
    ENUM_VALUE_PREFIX:
      - google/ads/admob/v1/admob_resources.proto
      - google/ads/googleads/v2/enums/access_reason.proto
      - google/ads/googleads/v2/enums/access_role.proto
      - google/ads/googleads/v2/enums/account_budget_proposal_status.proto
      - google/ads/googleads/v2/enums/account_budget_proposal_type.proto
      - google/ads/googleads/v2/enums/account_budget_status.proto
      - google/ads/googleads/v2/enums/ad_customizer_placeholder_field.proto
      - google/ads/googleads/v2/enums/ad_group_ad_rotation_mode.proto
      - google/ads/googleads/v2/enums/ad_group_ad_status.proto
      - google/ads/googleads/v2/enums/ad_group_criterion_approval_status.proto
      - google/ads/googleads/v2/enums/ad_group_criterion_status.proto
      - google/ads/googleads/v2/enums/ad_group_status.proto
      - google/ads/googleads/v2/enums/ad_group_type.proto
      - google/ads/googleads/v2/enums/ad_network_type.proto
      - google/ads/googleads/v2/enums/ad_serving_optimization_status.proto
      - google/ads/googleads/v2/enums/ad_strength.proto
      - google/ads/googleads/v2/enums/ad_type.proto
      - google/ads/googleads/v2/enums/advertising_channel_sub_type.proto
      - google/ads/googleads/v2/enums/advertising_channel_type.proto
      - google/ads/googleads/v2/enums/affiliate_location_feed_relationship_type.proto
      - google/ads/googleads/v2/enums/affiliate_location_placeholder_field.proto
      - google/ads/googleads/v2/enums/age_range_type.proto
      - google/ads/googleads/v2/enums/app_campaign_app_store.proto
      - google/ads/googleads/v2/enums/app_campaign_bidding_strategy_goal_type.proto
      - google/ads/googleads/v2/enums/app_payment_model_type.proto
      - google/ads/googleads/v2/enums/app_placeholder_field.proto
      - google/ads/googleads/v2/enums/app_store.proto
      - google/ads/googleads/v2/enums/app_url_operating_system_type.proto
      - google/ads/googleads/v2/enums/asset_field_type.proto
      - google/ads/googleads/v2/enums/asset_performance_label.proto
      - google/ads/googleads/v2/enums/asset_type.proto
      - google/ads/googleads/v2/enums/attribution_model.proto
      - google/ads/googleads/v2/enums/bid_modifier_source.proto
      - google/ads/googleads/v2/enums/bidding_source.proto
      - google/ads/googleads/v2/enums/bidding_strategy_status.proto
      - google/ads/googleads/v2/enums/bidding_strategy_type.proto
      - google/ads/googleads/v2/enums/billing_setup_status.proto
      - google/ads/googleads/v2/enums/brand_safety_suitability.proto
      - google/ads/googleads/v2/enums/budget_delivery_method.proto
```

This would allow you to ignore existing issues, while continuing to develop new files with your new standards.
