### ISSUE TITLE
code generated by swift plugin using googleapis/type/date fails with `Cannot find type Google_Type_Date in scope`

### ISSUE THREAD

**Issue by majelbstoat** [bufbuild/buf#1826]
I have a proto message that uses [google/type/date.proto](https://github.com/googleapis/googleapis/blob/master/google/type/date.proto), which is not a well-known type:

```proto
message GenerateSitemapRequest {
  string time_zone  = 1;
  google.type.Date from_date = 2;
  google.type.Date until_date = 3;
}
```

Using the following generate yaml file:

```yaml
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/grpc/swift
    out: ../swift/src
  - plugin: buf.build/apple/swift
    out: ../swift/src
```

The protos compile correctly, but when I come to build the project, I get compilation errors like `Cannot find type 'Google_Type_Date' in scope`. Indeed, in the generated code, there is no additional import, and they are not part of SwiftProtobuf like the google well known types.

The same proto compiles properly for Go with buf, and has the expected import:

```go
import (
	date "google.golang.org/genproto/googleapis/type/date"
)
```

Is there a particular Swift package I need to add? Or some other way that I need to configure the swift code generation?
