### ISSUE TITLE
directory is not ignored if build root is "."

### ISSUE THREAD

**Issue by maskimko** [bufbuild/buf#183]
Hi!

I noticed that when build root is a dot "."  

```yaml
version: v1beta1
build:
  roots:
    - .
  excludes:
lint:
  ignore:
    - third_party
```

"lint.ignore" section is not respected by buf, but when there is a particular directory specified as a build root, everyting works

```yaml
version: v1beta1
build:
  roots:
    - proto
    - third_party/googleapis
  excludes:
lint:
  ignore:
    - third_party/googleapis/google/api
    - third_party/googleapis/google/protobuf
    - third_party/googleapis/google/rpc
```

Due to a specifics of the project I need to exactly 1ts configuration because there is a bazel WORKSPACE file, and all proto_library deps are related to it. 
Please help me to understand how I can overcome this issue :)

**Comment by bufdev** [comment]
Please see the documentation.

https://docs.buf.build/lint-configuration#ignore

> This allows directories or files to be excluded from all lint checkers when running buf check lint. The specified directory or file paths should be relative to their root. For example, given a root proto, and a file proto/bar/baz.proto, the following will result in proto/bar/baz.proto being ignored:

```
version: v1beta1
build:
  roots:
    - proto
lint:
  ignore:
    - bar/baz.proto
```
