### ISSUE TITLE
Compiling to Java using the provided docker image

### ISSUE THREAD

**Issue by MatanRubin** [bufbuild/buf#184]
Hi, thanks for Buf, it's really awesome!
When trying to compile proto files to Java using Buf's docker image, I get the following message:

> plugin java: exec: "protoc": executable file not found in $PATH

I'm assuming this is because the docker image does not have protoc installed. Any workaround or solution for this?

Some context: I'm trying to use Buf in a gitlab pipeline to lint and then compile my proto files to java. This is how my relevant gitlab step looks:

```
protobuf:
  image:
    name: bufbuild/buf:0.30.0
    # The entrypoint for Buf's docker image is buf itself, which gitlab doesn't
    # like. Override it so that we get a shell.
    # See https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2692
    entrypoint: [""]
  stage: protobuf
  script:
    - buf check lint  # <---- This works great
    - buf generate -o gen  # <---- This step fails with the message I pasted above
  artifacts:
    paths:
      - gen
```
