### ISSUE TITLE
buf generate - .proto not exists

### ISSUE THREAD

**Issue by kuchaguangjie** [bufbuild/buf#1911]
When I run `buf generate`, get error:
> proto/auth_service.proto:5:8:user.proto: does not exist

`buf.gen.yaml`:
```
version: v1
plugins:
  - name: go
    out: gen/go
    opt:
      - paths=source_relative
  - name: go-grpc
    out: gen/go
    opt:
      - paths=source_relative
  - name: grpc-gateway
    out: gen/go
    opt:
      - paths=source_relative
      - generate_unbound_methods=true
  - name: openapiv2
    out: swagger-ui/gen/openapiv2/
```

The proto files are in `proto/`, there are only 2 file, 1 file import the other via:
> import "user.proto";

So, how to fix this ?

**Comment by kuchaguangjie** [comment]
After adding `buf.work.yaml`:
```
version: v1
directories:
  - proto
```

now it works.

**Comment by kuchaguangjie** [comment]
But when I try to deps in `buf.yaml`:
```
version: v1
name: buf.build/kuchaguangjie/grpc
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
```

`buf generate` can't find proto files of the `deps`:
> proto/service.proto:4:8:proto/google/api/annotations.proto: does not exist

So, how to fix this?
