### ISSUE TITLE
buf.gen.yaml `path` does not work with absolute path when using `#!/bin/env bash`

### ISSUE THREAD

**Issue by joshcarp** [bufbuild/buf#1975]
Steps to reproduce:

/absolute/path/to/protoc-gen-foobar.sh:
```bash
#!/bin/env bash
```

buf.gen.yaml:
```yaml
version: v1
plugins:
  - plugin: foobar
    out: gen/proto/foobar
    path: ["/absolute/path/to/protoc-gen-foobar.sh"]
```

gives the error:

```
$ buf generate
Failure: plugin debug: fork/exec /absolute/path/to/protoc-gen-foobar.sh: no such file or directory
```

However when I change the `/absolute/path/to/protoc-gen-foobar.sh` to 
```bash
#!/bin/bash 
```
or change `buf.gen.yaml` to
```yaml
version: v1
plugins:
  - plugin: foobar
    out: gen/proto/foobar
    path: ["sh", "-e", "/absolute/path/to/protoc-gen-foobar.sh"]
```
It works fine

**Comment by bufdev** [comment]
Note that absolute paths do not affect this, this also fails with "no such file or directory":

```yaml
version: v1
plugins:
  - plugin: foobar
    out: foobar
    path: "./protoc-gen-foobar.sh"

```
