### ISSUE TITLE
Unable to get FIELD_NO_DELETE_UNLESS_NUMBER_RESERVED and FIELD_NO_DELETE_UNLESS_NAME_RESERVED to work

### ISSUE THREAD

**Issue by noel-yap** [bufbuild/buf#2043]
`buf.yaml`:
```
version: v1
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
    - FIELD_NO_DELETE_UNLESS_NUMBER_RESERVED
    - FIELD_NO_DELETE_UNLESS_NAME_RESERVED
```

I've also tried placing `FIELD_NO_DELETE_*` in an `except:` section.

Are there any examples of how to use these?

**Comment by noel-yap** [comment]
The following works:
```
version: v1
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FIELD_NO_DELETE_UNLESS_NUMBER_RESERVED
    - FIELD_NO_DELETE_UNLESS_NAME_RESERVED
```

Is there a way to get the other default `FILE` settings?

**Comment by bufdev** [comment]
If you can give us a specific, reproducible example (with reproduction steps) of what is not working, we're happy to help out!

**Comment by noel-yap** [comment]
proto has:
```
message SpecimenInfo {
  reserved 3;
  reserved "tube_count";
}
```

It used to be:
```
message SpecimenInfo {
  optional int32 tube_count = 3;
}
```

With `buf.yaml`:
```
version: v1
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
    - FIELD_NO_DELETE_UNLESS_NUMBER_RESERVED
    - FIELD_NO_DELETE_UNLESS_NAME_RESERVED
```

We get the following error:
```
ERROR: order-manager/proto/v1/common.proto:203:1:Previously present field "3" with name "tube_count" on message "SpecimenInfo" was deleted.
ERROR: order-manager/proto/v1/common.proto:203:1:Previously present oneof "_tube_count" on message "SpecimenInfo" was deleted.
```

If I remove `- FILE` from `buf.yaml`, things work fine but that remove a bunch of rules that we would like to keep. Is the only solution to enumerate all the rules (except `FIELD_NO_DELETE`) that are included in `FILE`?

**Comment by bufdev** [comment]
You need to exclude `FIELD_NO_DELETE`:

```yaml
version: v1
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
    - FIELD_NO_DELETE_UNLESS_NUMBER_RESERVED
    - FIELD_NO_DELETE_UNLESS_NAME_RESERVED
  except:
    - FIELD_NO_DELETE
```
