### ISSUE TITLE
Congratulations and question

### ISSUE THREAD

**Issue by frederikhors** [bufbuild/buf#2045]
Hi all! Congratulations for this project I just found out! It's amazing!

I'm using `"@bufbuild/buf": "1.15.0-1"` in my `package.json`.

I created `buf.gen.yaml`:

```yaml
version: v1

plugins:
  - plugin: es
    out: gen
    opt: target=ts

  - plugin: connect-es
    out: gen
    opt: target=ts
```

and I'm generating using: `npx buf generate ../player/protos`.

It works. Good!

But I need to generate for many other .proto directories.

Is there a way to use `buf.gen.yaml` file to indicate those directories?
