### ISSUE TITLE
Can't find how to specify the import root for buf generate

### ISSUE THREAD

**Issue by leandregagnonlewis** [bufbuild/buf#2068]
I am tryinng to use buf generate, but have a problem when trying to change the root (for resolving imports). My file structure is the following:

```
- my-repo
  - protobufs-submodudle
    -protos
      - buf.yaml 
      - backend
        - queries.proto
        - ...
      - utils
        - datetime.proto
  - package.json
  - src
  - buf.gen.yaml
  - ...
```

- In `queries.proto` I need to import `datetime.proto`.
- I run buf generate from `my-repo` root. 
- Currently, I made the import work by having `import "protobufs-submodudle/protos/utils/datetime.proto";` in `queries.proto`. 
- I want the import root to be `my-repo/protos` so that the import would be  `import "utils/datetime.proto";`
- As per the doc, I tried adding a `buf.yaml` file in the `protobufs-submodudle/protos` to indicate the root, but the import is still failing.
- The exact command I run is `buf generate --path protobufs-submodudle/protos/backend/queries.proto --include-imports --config protobufs-submodudle/protos/buf.yaml"`

Content of `buf.gen.yaml`:
```
# buf.gen.yaml defines a local generation template.
# For details, see https://docs.buf.build/configuration/v1/buf-gen-yaml
# Based on code in the repo README
# For details, see https://github.com/bufbuild/connect-web/tree/main/packages/protoc-gen-connect-web#generating-code
version: v1
plugins:
  # This will invoke protoc-gen-es and write output to src/gen
  - name: es
    out: src/api/generated
    opt: 
      - target=ts
      - import_extension=.ts
  # This will invoke protoc-gen-connect-es
  - name: connect-es
    out: src/api/generated
    opt: 
      - target=ts
      - import_extension=.ts
```

Content of `buf.yaml`
```
version: v1
```

Can you help with this ? Thanks!
