### ISSUE TITLE
buf grpc/web generate error:  options: mode is required

### ISSUE THREAD

**Issue by ihatemodels** [bufbuild/buf#2087]
I am trying to setup a grpc/web client and i get the following error: 

```bash
Failure: plugin "buf.build/grpc/web:v1.4.2" failed: health.proto: options: mode is required
````

The error specifically occurs when using gRPC-Web, while other plugins do not seem to be affected. This issue has been reported here: https://github.com/grpc/grpc-web/issues/1251

## Buf version 

```bash
➜  buf --version
1.17.0
```

## heath.proto

```proto
syntax = 'proto3';

package health_proto.v1;

option csharp_namespace = "Grpc.Health.V1";
option go_package = "google.golang.org/grpc/health/grpc_health_v1";
option java_multiple_files = true;
option java_outer_classname = "HealthProto";
option java_package = "io.grpc.health.v1";

// Copyright 2015 The gRPC Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
message HealthCheckRequest {
  string service = 1;
}

message HealthCheckResponse {
  enum ServingStatus {
    UNKNOWN = 0;
    SERVING = 1;
    NOT_SERVING = 2;
    SERVICE_UNKNOWN = 3;  // Used only by the Watch method.
  }
  ServingStatus status = 1;
}

service Health {
  rpc Check(HealthCheckRequest) returns (HealthCheckResponse);
  rpc Watch(HealthCheckRequest) returns (stream HealthCheckResponse);
}
````

## buf.gen.yaml

```yaml
version: v1
plugins:
  - plugin: buf.build/grpc/web:v1.4.2
    out: gen/web
  # dependencies
  - plugin: buf.build/protocolbuffers/js
    out: gen/web

  # Documentation
  - name: doc
    out: gen/doc
    opt: html,index.html
    strategy: all
```

## buf.yaml

```yaml
version: v1
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
 ```
