### ISSUE TITLE
Dependencies from custom remote 

### ISSUE THREAD

**Issue by MUlt1mate** [bufbuild/buf#2120]
Greetings. I have proto file that imports file from local gitlab instance: `import "mygitlab.com/dev/rpc/queue.proto";`
I failed to use buf generation with that dependecy.
my buf.yaml
```yaml
version: v1
name: "mygitlab.com/common/payments"
deps:
  - "mygitlab.com/dev/rpc"

```
buf.gen.yaml
```yaml
version: v1
plugins:
  - plugin: go
    out: .
    opt:
      - paths=source_relative
      - I=./vendor
      - I=.
```

Command output
```
buf generate
WARN    Specified deps are not covered in your buf.lock, run "buf mod update":
        - mygitlab.com/dev/rpc
payment.proto:6:8:mygitlab.com/dev/rpc/queue.proto: does not exist
```

```
buf mod update
Failure: the server hosted at that remote is unavailable.
```
buf version 1.19.0

The generation works fine with `protoc -I=. -I=./vendor --go_out=paths=source_relative:.  payment.proto`

Is it possible to use custom remote for generation? Didn't find any information in docs.
