### ISSUE TITLE
How to use this tool with grpc python

### ISSUE THREAD

**Issue by wiznancial** [bufbuild/buf#223]
I was wondering how you would use this tool with grpc-python

I have build the plugin from source but keep getting the error

plugin grpc_python_plugin: could not find protoc plugin for name grpc_python_plugin

**Comment by bufdev** [comment]
Without more information to reproduce, we can't help you. In general though, you need to provide the `path` to `grpc_python_plugin`:

```yaml
version: v1beta1
plugins:
  - name: grpc-python
    path: /path/to/grpc_python_plugin
```

Alternatively, you can just specify `grpc_python_plugin` as the value for `path`, and `grpc_python_plugin` must be on your $PATH.

https://docs.buf.build/generate-usage
https://github.com/grpc/grpc/issues/15675

**Comment by JoshuaPostel** [comment]
@bufdev  Do you have any suggestions for building `grpc_python_plugin` beyond that in [grpc/grpc#15675](https://github.com/grpc/grpc/issues/15675)?

After struggling to build the `grpc_python_plugin` from source, I saw you comment on issues regarding prebuilt grpc_*_plugin binaries.  I fully understand this is an issue on grpc's end, just thought I would ask in case there is a recommended way to integrate `buf` and python grpc.

**Comment by wakanapo** [comment]
I'm struggling to get grpc_python_plugin binary on OSX too.

For Ubuntu/Debian, I found the easy way. 
We can get `grpc_python_plugin` binary via apt.
```
apt install protobuf-compiler-grpc
```
And then the following works.
```
version: v1beta1
plugins:
  - name: python-grpc
    path: grpc_python_plugin
```

**Comment by wakanapo** [comment]
We seem to have no way to build grpc_python_plugin from source of the latest version. https://github.com/grpc/grpc/issues/26125
So, we need to use the old version.

And I found one hacky way to get grpc_python_plugin binary. It's not the latest version, though.
Pants, which is build system, provides the grpc_python_plugin binary to use in the build system. [ref](https://www.pantsbuild.org/docs/reference-grpc_python_plugin)
For example, we can get the binary for mac like this.
```
wget https://binaries.pantsbuild.org/bin/grpc\_python\_plugin/1.32.0/macos/x86\_64/grpc\_python\_plugin
```

**Comment by ZymoticB** [comment]
The following is a workable solution, but you'll likely want to customize it to your own environment.

grpc/grpc deprecated their makefile, they only support CMake and bazel now. This dockerfile will build all plugins and then copy the grpc_python_plugin into a smaller container.
```
FROM debian:buster as builder

RUN apt-get update
RUN apt-get install -y git cmake build-essential

WORKDIR /build
RUN git clone https://github.com/grpc/grpc --recursive
WORKDIR /build/grpc
RUN cmake .
RUN cmake --build . --target plugins

FROM debian:buster-slim
WORKDIR /workdir
COPY --from=builder /build/grpc/grpc_python_plugin /workdir

CMD /workdir/grpc_python_plugin
```
As noted by @bufdev buf expects the plugin to be an executable on your PATH or specified by a path in the `buf.gen.yaml`. You can use a small shell script to redirect to a docker container like (with some assumptions about how you tagged the docker build).
```
$ cat protoc-gen-grpc_python_plugin
#!/bin/bash
exec docker run -i --rm grpc_python_plugin
```
The rest of the work is ensuring that shell script is on your path, or configured in your `buf.gen.yaml` as well as any further configuration of the plugin you require which is documented [here](https://docs.buf.build/generate-usage/)

**Comment by JoshuaPostel** [comment]
Thanks for the replies!  Both approaches worked for me:
@wakanapo's is nice for quickly getting the binary
@ZymoticB's is nice for building specific versions (which support being built with `cmake`)

**Comment by johanbrandhorst** [comment]
We recently released support for remote plugins, so you can generate Python code with the following (no other tooling than `buf` needed!):

```yaml
version: v1
plugins:
  - remote: buf.build/protocolbuffers/plugins/python:v3.19.1-1
    out: ./gen/python
  - remote: https://buf.build/grpc/plugins/python:v1.41.1-1
    out: ./gen/python
```

**Comment by avinash-fam** [comment]
Adding `pyi_out` option will generate `.pyi` files too.

```
version: v1

managed:
  enabled: true

plugins:
  - plugin: buf.build/grpc/python:v1.56.2
    out: gen/py/

  # dependencies
  - plugin: buf.build/protocolbuffers/python
    out: gen/py/
    opt: pyi_out    # generates .pyi files too
```
