### ISSUE TITLE
kratos error proto gen problem

### ISSUE THREAD

**Issue by urionz** [bufbuild/buf#2267]
### error proto path `****/api/v1/error.proto`

```proto
syntax = "proto3";

package api.v1;

import "errors/errors.proto";

enum ErrorReason {
  option (errors.default_code) = 500;

  UNKNOWN_ERROR = 0;
  UNAUTHORIZED = 1 [(errors.code) = 401];
  BAD_REQUEST = 2 [(errors.code) = 400];
  FORBIDDEN = 3 [(errors.code) = 403];
}
```

### buf mod config path：****/buf.yaml
```yaml
version: v1
deps:
  - buf.build/googleapis/googleapis
  - buf.build/kratos-go/kratos
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/bufbuild/protovalidate

breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
  except:
    - RPC_REQUEST_STANDARD_NAME
    - RPC_REQUEST_RESPONSE_UNIQUE
    - RPC_RESPONSE_STANDARD_NAME
    - ENUM_VALUE_PREFIX
    - ENUM_ZERO_VALUE_SUFFIX
  allow_comment_ignores: true
```

### buf gen config path：****/buf.gen.yaml
```yaml
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: ****/v1
    except:
      - buf.build/googleapis/googleapis
      - buf.build/grpc-ecosystem/grpc-gateway
      - buf.build/bufbuild/protovalidate

plugins:
  - plugin: buf.build/protocolbuffers/go:v1.30.1
    out: .
    opt: paths=source_relative
  - plugin: buf.build/grpc/go:v1.3.0
    out: .
    opt: paths=source_relative ## go install github.com/go-kratos/kratos/cmd/protoc-gen-go-http
  - name: go-http
    out: .
    opt: paths=source_relative
  - name: go-errors ## go install github.com/go-kratos/kratos/cmd/protoc-gen-go-errors
    out: .
    opt: paths=source_relative
```

### gen get result: ****/api/v1/error.pb.go
```go
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: api/v1/error.proto

package apiv1

import (
	_ "****/api/errors" // except： _ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)
```

### **expect：error.pb.go gen result**

```go
import _ "github.com/go-kratos/kratos/v2/errors" 
```

**Comment by oliversun9** [comment]
Hi there, if you want to import the Go code generated from [this Protobuf file](https://buf.build/kratos-go/kratos/file/main:errors/errors.proto) with `"github.com/go-kratos/kratos/v2/errors"` as your import path, as defined on [this line](https://buf.build/kratos-go/kratos/file/main:errors/errors.proto#L7), you can add module [`buf.build/kratos-go/kratos`](http://buf.build/kratos-go/kratos) to `go_package_prefix`'s `except`. This tells managed mode to skip this module when applying `go_package_prefix`. Your `buf.gen.yaml` will look like:

```yaml
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: abcd/v1
    except:
      - buf.build/googleapis/googleapis
      - buf.build/grpc-ecosystem/grpc-gateway
      - buf.build/bufbuild/protovalidate
      - buf.build/kratos-go/kratos # added this line to skip go_package_prefix for this module

plugins:
  - plugin: buf.build/protocolbuffers/go:v1.31.0 # 1.31.0 is the latest version
    out: .
    opt: paths=source_relative
  - plugin: buf.build/grpc/go:v1.3.0
    out: .
    opt: paths=source_relative
  - name: go-http ## go install github.com/go-kratos/kratos/cmd/protoc-gen-go-http
    out: .
    opt: paths=source_relative
  - name: go-errors ## go install github.com/go-kratos/kratos/cmd/protoc-gen-go-errors
    out: .
    opt: paths=source_relative
```

This fixes it on my machine. Let me know if that helps!
