### ISSUE TITLE
Add support for "regex" for excludes config instead of needing explicit directories

### ISSUE THREAD

**Issue by AlexeiZenin** [bufbuild/buf#233]
There is a case where our repository includes certain Protobuf definitions in test folders (Maven is used to generate the Protobuf classes along with some pre-packaged utility code all within the same repo). These test definitions are for testing only thus should not be added as part of linting or breaking change detection. Currently the excludes config only takes explicit folder paths which is cumbersome when you have dozens or hundreds of source folders.

Current `buf.yaml`:
```yaml
build:
  excludes:
    - services/A/src
    - services/B/src
    - services/C/src
```

Proposed `buf.yaml`:
```yaml
build:
  excludes:
    - **/src/
```

The above is basically some regex to capture all folders that have a src directory and excludes them. It is a rough example, could be regex or ant style and so on (not critical for me).
