### ISSUE TITLE
Resolve import path for vendored protos 

### ISSUE THREAD

**Issue by sdzharkov** [bufbuild/buf#2346]
Hi team, in our current monorepo we vendor in the `googleapis` protos. Our protos import `googleapis` via the import path `import "google/protobuf/timestamp.proto";`.

I'm interested in building a Buf image for the monorepo. However, I keep seeing the following issue when doing so:
```bash
buf build . --debug -v --exclude-path third_party --disable-symlinks
...
service.proto:2:8:google/api/annotations.proto: does not exist
```

Note that - **we do not want to rely on a dependency from the Buf Schema Registry** due to network isolation concerns. I'm aware that including the dependency `buf.build/googleapis/googleapis` does work. 

Is there a way to resolve the import in the `buf.yaml` file or a `buf.gen.yaml` file?  Thank you in advance!

I've also attempted to have the annotation protos resolve in the `buf.gen.yaml` file, but I'm certain this is incorrect
```
version: v1
plugins:
  - plugin: protoc-gen-validate
    out: gen/proto/go
    opt: paths:bazel-bin/external/com_github_envoyproxy_protoc_gen_validate/cmd/protoc-gen-validate-go/protoc-gen-validate-go_/protoc-gen-validate-go
  - plugin: buf.build/googleapis/googleapis
    out: gen/proto/go
    opt: paths:bazel-bin/external/go_googleapis/google/api/annotations_proto-descriptor-set.proto.bin
```
