### ISSUE TITLE
Buf breaking fails due to googleapis

### ISSUE THREAD

**Issue by adrianlungu** [bufbuild/buf#2378]
Hello,

I've tried configuring the buf.yaml, calling `buf mod clean-cache`, deleting the `buf.lock` file or even recreating the `buf.yaml` from 0 but everytime I run the following

```
buf breaking --against '.git#branch=main'
```

I get 

```
Failure: buf.build/googleapis/googleapis:1068d85d09894f7587a3236f489c0d80: does not exist
```

Running on the latest version of `buf`: 

```
buf --version
1.26.1
```

Any help would be greatly appreciated

**Comment by smallsamantha** [comment]
Hey @adrianlungu - could you try `buf mod update`? I'm wondering if you're running into this [googleapis failure](https://buf.build/docs/reference/troubleshooting#googleapis-failure). Let me know if you continue to have issues

**Comment by adrianlungu** [comment]
Hello @smallsamantha - tried both `buf mod update` as well as `buf mod prune` but it did not change the outcome.

**Comment by smallsamantha** [comment]
It looks like [1068d85d09894f7587a3236f489c0d80](https://buf.build/googleapis/googleapis/docs/1068d85d09894f7587a3236f489c0d80
) is not a [BSR commit identifier or a tag reference](https://buf.build/docs/bsr/module/manage#referencing-a-module). The [dep](https://buf.build/docs/configuration/v1/buf-yaml#deps) on googleapis in your buf.yaml seems to be referencing a commit that doesn't exist - could you share your buf.yaml so we can see how you're pinning to this commit?

**Comment by adrianlungu** [comment]
buf.yaml

```
version: v1
deps:
  - buf.build/grpc-ecosystem/grpc-gateway
build:
  excludes: []
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
```

buf.lock

```
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: 711e289f6a384c4caeebaff7c6931ade
    digest: shake256:e08fb55dad7469f69df00304eed31427d2d1576e9aab31e6bf86642688e04caaf0372f15fe6974cf79432779a635b3ea401ca69c943976dc42749524e4c25d94
  - remote: buf.build
    owner: grpc-ecosystem
    repository: grpc-gateway
    commit: fed2dcdcfd694403ad51cd3c94957830
    digest: shake256:ed076a21e3d772892fc465ced0e4dd50f9dba86fdd4473920eaa25efa4807644e8e021be423dcfcee74bf4242e7e57422393f9b1abb10acb18ea1a5df509bb19
```

**Comment by smallsamantha** [comment]
Thanks for the info @adrianlungu. Your buf.lock does indicate that you're relying on the [latest googleapis commit](https://buf.build/googleapis/googleapis/docs/711e289f6a384c4caeebaff7c6931ade). You're running buf breaking against the main branch of your git repository - are you able to share the buf.yaml that is on the main branch?

**Comment by adrianlungu** [comment]
The one in `main` does seem to be pretty old, and an earlier version of `main` did indeed seem to have the tag reference that's throwing the error:

```
version: v1beta1
deps:
  - buf.build/googleapis/googleapis
  - buf.build/envoyproxy/protoc-gen-validate
  - buf.build/grpc-ecosystem/grpc-gateway
build:
  roots:
    - protobuf
    - github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
```

I've fetched and pulled `main` locally, and now I'm getting:

```
<input>:1:1:Previously present file "service/v1/service.proto" was deleted.
```

Not sure if the previous error is gone or superseded by this one 🤔
