### ISSUE TITLE
Cryptic bufgen.ExternalPluginConfigV1 error on 'buf generate'

### ISSUE THREAD

**Issue by iisharankov** [bufbuild/buf#2493]
I'm trying to get `buf generate` to work on the following two files

#### `buf.gen.yaml`
```
version: v1
plugins:
  - plugin: go
    out: ../api
    opt:
      - paths=source_relative
  - plugin: go-grpc
    out: ../api
    opt:
      - paths=source_relative
```

#### `buf.yaml`
```
version: v1
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
```

with 
```
$ buf --version
0.56.0

$ go version
go version go1.21.3 linux/amd64
```

I've tried everything and get the following errors every time.
```
$ buf -v generate
Failure: could not unmarshal as YAML: yaml: unmarshal errors:
  line 3: field plugin not found in type bufgen.ExternalPluginConfigV1
  line 7: field plugin not found in type bufgen.ExternalPluginConfigV1.
```
I've 

1.  Searched for this error and it exists nowhere. The closest is #307, but that references `build` and `deps`, not `plugin`, and also I've clearly isolated the two files as per [tutorials](https://grpc-ecosystem.github.io/grpc-gateway/docs/tutorials/generating_stubs/using_buf/).
2. Tried `buf lint`, with no warnings
3. Tried appending `protoc-gen-` to the plugins suggested [here](https://buf.build/docs/configuration/v1/buf-gen-yaml#plugin)
4. Tried remote plugins given [here](https://buf.build/docs/generate/remote-plugins) and [here](https://buf.build/blog/remote-packages-remote-plugins-approaching-v1)
5. Installed the protocal buffers plugin [here](https://buf.build/blog/remote-packages-remote-plugins-approaching-v1)

Strangely, absolutely all tries have given the same exact error, suggesting to me the error isn't actually in the plugin? I doubt it applies, but this is with Windows on WSL.
