### ISSUE TITLE
Can't find imports in imports that added by `--path` in one level

### ISSUE THREAD

**Issue by d-enk** [bufbuild/buf#2506]
Files:
```yml
vendor:
  dep1:
    1.proto # import 2
  dep2:
    2.proto
proto:
  0.proto # import 1, 2
```

`buf lint` Correctly return error:
`proto/0.proto:5:8:dep1/1.proto: does not exist`

`buf build --path vendor/`
Correctly find all deps 1, 2 for 0

But can't find 2 for 1
`vendor/dep1/1.proto:5:8:dep2/2.proto: does not exist`

Looking like trying using `--path vendor/`
from location `dep1`
without context `../`

I know how this can be solved using `buf.work.yaml`
But this just seems like a bug that can be easily fixed.

[proto.zip](https://github.com/bufbuild/buf/files/13024941/proto.zip)
