### ISSUE TITLE
Generate google.api.* dependencies for csharp

### ISSUE THREAD

**Issue by gigi** [bufbuild/buf#2623]
Hi!

I'm trying to generate *.cs files for C# using these plugins https://buf.build/grpc/csharp

```proto
syntax = "proto3";

package test.demo.v1;

import "google/api/annotations.proto";
...
```
I've added `buf.build/googleapis/googleapis` as dependencies:
```yaml
version: v1
deps:
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/googleapis/googleapis
 ...
```
This generates proper models but they rely on  `Google.Api.AnnotationsReflection` which is absent in output folder
```cs
new pbr::FileDescriptor[] { global::******Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, },
```

To generate `Annotations.cs` I have to put deps by hand to `proto/google/api/annotations.proto` and remove buf.lock. 

Is it a way to generate dependencies for C# too using buf's dependecies?

Thank you
