### ISSUE TITLE
Adding files to be ignored option for buf format to buf.yaml

### ISSUE THREAD

**Issue by Yusufss4** [bufbuild/buf#2632]
Hello this is our file structure,

```
├── README.md
├── buf.yaml
├── google
│   └── protobuf
│       ├── any.proto
│       ├── duration.proto
│       └── timestamp.proto
└── locy
    ├── borda_packet
    │   └── v2
    │       └── borda_packet.proto
.... other proto files.
```

And here is our buf.yaml file,

```
version: v1
breaking:
  use:
    - FILE
  ignore:
    - google/protobuf/*.proto
lint:
  use:
    - DEFAULT
  ignore:
    - google/protobuf/*.proto
```

In the top directory we are running `buf lint` and it ignores the files in the google. But when we run the `buf format` it does not ignore the files in the google dir. How can we add options for the `buf format`?

I could not find anything related to buf format in the given [docs](https://buf.build/docs/configuration/v1/buf-yaml). 

Thanks.
