### ISSUE TITLE
PROTOVALIDATE cannot be selected inside lint use

### ISSUE THREAD

**Issue by Arnovsky** [bufbuild/buf#2649]
When using buf 1.28.1 and not using the default linter a failure is raised

Example buf.yaml
```yaml
lint:
  use:
    - PROTOVALIDATE
```

when running `buf lint --path my/path` the following error is outputted: `Failure: "PROTOVALIDATE" is not a known id or category`

Version output:
```
buf --version
1.28.1
```
