### ISSUE TITLE
Field Deps Not Found in Type bufgen.ExternalConfigV1

### ISSUE THREAD

**Issue by au-z** [bufbuild/buf#2664]
Seems there may a simple explanation for this, but I can't seem to figure out what's wrong with these dependencies. Anyone know what may be going on?

```yaml
# buf.gen.yaml
version: v1
deps:
  - buf.build/googleapis/googleapis
plugins:
  - plugin: es
    opt: target=ts
    out: src/proto
  - plugin: connect-es
    opt: target=ts
    out: src/proto
```

```bash
buf generate ./proto

Failure: could not unmarshal as YAML: yaml: unmarshal errors:
  line 2: field deps not found in type bufgen.ExternalConfigV1
```

```bash
buf --version
1.28.1
```
