### ISSUE TITLE
Imported file does not exist Error

### ISSUE THREAD

**Issue by anandwana001** [bufbuild/buf#273]
Buf Lint Check is failing for import files when not passing input params

using 0.37.1 version

The command I am using:
```
buf lint --config buf.yaml
```

The error I am getting:
```
model/src/main/proto/exploration.proto:5:8:subtitled_html.proto: does not exist
```

My Proto file - [exploration.proto](https://github.com/oppia/oppia-android/blob/develop/model/src/main/proto/exploration.proto)
```proto
syntax = "proto3";

package model;

import "subtitled_html.proto";
import "subtitled_unicode.proto";
import "interaction_object.proto";
import "translation.proto";
import "voiceover.proto";

option java_package = "org.oppia.android.app.model";
option java_multiple_files = true;

// Structure for a single exploration.
// Maps from: data/src/main/java/org/oppia/android/android/data/backends/gae/model/GaeExploration.kt
message Exploration { }
```

If I am adding a path argument in the command

The command I am using:
```
buf lint model/src/main/proto buf.yaml
```

All lint check passes here

[buf.yaml](https://github.com/oppia/oppia-android/blob/develop/buf.yaml)
```yaml
version: v1beta1
build:
  roots:
    - .
  excludes:
    - model/build

lint:
  use:
    - DEFAULT
  except:
    - PACKAGE_DIRECTORY_MATCH
    - PACKAGE_VERSION_SUFFIX
    - ENUM_VALUE_PREFIX
```

1. Is it necessary to pass a path argument?
2. How can we run the `buf lint` to the whole repository?
3. Is using `.` in roots is the correct way to target the whole repository?
4. Reference issue where I find this error - https://github.com/oppia/oppia-android/pull/2776
