### ISSUE TITLE
buf generate does not appear to respect buf.yaml excludes rules

### ISSUE THREAD

**Issue by YvanJAquino** [bufbuild/buf#2814]
# The question

I need to manually copy / include certain protos for annotations (for grpc-gateway and gnostic) - but when I perform buf generate, some of the resulting go code has a namespace conflict. How can I tell buf that I don't want to compile these "annotations.proto"s and their dependencies?

# The problem

My project requires a number of GCP services (from official Google Cloud Go Client Libraries) that seem to conflict with my application at runtime - see the stack trace below for more details.

## Stack trace:

```shell
developer@vscode-v2:~/gitlab.com/prototypes/go-cx-cip$ go run cmd/server/main.go
panic: proto: file "google/api/http.proto" has a name conflict over google.api.CustomHttpPattern
        previously from: "gitlab.com/prototypes/go-cx-cip/pkg/api/google"
        currently from: "google.golang.org/genproto/googleapis/api/annotations"
See https://protobuf.dev/reference/go/faq#namespace-conflict
```

## The (temporary) fix

Having introspected the generated files, it appears that some of the google protos (for grpc-gateway) and gnostic protos (for openapiv3 code-gen) protos are generated into go modules which are then imported into the main types file (service.pb.go).

```go
import (
	_ "gitlab.com/prototypes/go-cx-cip/pkg/api/google"
	_ "gitlab.com/prototypes/go-cx-cip/pkg/api/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)
```

Since the problem is a runtime problem, I decided to remove any references in that file to the code generated packages such that the imports look like this in that service.pb.go which solves my problem - but now I need to do this every time I rebuild the protos, which is a bit annoying.

```go
import (
 protoreflect "google.golang.org/protobuf/reflect/protoreflect"
 protoimpl "google.golang.org/protobuf/runtime/protoimpl"
 reflect "reflect"
 sync "sync"
)
```

## Evaluation of buf capabilities.

According to the buf documentation ( [https://buf.build/docs/configuration/v1/buf-yaml#build](https://buf.build/docs/configuration/v1/buf-yaml#build) ), the recommendation is to add a build: { excludes: \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\] } clause to ignore the discovery and generation of these protos.  Unfortunately this continues to build those protos which causes some conflicts at runtime.  I still have to delete those imports manually for the solution to compile.

# Project Structure

```shell
.
├── Dockerfile
├── activate
├── api
│   ├── buf.yaml
│   ├── cip
│   │   └── v1
│   │       └── cip.proto
│   ├── google
│   │   ├── annotations.proto
│   │   └── http.proto
│   ├── openapi.yaml
│   ├── openapi_updated.yaml
│   └── openapiv3
│       ├── OpenAPIv3.proto
│       └── annotations.proto
├── buf.gen.yaml
├── cmd
│   └── server
│       └── main.go
├── go.mod
├── go.sum
└── pkg
    ├── api
    │   ├── cip
    │   │   └── v1
    │   │       ├── cip.pb.go
    │   │       ├── cip.pb.gw.go
    │   │       └── cip_grpc.pb.go
    │   ├── google
    │   │   ├── annotations.pb.go
    │   │   └── http.pb.go
    │   └── openapiv3
    │       ├── OpenAPIv3.pb.go
    │       └── annotations.pb.go
    ├── generative
    │   └── generative.go
    └── server
        └── server.go
```

# api/buf.yaml

```yaml
version: v1
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
build:
  excludes:
    - google
    - openapiv3
```

# ./buf.gen.yaml

```yaml
version: v1
managed:
  enabled: true
  go_package_prefix:
    # Used as the base path for importing from other .pb.go files.
    default: gitlab.com/prototypes/go-cx-cip/pkg
    except:
      - buf.build/googleapis/googleapis
plugins:
    # Generates proto types
  - plugin: buf.build/protocolbuffers/go
    out: pkg
    opt: paths=source_relative
    # Generates stubs for clients / servers
  - plugin: buf.build/grpc/go
    out: pkg
    opt: paths=source_relative
    # Generates stubs for REST RP
  - plugin: buf.build/grpc-ecosystem/gateway
    out: pkg
    opt: paths=source_relative
    # Generates OpenAPI Spec for Proto(s)
  - plugin: buf.build/community/google-gnostic-openapi
    out: api
    opt: [
      paths=source_relative,
      default_response=false
    ]
```

**Comment by bufdev** [comment]
The problem is that you are including the files directly into your main module, in which case `buf` will generate stubs for them like any of your other files in `api`. You can't `exclude` these files - this is excluding them at the build stage, not the generate stage, and at the build stage you need all imported files present. To make this so, what you want is to add `buf.build/googleapis/googleapis` as a dependency in your `buf.yaml`:

```
version: v1
deps:
  - buf.build/googleapis/googleapis
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
```

Then, inside `api`, run `buf mod update`.

By default, `buf generate` won't generate code for imports, and you've already excluded rewriting the Go package for `buf.build/googleapis/googleapis` in your `buf.gen.yaml`, so you will get the correct `google.golang.org` imports.

I don't know where openapiv3 came from - where are these files from?
