### ISSUE TITLE
buf generate get an error 

### ISSUE THREAD

**Issue by dobet** [bufbuild/buf#2835]
in this tree, I got an error.
```
api/v1/hello.proto:3:8:google/api/annotations.proto: does not exist
api/v1/hello.proto:12:25:syntax error: unexpected '/'
```
```
|-- api
|   `-- v1
|       |-- hello.proto
|       `-- hello.yaml
|-- buf.gen.yaml
|-- buf.yaml
`-- third_party
    |-- README.md
    |-- buf.yaml
    |-- errors
    |   `-- errors.proto
    |-- gnostic
    |   `-- openapi
    |       |-- discovery
    |       |   `-- v1
    |       |       `-- discovery.proto
    |       |-- v2
    |       |   `-- openapiv2.proto
    |       `-- v3
    |           |-- README.md
    |           |-- annotations.proto
    |           `-- openapiv3.proto
    |-- google
    |   |-- api
    |   |   |-- annotations.proto
    |   |   |-- field_behavior.proto
    |   |   |-- http.proto
    |   |   `-- httpbody.proto
    |   `-- protobuf
    |       |-- any.proto
    |       |-- api.proto
    |       |-- descriptor.proto
    |       |-- duration.proto
    |       |-- empty.proto
    |       |-- field_mask.proto
    |       |-- source_context.proto
    |       |-- struct.proto
    |       |-- timestamp.proto
    |       |-- type.proto
    |       `-- wrappers.proto
    |-- protoc-gen-openapiv2
    |   `-- options
    |       |-- annotations.proto
    |       `-- openapiv2.proto
    `-- validate
        |-- README.md
        `-- validate.proto
```

this is my buf.yaml and buf.gen.yaml
```
#buf.yaml
version: v1beta1
name: dmp/api/hello
build:
  roots:
    - buf
  

# buf.gen.yaml

version: v1
managed:
  enabled: false
plugins:
  # protoc-gen-go needs to be installed, generate go files based on proto files
  - name: go
    out: api/gen
    opt:
     - paths=source_relative
  # protoc-gen-go-grpc needs to be installed, generate grpc go files based on proto files
  - name: go-grpc
    out: api/gen
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false
  # protoc-gen-grpc-gateway needs to be installed, generate grpc-gateway go files based on proto files
  - name: go-http
    out: api/gen
    opt:
      - paths=source_relative

```

this is my proto
```

syntax = "proto3";
  
import "google/api/annotations.proto";

package api.v1;

// option go_package = "api/v1/greeter";

service Greeter {
  rpc Greeter (GreeterRequest) returns (GreeterResponse) {
        option (google.api.http) = {
                get: api/v1/helloworld
        };
  }
}

message GreeterRequest {
  string name = 1;
}

message GreeterResponse {
  string message = 1;
}
```

how to do ?
