### ISSUE TITLE
Imports from with non-directory roots

### ISSUE THREAD

**Issue by travisgroth** [bufbuild/buf#285]
Hi, the option to specify git references of external repositories that I wish to build is very useful but I'm wondering how it is intended to work in conjunction with imports.  It doesn't seem to make the external sources available for later roots to build against:

Example:

```yaml
build:
  roots:
    - ssh://git@github.com/envoyproxy/protoc-gen-validate.git
    - myapp/
```

myapp/test.proto:
```
syntax = "proto3";
package myapp;
import "validate/validate.proto";
```

```bash
buf build
myapp/test.proto:5:8:validate/validate.proto: does not exist
Failed to "build": .
```

Is there something else that needs to be done to enable this?  It would be really useful to be able to build a set of repository based sources that import each other.
