### ISSUE TITLE
lint: Excluding a rule doesn't seem to work

### ISSUE THREAD

**Issue by titpetric** [bufbuild/buf#2852]
I want to exclude field_lower_snake_case rules from buf lint, I have:

`buf.work.yml`:

```
version: v1
directories:
  - pkg
```

`buf.gen.yml`:

```
version: v1
managed:
  enabled: true
plugins:
  - plugin: go
    out: .
    opt: paths=source_relative
    strategy: directory
```

`pkg/model/v1/buf.yaml`:

```
version: v1
breaking:
  use:
    - FILE
lint:
  except:
    - FIELD_LOWER_SNAKE_CASE
```

`pkg/model/v1/model.proto`:

```
syntax = "proto3";

package pkg.model.v1;

option go_package = "pkg/model/v1";

service CoprocessService {
        rpc Do(DoRequest) returns (DoResponse);
}

message DoRequest {
  Object object = 1;
}

message DoResponse {
  Object object = 1;
}

message Object {
  string orgID = 1;
}
```

Issue reported by `buf lint`:

```
# buf lint
pkg/model/v1/model.proto:20:10:Field name "orgID" should be lower_snake_case, such as "org_id".
```

Buf version: 1.30.0
