### ISSUE TITLE
FIELD_SAME_ONEOF is not triggering

### ISSUE THREAD

**Issue by MollardMichael** [bufbuild/buf#2886]
I might have missunderstood the usage of FIELD_SAME_ONEOF as a breaking rule.

My understanding was that it would trigger as long as I add or remove a new field in a oneof .

So I tried the following

```
     oneof statusInfo {
         Booked booked = 100;
+        Booked booked_2 = 101;
     }
```

Using buf version 1.30.1.

I was expecting it to trigger the rule but it is not. 
Am I doing something wrong?

My buf.yaml
```
version: v1
lint:
  use:
    - DEFAULT
breaking:
  use:
    - WIRE
```
