### ISSUE TITLE
file (path/that/exists): does not exist

### ISSUE THREAD

**Issue by WadeLewis** [bufbuild/buf#295]
Hello, I'm attempting to incorporate buf into our repo but am currently unsuccessful at generating protobuf files.  What am I doing wrong here?  
Command: `buf generate -v --template templating.buf.gen.yaml ./templating/v1`
output: 
```
...
DEBUG	build_module	{"duration": "5.241379ms"}
templating/v1/templating.proto:5:8:templating/v1/messages.proto: does not exist
DEBUG	command	{"duration": "10.433803ms"}
```
Error: `templating/v1/templating.proto:5:8:templating/v1/messages.proto: does not exist`
The offending line (templating.proto line 5): `import "templating/v1/messages.proto";`

File structure: 
```
.
├── buf.yaml
├── templating.buf.gen.yaml
├── templating
│   └── v1
│       ├── messages.proto
│       └── templating.proto

```

my `buf.yaml` file: 
```
version: v1beta1
build:
  roots:
    - .
lint:
  use:
    - BASIC
    - FILE_LOWER_SNAKE_CASE
  except:
    - ENUM_NO_ALLOW_ALIAS
    - IMPORT_NO_PUBLIC
    - PACKAGE_AFFINITY
    - PACKAGE_DIRECTORY_MATCH
    - PACKAGE_SAME_DIRECTORY
breaking:
  use:
    - WIRE_JSON
```

And this is the `templating.buf.gen.yaml` file:
```
version: v1beta1
plugins:
  - name: go
    out: gen/go
    opt: paths=source_relative
  - name: go-grpc
    out: gen/go
    opt: paths=source_relative,require_unimplemented_servers=false
```

I don't understand why I'm able to compile using protoc, and not able to compile using buf.  Why is the CLI able to see `./templating/v1/templating.proto`, but is unable to import `./templating/v1/messages.proto`?

This works with protoc, does not work with buf CLI.  Any pointers on what I'm doing wrong?
