### ISSUE TITLE
I wonder about that why you changed lots of thing in 1.32?

### ISSUE THREAD

**Issue by kodmanyagha** [bufbuild/buf#2987]
Hi folks. I'm so thankful for this project, this is so important and helping too much. But I have a small question. Why you changed too much thing in minor version upgrade? You added v2 implementation for yaml files and changed other important things. I think its version must be 2. Thanks.

**Comment by bufdev** [comment]
Hey @kodmanyagha - appreciate the feedback. Buf follows semantic versioning, which only specifies for major versions to be changed if there are breaking changes. There are no breaking changes in v1.32.0, and major versions are incredibly disruptive, so it is a minor change. The Buf team took great care to make sure that v1.32.0 continues to work with all of your workflows.

**Comment by kodmanyagha** [comment]
Thanks for your message. In my project I didn't able to compile with 1.32. I can't show the code for privacy reasons but I'm going to create a simple example project which works in 1.31 but not 1.32. @bufdev

**Comment by bufdev** [comment]
Ok sounds good - if something doesn't work in 1.32 that worked in 1.32, that is a bug, if you file an issue we will be happy to look at it!

**Comment by kodmanyagha** [comment]
For example I stored all proto files in "proto" folder. In 1.31 I can compile all proto files: `npx buf generate proto`

But in 1.32 this command isn't working. It gives this error: 

```
Failure: failed to build input "proto" because it is contained by module at path "." specified in your configuration, you must provide the workspace or module as the input, and filter to this path using --path
```

Let me show my buf.yaml and buf.gen.yaml files:

```
# buf.yaml
version: v1
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
build:
  excludes: [node_modules]

```

```
# buf.gen.yaml
version: v1
plugins:
  - name: es
    opt: target=ts
    out: src/proto
  - name: connect-es
    opt: target=ts
    out: src/proto
  - name: ts_proto
    out: src/proto
    strategy: all

    # https://github.com/stephenh/ts-proto?tab=readme-ov-file#supported-options
    opt:
      - target=nestJs
      - nestJs=true
      - env=node
      - fileSuffix=_nest
      - addGrpcMetadata=true
      - esModuleInterop=true
      - snakeToCamel=false
      - stringEnums=true

```

What do you suggest bro? @bufdev
