### ISSUE TITLE
buf -generate with "#subdir" GitHub link appears to be broken in v1.32.0.

### ISSUE THREAD

**Issue by jstraceski** [bufbuild/buf#3000]
Probably due to a parsing issue on the URL if I were to guess.

Steps to reproduce:
```
GO111MODULE=on GOBIN=/usr/local/bin go install github.com/bufbuild/buf/cmd/buf@v1.32.0

buf -v generate 'https://github.com/envoyproxy/envoy.git#subdir=api,branch=main' --path=envoy/service/ext_proc/v3/external_processor.proto --include-imports
```

**Comment by jstraceski** [comment]
Works with:
```
GO111MODULE=on GOBIN=/usr/local/bin go install github.com/bufbuild/buf/cmd/buf@v1.31.0

buf -v generate 'https://github.com/envoyproxy/envoy.git#subdir=api' --path=envoy/service/ext_proc/v3/external_processor.proto --include-imports
```

**Comment by jstraceski** [comment]
Contents of our buf.gen.yaml file
```
# buf.gen.yaml
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/grpc/python:v1.62.1
    out: protodef
  # dependencies
  - plugin: buf.build/protocolbuffers/python
    out: protodef
```
