### ISSUE TITLE
Configuration of gen file V2 Directory: include fails with error

### ISSUE THREAD

**Issue by Nokinori** [bufbuild/buf#3049]
Hello!
I want to do a generation of directories within one.
According to the doc [here](https://buf.build/blog/buf-cli-next-generation) I can use directory.include.

tree:
```
root/
-buf.yaml
-buf.gen.yaml
-proto/
--org/
---example/
----dir1/
-----file.proto
-----subdir/
------file.proto
----dir2/
-----file.proto
----dir3/
```
buf.yaml
```
version: v2
modules:
  - path: proto
    name: buf.build/org/example
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
```
buf.gen.yaml
```
version: v2
plugins:
  - local: protoc-gen-go
    out: gen/proto/go
    opt: paths=source_relative
inputs:
  - directory: proto
    include:
      - proto/org/example/dir1
      - proto/org/example/dir2
```

Exec `buf -v generate`
Fails with `Failure: decode buf.gen.yaml: invalid as version v2: could not unmarshal as YAML: yaml: unmarshal errors:
  line 28: field include not found in type bufconfig.externalInputConfigV2
`
Exec` buf -v generate --path=proto/org/example/dir1/` works.

Am I doing something wrong with configuration in yaml?
