### ISSUE TITLE
buf generate --path with file globs

### ISSUE THREAD

**Issue by veith** [bufbuild/buf#313]
It would be nice, to be able, to use file globs in the path argument.

Given following config:
```yaml
build:
  roots:
    - dist/protos
    - dependencies/github.com/some/external/proto/dir
```

To generate all protos inside of dist/protos  you have to type one of following commands:
```bash
# Note: dist/protos is a root
buf generate --path `glob dist/protos/* | tr ' ' ,`

buf generate --path $(glob dist/protos/* | tr ' ' ,)
```

Desired behaviour:
```bash
buf generate --path dist/protos/*
#or
buf generate --pathglob dist/protos/*
```
