### ISSUE TITLE
Target dir for input:git_repo 

### ISSUE THREAD

**Issue by hollyhox-21** [bufbuild/buf#3152]
### Feature

Please add the target directory where the compiled proto file will be placed

```
  - git_repo: "https://github.com/some-repo.git"
    branch: master
    subdir: endpoints
    target: pkg/some_dir/some_grpc_services
```

**Comment by bufdev** [comment]
We do not understand what you are asking for - output locations are specified in the plugins configuration, not the inputs. Can you clarify?

**Comment by hollyhox-21** [comment]
I mean override out for input git_repo. I want to compile outside proto files. And use their for create client

**Comment by bufdev** [comment]
I still don't understand. Can you create an example repository with what you want to see, and the output?

**Comment by doriable** [comment]
The `inputs` key in `buf.gen.yaml` currently does not interact with the `plugins` key -- the destination of your output is configured in `plugins` on a per-plugin basis, and then each plugin is applied to each input.

If you want a different plugin configuration, our current guidance is to define a second file, e.g. `buf.remote.gen.yaml`, and have your the remote repository you are targeting and plugin configurations, e.g.

```
**buf.gen.yaml:**

version: v2
plugins:
  - remote: buf.build/protocolbuffers
    out: pkg/api
    opt:
      - paths=source_relative
inputs:
  - directory: api

**buf.remote.gen.yaml:**
version: v2
plugins:
  - remote: buf.build/protocolbuffers
    out: pkg/remote_api
    opt:
      - paths=source_relative
  - git_repo: "https://github.com/serviceA.git"
     branch: master
     subdir: api
```

And then you can use the second file with `buf generate --template buf.remote.gen.yaml`.

We have similar requests in the past, https://github.com/bufbuild/buf/issues/3060, I can close this as a duplicate and we can combine the discussions. Thanks!
