### ISSUE TITLE
Add link to docs in `buf config init`

### ISSUE THREAD

**Issue by stefanvanburen** [bufbuild/buf#3180]
### Feature

`buf config init` currently generates:

```yaml
version: v2
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
```

I effectively always need to reference https://buf.build/docs/configuration/v2/buf-yaml in order to specify more configuration. It would be nice if the generated config could directly link to that page, perhaps in a comment, so that it's easier to get started editing the configuration.

Something like:

```yaml
# https://buf.build/docs/configuration/v2/buf-yaml
version: v2
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
```

I don't think `buf config init` can generate non-`v2` buf.yaml files, but the URL should correspond to the version of the file being created.
