### ISSUE TITLE
Cannot generate import for googleapis datatype under managed mode.

### ISSUE THREAD

**Issue by li3p** [bufbuild/buf#3191]
### GitHub Repository

https://github.com/li3p/hellobuf

### Commands

```shell
buf generate
```

### Output

```shell
with `managed: enabled: true` in `buf.gen.yaml`

missing `datetime "google.golang.org/genproto/googleapis/type/datetime"`


package weather

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)
```

### Expected Output

with `managed: enabled: false` in `buf.gen.yaml`

```go
package weather

import (
	datetime "google.golang.org/genproto/googleapis/type/datetime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)
```

**Comment by doriable** [comment]
Thank you for providing a clear repro, we're taking a look at this!

**Comment by oliversun9** [comment]
Hi there, I was able to reproduce this. The problem lies in the disable rules in the managed mode config, you have:

```
...
  override:
    - file_option: go_package
      value: hellobuf/gen/acme/weather/v1;weather
  disable:
    - module: buf.build/googleapis/googleapis
      file_option: go_package_prefix
...
```

Notice how the override rule says `go_package` while the disable rule says `go_package_prefix`. This results in `buf.build/googleapis/googleapis` still being modified, because a disable rule for `go_package_prefix` does not disable rules for `go_package_prefix`.

The fix is to change `go_package_prefix` to `go_package` in the disable rule, it will look like:

```
...
  override:
    - file_option: go_package
      value: hellobuf/gen/acme/weather/v1;weather
  disable:
    - module: buf.build/googleapis/googleapis
      file_option: go_package # here
...
```
