### ISSUE TITLE
Using a plugin that defines some options under `_out`

### ISSUE THREAD

**Issue by aaomidi** [bufbuild/buf#3199]
### Feature

I am trying to use https://github.com/chrusty/protoc-gen-jsonschema with buf, and set the `--jsonschema_out=json_fieldnames:.` option. Note that this is a `_out` and not a `_opt`.

I don't think there is a way to do this on buf right now?

**Comment by doriable** [comment]
Hi, this is specific behaviour that the plugin `protoc-gen-jsonschema` is using from the plugins: https://pkg.go.dev/google.golang.org/protobuf/compiler/protogen#Options

> 	//   --go_out=<param1>=<value1>,<param2>=<value2>:<output_directory>

So basically, when you set `jsonschema_out=<out option>:.`, the compiler is handling the out directory, `.`, and passes the rest as parameters to `protoc-gen-jsonschema` to handle.

If you are using these `jsonschema_out` parameters with `buf.gen.yaml`, you can pass them as `opt`s in the following way:

```
version: v2
managed:
  enabled: true
plugins:
  - local: protoc-gen-jsonschema
    opt:
      - json_fieldnames
    out: .
``` 

This above example `buf.gen.yaml` is equivalent to `jsonschema_out:json_fieldnames:.`, where the parameter value is `json_fieldnames` and the out directory is `.`.

**Comment by aaomidi** [comment]
So to make sure I understand correctly, this is not possible with using a remote plugin?

**Comment by aaomidi** [comment]
```
version: v2
managed:
  enabled: false
plugins:
  - remote: buf.build/community/chrusty-jsonschema:v1.4.1
    out: chart/
    opt:
      - json_fieldnames
```
vs

```
version: v2
managed:
  enabled: false
plugins:
  - local: protoc-gen-jsonschema
    out: chart/
    opt:
      - all_fields_required
      - file_extension=schema.json
      - enforce_oneof
      - json_fieldnames

```
