### ISSUE TITLE
Add post-processing commands

### ISSUE THREAD

**Issue by benedikt-bartscher** [bufbuild/buf#3207]
### Feature

I would love to see an option for the buf generator which adds custom post-processing commands.
For example running ruff after generating code with python-betterproto.

Slack ref: https://bufbuild.slack.com/archives/CRZ680FUH/p1722782692615029

**Comment by benedikt-bartscher** [comment]
Commands could be specified per plugin. It should be possible to pass the out directory to the commands, f.e. like this:

buf.gen.yaml
```yaml
plugins:
  - local: protoc-gen-python_betterproto
    out: gen
    post:
      - "ruff --fix $out"
```
