### ISSUE TITLE
how to append protoc params for generate

### ISSUE THREAD

**Issue by YeRuyi** [bufbuild/buf#321]
Just like protoc-gen-validate lib, I have to append opt like `--validate_out="lang=go:../generated"` , how can I resolve it by buf tool.

**Comment by YeRuyi** [comment]
buf.yaml:
```
version: v1beta1
name: buf.build/roypbtest/test
deps:
  - buf.build/beta/googleapis
  - buf.build/beta/protoc-gen-validate
build:
  roots:
    - .
```

**Comment by bufdev** [comment]
Use the `opt` option, as explained in the docs for `buf generate`: https://docs.buf.build/generate-usage

**Comment by YeRuyi** [comment]
@bufdev, thx for help. Do you know protoc-gen-valid plugin name? I try using opt in go plugin and have error
```
build.gen.yaml

version: v1beta1
plugins:
  - name: go
    out: build
    opt:
      - paths=source_relative
      - validate_out="lang=go:./build"
```
and console is:
```
protoc-gen-go: no such flag -validate_out
Failed to "generate": plugin go: exit status 1; exit status 1; exit status 1.
```

**Comment by YeRuyi** [comment]
I have resolved it, got the answer by trying replace params. using yaml like

```
version: v1beta1
plugins:
  - name: go
    out: build
    opt:
      - paths=source_relative
  - name: validate
    out: build
    opt:
      - lang=go
      - validate_out="lang=go:./build"
```
