### ISSUE TITLE
when i use git repo in buf.generate.yaml#inputs, how can i set buf.yaml#modules

### ISSUE THREAD

**Issue by jluncc** [bufbuild/buf#3280]
### What's up?

i have third_party proto files which on gitlab, and it work with Java code so without go_package in it

now i want to use buf to generate go file with this proto file, so i have a `buf.gen.yaml` file on my project and use git repo inputs like below:

``` yml
inputs:
  - git_repo: xxx
```

but get error when i `buf generate`: 

```txt
Please specify either:
        • a "go_package" option in the .proto source file, or
        • a "M" argument on the command line.
```

so i want to use buf managed mode to override go_package, but i do not know how to set module on `buf.yaml` when i use git repo inputs instand of local proto file

**Comment by emcfarlane** [comment]
Hi @jluncc, please see the docs for `go_package_prefix` and `go_package` [here](https://buf.build/docs/generate/managed-mode#go). You'll need to set the overrides in your `buf.gen.yaml` something like:
```
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: data
```
Ensure you are correctly scoping the override to the module with the `moudle` or `path` options.

**Comment by jluncc** [comment]
> Hi @jluncc, please see the docs for `go_package_prefix` and `go_package` [here](https://buf.build/docs/generate/managed-mode#go). You'll need to set the overrides in your `buf.gen.yaml` something like:
> 
> ```
> managed:
>   enabled: true
>   override:
>     - file_option: go_package_prefix
>       value: data
> ```
> 
> Ensure you are correctly scoping the override to the module with the `moudle` or `path` options.

@emcfarlane thanks for your reply, but, this setting not work when i use git_repo inputs 

i know it can work when i use local path, but i want to know is, when i use git_repo inputs how can i use managed mode ?

**Comment by emcfarlane** [comment]
@jluncc please provide a reproducible example. I've tested with a git_repo for the following `buf.gen.yaml`:
```
version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: data
plugins:
  - local: protoc-gen-go
    out: gen/go
    opt: paths=source_relative
inputs:
  - git_repo: https://github.com/emcfarlane/buf-yamls.git
    subdir: modnodeps
    branch: noGoPackage
```
The branch `noGoPackage` has your two restrictions:
1. No `buf.yaml` file.
2. No `go_package` option in the file.
See the branch [here](https://github.com/emcfarlane/buf-yamls/compare/main...noGoPackage). If you follow the issue template it will help us provide support.

**Comment by bufdev** [comment]
@jluncc this issue will be closed unless you provide a reproducible example in a temporary github repository per the issue template instructions, thanks.

**Comment by jluncc** [comment]
> @jluncc please provide a reproducible example. I've tested with a git_repo for the following `buf.gen.yaml`:
> 
> ```
> version: v2
> managed:
>   enabled: true
>   override:
>     - file_option: go_package_prefix
>       value: data
> plugins:
>   - local: protoc-gen-go
>     out: gen/go
>     opt: paths=source_relative
> inputs:
>   - git_repo: https://github.com/emcfarlane/buf-yamls.git
>     subdir: modnodeps
>     branch: noGoPackage
> ```
> 
> The branch `noGoPackage` has your two restrictions:
> 
> 1. No `buf.yaml` file.
> 2. No `go_package` option in the file.
>    See the branch [here](https://github.com/emcfarlane/buf-yamls/compare/main...noGoPackage). If you follow the issue template it will help us provide support.

@emcfarlane sorry i miss something, i test your yaml and can generate as well,   

my proto have import googleapi proto like `import "google/api/annotations.proto";` 

and my `buf.gen.yaml` like below:  

```yml
version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: data
  disable:
    - module: buf.build/googleapis/googleapis
      file_option: go_package_prefix      
plugins:
  - remote: buf.build/grpc-ecosystem/gateway:v2.22.0
    out: gen/go
    opt:
      - allow_delete_body=true
  - remote: buf.build/grpc/go:v1.5.1
    out: gen/go
    opt:
      - require_unimplemented_servers=false
  - remote: buf.build/protocolbuffers/go:v1.34.2
    out: gen/go
inputs:
  - git_repo: xxx
```  

so i also want to use buf to solve googleapi dependecny issue, and because my proto repo have not `buf.yml` that can not declare googleapi dependency when generate  

however, i think i can copy proto to local path and add buf.yml to handle my case   

thanks a lot again
