### ISSUE TITLE
pyi output for python grpc

### ISSUE THREAD

**Issue by vojtajina** [bufbuild/buf#3285]
### Feature

Is it possible to get pyi types (for python autocomplete), for grpc?

It works for python protobufs, but I can't get it working for the _grpc.py files.

**Comment by doriable** [comment]
This is a concern for the `grpc-python` plugin and not from the `buf` CLI. My understanding is that type hints is not yet available for gRPC https://github.com/grpc/grpc/issues/29041 but it seems like there is work being done. I would check-in with the gRPC folks on this one, thanks!

**Comment by vojtajina** [comment]
@doriable thanks, I will look into the plugin you mentioned.

grpc-tools generates it (this is what I used before switching to buf):
```
python -m grpc_tools.protoc \
    --python_out=api_mock \
    --pyi_out=api_mock \
    --grpc_python_out=api_mock \
    --proto_path ../../protos/api_server \
    ../../protos/api_server/api_server_grpc.proto
```

but I don't know how to use it with buf.

**Comment by doriable** [comment]
Ah okay, so basically `grpc_tools.protoc` combines three plugins: protocolbuffers python, grpc python, and pyi. So, with `buf`, you basically need to run the same three plugins, which we have available on the BSR remotely. So, you basically need a `buf.gen.yaml` file with all three plugins configured, which would look something like:

```
version: v2
managed:
  enabled: true
plugins:
  - remote: buf.build/protocolbuffers/python:v27.4
    out: api_mock # based on the example provided
  - remote: buf.build/grpc/python:v1.66.1
    out: api_mock
  - remote: buf.build/protocolbuffers/pyi:v27.4
    out: api_mock
```

For more information on configuring the inputs, or if you are managing the plugins locally, etc. you can reference our `buf.gen.yaml` docs: https://buf.build/docs/configuration/v2/buf-gen-yaml
