### ISSUE TITLE
add a .pre-commit-hooks.yaml

### ISSUE THREAD

**Issue by MelleKoning** [bufbuild/buf#340]
For easy implementation/integration with pre-commit, could a `.pre-commit-hooks.yaml` be added to the repository?

For a local repository containing some *.proto files, we should be able to add something like the following pre-commit hook to the .pre-commit-config.yaml:

```
- repo: https://github.com/bufbuild/buf
    rev: v0.41.0
    hooks:
      - id: buf
        name: buf linter
        description: Validates proto files
        entry: buf
        language: golang
        language_version: 1.15.8
        pass_filenames: false
        args: [lint --path ./api]
```

**Comment by johanbrandhorst** [comment]
Are you suggesting that we should add a pre-commit hook to this repository? I'm not sure I follow.

**Comment by MelleKoning** [comment]
Yes, for tools like linters it's not uncommon to support the pre-commit hooks in the repository. The file tells pre-commit about the language used.

As examples see
- https://github.com/golangci/golangci-lint/blob/master/.pre-commit-hooks.yaml
- https://github.com/adrienverge/yamllint/blob/master/.pre-commit-hooks.yaml

**Comment by bufdev** [comment]
I think we are going to pass on this, although thank you for the suggestion - pre-commit isn't widely used enough for us to maintain code for it in our primary repository.

**Comment by MelleKoning** [comment]
Just for reference, the `.pre-commit-hooks.yaml` that works for me on a [fork](https://github.com/MelleKoning/buf/blob/master/.pre-commit-hooks.yaml):

```
- id: buf
  name: buf linter
  description: Validates proto files
  entry: buf  
  language: golang
  types: [proto]
```

**Comment by ryanrhee** [comment]
FYI, pre-commit support has landed.

To [quote](https://github.com/bufbuild/buf/issues/1077#issuecomment-1150422915) @bufdev:
> This is added from https://github.com/bufbuild/buf/pull/1182, is available on main, and will go out in the next release.

**Comment by MelleKoningSGG** [comment]
@ryanrhee did you ever manage to run the buf linter for proto files that are not in root? What config in `.pre-commit-config.yaml` did you use for that?

**Comment by ryanrhee** [comment]
You have to point the invocation to your buf yaml or buf work yaml file.

Also, override the file extension in your config if your protobuf files do not use the .proto extension

**Comment by MelleKoningSGG** [comment]
@ryanrhee how?

In my current example, the proto files are in a subfolder `/api` from root.

/api/some.proto
/api/other.proto (refers to some.proto)
/api/buf.yaml

in `.pre-commit-config.yaml` I have tried several things for example:
```
- repo: https://github.com/bufbuild/buf
    rev: v1.6.0
    hooks:
      - id: buf-lint
        args: [api/buf.yaml, --error-format=json]
```

but the output of `pre-commit run -a -v` is always:

```
buf linter...........................................(no files to check)Skipped
- hook id: buf-lint
```

the `api/buf.yaml` contains:

```
version: v1beta1
build:
  roots:
    - .
lint:
  use:
    - BASIC
    - FILE_LOWER_SNAKE_CASE
  except:
    - ENUM_NO_ALLOW_ALIAS
    - IMPORT_NO_PUBLIC
    - PACKAGE_AFFINITY
    - PACKAGE_DIRECTORY_MATCH
    - PACKAGE_SAME_DIRECTORY
    - DIRECTORY_SAME_PACKAGE
breaking:
  use:
    - WIRE_JSON

```
I have no idea why buf can not find the proto files.

Also tried: putting `buf.yaml` in root and pointing to the ./api folder in the `buf.yaml`, as well as adding `files: ^api/.*\.proto$` in the pre-commit-config.yaml, etc:  but the result is always "no files to check" ?
Did I miss something very obvious?

**Comment by ryanrhee** [comment]
@MelleKoning are you able to run buf without `pre-commit`? what is the invocation you use?

**Comment by MelleKoningSGG** [comment]
> @MelleKoning are you able to run buf without `pre-commit`? what is the invocation you use?

When I run buf simply from commandline in the repository root and proto files as well as buf.yaml are in ./api, then I get:
```
buf lint ./api
api/sim.proto:265:9:Service name "sim" should be PascalCase, such as "Sim".
```

...which is a valid warning.

When I run `pre-commit` in the repository root, then I get no files found.

Note that the buf.yaml is also in ./api.

Running via pre-commit, configured in `.pre-commit-config.yaml` like so:
```
- repo: https://github.com/bufbuild/buf
    rev: v1.6.0
    hooks:
      - id: buf-lint
        args: [api/buf.yaml, --error-format=json]
```

outputs:
`buf lint.............................................(no files to check)Skipped`

Are the arguments in the `.pre-commit-config.yaml` setup correctly?
