### ISSUE TITLE
How to pass "--dart_out=grpc:./lib/" in buf.gen.yaml

### ISSUE THREAD

**Issue by kkweon** [bufbuild/buf#341]
## Summary

In order to create a gRPC client, I need to pass `protoc --dart_out=grpc:./client/lib/protos <proto>`.
But, none of the following seems to work in buf.gen.yaml

```yaml
version: v1beta1
plugins:
  - name: dart
    out: grpc:./client/lib/protos
```

## Expectation

- The above gets translated to `--dart_out=grpc:./client/lib/protos` which would generate in `./client/lib/protos/...`
- gRPC files are generated.

## Current behavior

- The above would work as if I ran with `--dart_out='grpc:./client/lib/protos'`. So, it would create a directory called `grpc:./`
- No gRPC files are generated

## References

- gRPC Dart Tutorial: https://grpc.io/docs/languages/dart/quickstart/#regenerate-grpc-code

**Comment by bufdev** [comment]
```yaml
version: v1beta1
plugins:
  - name: dart
    out: client/lib/protos
    opt: grpc
```
