### ISSUE TITLE
Can I generate code into multiple directories?

### ISSUE THREAD

**Issue by kskumgk63** [bufbuild/buf#342]
Hey, I am just wondering if I can generate code into multiple directories.

I know `buf.gen.yaml` below is invalid, but I want to do like this.

```yaml
version: v1beta1
plugins:
  - name: go
    out:
      - .
      - ../path/to
    opt: paths=source_relative
  - name: go-grpc
    out:
      - .
      - ../path/to
    opt: paths=source_relative
```

If there are no way to do that, I would like to know if you have a plan to implement this feature.
