### ISSUE TITLE
[question] buf - how to remove existing path

### ISSUE THREAD

**Issue by kcris** [bufbuild/buf#3426]
### What's up?

Using a scala service with protobuf based grpc. I used to have 3 folders with .proto files in the service. One of those is now moved to a different library. So my buf.yaml was adjusted as follows:

```yaml
version: v2
modules:
  ##- path: other/src/main/protobuf ##this is now being moved to a separate library
  - path: service/src/main/protobuf
  - path: service/target/protobuf_external
    breaking:
      use:
        - WIRE
      except:
        - FIELD_SAME_DEFAULT
```

When `buf breaking ...` is running (on my dev branch) it complains that:

```bash
buf breaking --against /tmp/my-master-branch-copy --error-format=json

Failure: input contained 2 images, whereas against contained 3 images
```

So the question is: How to properly get rid of the removed .proto path/folder ?

Thanks
