### ISSUE TITLE
buf.gen.yaml opt isn't passing through correctly

### ISSUE THREAD

**Issue by evanmoran** [bufbuild/buf#344]
Hi there! I'm running into an issue where I want to pass an option to a plugin and it doesn't seem to be passing through correctly. The plugin is `ts-proto`: https://github.com/stephenh/ts-proto

Install the plugin like this:

```
npm install ts-proto
```
Then configure the `buf.gen.yaml` like this: 
```
version: v1
plugins:
  - name: ts-proto
    out: build/ts-proto
    path: ./node_modules/ts-proto/protoc-gen-ts_proto
    opt: "--ts_proto_opt=outputServices=grpc-js"
```

Expected:  the `outputServices=grpc-js` option generates a server proto
Actual: the plugin generates as if the option wasn't passed. 

If I run the same command manually with `protoc` it works correctly: 

```
find ./protos -name '*.proto' -exec \
	protoc {} \
		--proto_path=./protos \
		--plugin=./node_modules/ts-proto/protoc-gen-ts_proto \
		--ts_proto_out=./build/ts-proto \
		--ts_proto_opt=outputServices=grpc-js \
		\;
```

Maybe it's caused by the dash?  Any advice would be appreciated!

**Comment by bufdev** [comment]
You are encoding the `protoc` flag `--ts_proto_opt` as part of your `buf.gen.yaml`, instead, it should be:

```yaml
plugins:
  - name: ts-proto
    out: build/ts-proto
    path: ./node_modules/ts-proto/protoc-gen-ts_proto
    opt: outputServices=grpc-js
```

https://docs.buf.build/generate-usage
