### ISSUE TITLE
Failure: read buf.gen.yaml: file does not exist

### ISSUE THREAD

**Issue by cruvie** [bufbuild/buf#3442]
### GitHub repository with your minimal reproducible example (do not leave this field blank or fill out this field with "github.com/bufbuild/buf" or we will automatically close your issue, see the instructions above!)

no

### Commands

```shell
npm install @bufbuild/protobuf @bufbuild/protoc-gen-es @bufbuild/buf


cruvie@CruvieMacAir-4 kk_rbac_api % ls -l buf.gen.yaml 
-rw-r--r--@ 1 cruvie  staff  284 Nov  1 10:05 buf.gen.yaml
cruvie@CruvieMacAir-4 kk_rbac_api % npx buf generate
Failure: read buf.gen.yaml: file does not exist
cruvie@CruvieMacAir-4 kk_rbac_api %
```

### Output

```shell
Failure: read buf.gen.yaml: file does not exist
```

### Expected Output

generate ts file

### Anything else?

```yaml
# Learn more: https://buf.build/docs/configuration/v2/buf-gen-yaml
version: v2
inputs:
  - directory: ../../../kk_go_kit/kk_rbac/kk_rbac_api/kk_rbac_api_def
plugins:
  - local: protoc-gen-es
    opt: target=ts
    out: ../../../kk_go_kit/lib_ts/kk_rbac_api/models

#  npx buf generate
```

```sh
    "@bufbuild/buf": "^1.46.0",
    "@bufbuild/protobuf": "^2.2.1",
    "@bufbuild/protoc-gen-es": "^2.2.1",
```
