### ISSUE TITLE
[BUG] go module check update for buf package failed

### ISSUE THREAD

**Issue by solarhell** [bufbuild/buf#3453]
### How to reproduce

https://sum.golang.org/lookup/buf.build/gen/go/protocolbuffers/wellknowntypes/connectrpc/go@v1.17.0-20240829202630-d59b7d45e69d.1

### Output

```shell
not found: buf.build/gen/go/protocolbuffers/wellknowntypes/connectrpc/go@v1.17.0-20240829202630-d59b7d45e69d.1: reading https://buf.build/gen/go/buf.build/gen/go/protocolbuffers/wellknowntypes/connectrpc/go/@v/v1.17.0-20240829202630-d59b7d45e69d.1.zip: 400 Bad Request
	server response: generating files: invalid_argument: plugin "buf.build/connectrpc/go:v1.17.0" exited with non-zero status 1: protoc-gen-connect-go: unable to determine Go import path for "google/protobuf/cpp_features.proto"
```

### Expected Output

something like this

https://sum.golang.org/lookup/golang.org/x/tools@v0.26.0
```
30629555
golang.org/x/tools v0.26.0 h1:v/60pFQmzmT9ExmjDv2gGIfi3OqfKoEP6I5+umXlbnQ=
golang.org/x/tools v0.26.0/go.mod h1:TPVVj70c7JJ3WCazhD8OdXcZg/og+b9+tH/KxylGwH0=

go.sum database tree
31465925
o2YqmsR/07bA4UH1xIFDEKC/Ue8LQMFM3w/58zAQV6c=

— sum.golang.org Az3grseXe9LdN4DYVxObtPAPFOdsY7pxJHh3CMtSGKHHjcFh4GR1T5xNy2ABLTnswaSo5OyT9RJ/1sv6ah0cooo0zQA=
```

**Comment by doriable** [comment]
Hello, thanks for filing this issue. This is occurring because we added [cpp_features.proto](https://buf.build/protocolbuffers/wellknowntypes/file/main:google/protobuf/cpp_features.proto) and [java_features.proto](https://buf.build/protocolbuffers/wellknowntypes/file/main:google/protobuf/java_features.proto) files which do not have the `go package` option defined.

That being said, if you are looking to work with well-known types and Go code, they are available already in the Go protobuf runtime: https://pkg.go.dev/google.golang.org/protobuf/types/known@v1.35.1.

I also noted that you are attempting to generate this with `connect-go` -- there are no RPC services for well-known types, which is what the `connect-go` plugin is used to generate, so you should not be using the plugin with the well-known type protobuf definitions.

**Comment by solarhell** [comment]
Thanks for the reply, I am indeed using `connect-go` and have added `googleapis` and `wellknowntypes` to the `deps` of `buf.yaml`. What should I tweak to avoid generating code for wellknowntypes?

FYI，this my is my current config

`buf.yaml`

```
version: v2
modules:
  - path: .
    name: buf.build/wolodata/api
lint:
  use:
    - STANDARD
  except:
    - FIELD_NOT_REQUIRED
    - PACKAGE_NO_IMPORT_CYCLE
  disallow_comment_ignores: true
breaking:
  use:
    - FILE
  except:
    - EXTENSION_NO_DELETE
    - FIELD_SAME_DEFAULT
deps:
    - buf.build/googleapis/googleapis
    - buf.build/protocolbuffers/wellknowntypes
```

and `buf.gen.yaml`

```
version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: github.com/wolodata/proto/gen
plugins:
  - remote: buf.build/protocolbuffers/go:v1.35.1
    out: gen
    opt:
      - paths=source_relative
  - remote: buf.build/connectrpc/go:v1.17.0
    out: gen
    opt:
      - paths=source_relative
  - remote: buf.build/connectrpc/es:v1.5.0
    out: gen
  - remote: buf.build/bufbuild/es:v1.10.0
    out: gen
```
