### ISSUE TITLE
Failed to "generate": plugin go: packages are not getting created that is mentioned in go_package

### ISSUE THREAD

**Issue by haseebH** [bufbuild/buf#347]
`buf generate`, is creating packages based on the path of the `proto` file in the directory. I am currently using `protoc` to generate code and packages are generated based on the `go_package` path for Go.

Is there any way in buf to generate packages based on the `go_package` parameter? 

buf.gen.yaml file
```
version: v1beta1
plugins:
  - name: go
    out: proto
    opt:
      - paths=source_relative
  - name: go-grpc
    out: proto
    opt:
      - paths=source_relative
```

proto/hello_world.proto file
```
syntax = "proto3";

option go_package = "github.com/haseebH/helloworld/go";

// The greeting service definition
service GreeterService {
  // Sends a greeting
  rpc SayHello (SayHelloRequest) returns (SayHelloResponse) {}
}

// The request message containing the user's name
message SayHelloRequest {
  string name = 1;
}

// The response message containing the greetings
message SayHelloResponse {
  string message = 1;
}
````
