### ISSUE TITLE
remote plugin fail

### ISSUE THREAD

**Issue by mingzaily** [bufbuild/buf#3488]
### What's up?

Everything was normal until today, but an error was reported today

```
Failure: unimplemented: unary response has zero messages for https://buf.build/buf.alpha.registry.v1alpha1.CodeGenerationService/GenerateCode
This version of the buf CLI may require APIs that have not yet been deployed to https://buf.build
To resolve this failure, you can either:
- Try using an older version of the buf CLI
- Contact the site admin for https://buf.build to upgrade the instance
```

Our yaml file
```yml
version: v1
managed:
  enabled: true

plugins:
  - plugin: buf.build/protocolbuffers/go:v1.33.0
    out: apis-go
    opt: paths=source_relative
  - plugin: buf.build/grpc/go:v1.4.0 
    out: apis-go
    opt: paths=source_relative,require_unimplemented_servers=false
  - plugin: buf.build/bufbuild/validate-go:v1.0.4
    out: apis-go
    opt: paths=source_relative
  - plugin: go-http # kartos local plugin
    out: apis-go
    opt:
      - paths=source_relative
```
