### ISSUE TITLE
buf.yaml v2 Annotated buf.yaml configuration includes invalid values

### ISSUE THREAD

**Issue by KinNeko-De** [bufbuild/buf#3501]
### GitHub repository with your minimal reproducible example (do not leave this field blank or fill out this field with "github.com/bufbuild/buf" or we will automatically close your issue, see the instructions above!)

https://buf.build/docs/configuration/v2/buf-yaml/

### What's up?

Hey..
I am currently writing an article about the integration of buf in visual studio code.
I tried to managed a [gitrepository which contains the apis for multiple applications](https://github.com/KinNeko-De/poc-sample-apicontract-oneapi/tree/feature/define).

I finally found a version where `buf lint --config buf.yaml` does not report errors because of a wrong package name.

I found the solution with the documentaion: https://buf.build/docs/configuration/v2/buf-yaml/ and the following lines:

```yaml
  # Multiple modules are allowed to have the same path, as long as they don't share '.proto' files.
  - path: proto/common
    module: buf.build/acme/weather
    includes:
      - proto/common/weather
  - path: proto/common
    module: buf.build/acme/location
    includes:
      - proto/common/location
```

But `module` is no a valid field for a yaml.  Buf lint reports an error when parsing the buf.yaml

It must be replaced with `name`

```yaml
  # Multiple modules are allowed to have the same path, as long as they don't share '.proto' files.
  - path: proto/common
    name: buf.build/acme/weather
    includes:
      - proto/common/weather
  - path: proto/common
    name: buf.build/acme/location
    includes:
      - proto/common/location
```

Can you please confirm that my buf.yaml is correct? Buf lint now works without problems, but the visual studio extension does not show any errors anymore. I will create then an issue in the vs code extension github repository. I guess that the vs code extension does not support the [changes from august.](https://github.com/bufbuild/buf/blob/bbefdb843ea0ad68f1ab72003dbf40683cf304c1/CHANGELOG.md?plain=1#L87)

Greetings

Nils
