### ISSUE TITLE
How to use buf to build a submodule that is in googleapis, such as the bigtable v2 apis?

### ISSUE THREAD

**Issue by liufuyang** [bufbuild/buf#3510]
### GitHub repository with your minimal reproducible example:
https://github.com/liufuyang/rust-buf-bigtable-test/blob/main/buf.yaml

### How to repeat the issue:

For example, create a dummy repo/folder and cd into it, then:

```
git submodule add https://github.com/googleapis/googleapis.git
```

Add a simple `buf.gen.yaml` (this perhaps should do but I think I never get the step to be able to verify it yet)
```yaml
# buf.gen.yaml
version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: github.com/tobby-s/minimal-example
plugins:
  - local: protoc-gen-go
    out: generated/minimal-example
    opt:
      - paths=source_relative
  - local: protoc-gen-go-grpc
    out: generated/minimal-example
    opt:
      - paths=source_relative
inputs:
  - directory: .
```

Then I tried with `buf.yaml` as:

```yaml
# buf.yaml
version: v2
modules:
  - path: googleapis/google/bigtable/v2
deps:
  - buf.build/googleapis/googleapis
```

Gives:
```
buf dep update
googleapis/google/bigtable/v2/bigtable.proto:23:8:import "google/api/routing.proto": file does not exist
```

Also tried with:
```yaml
version: v2
modules:
  - path: googleapis/google/bigtable/v2
  - path: googleapis/google/api
```

```
rm buf.lock
buf generate
googleapis/google/api/annotations.proto:19:8:import "google/api/http.proto": file does not exist
```

But that file does exist? 🤔

**Comment by emcfarlane** [comment]
Hey @liufuyang the `path` specifies the module root which is where the import name comes from, so the file `google/api/http.proto` will be checked in each defined module, see more about pathing concepts [here](https://buf.build/docs/concepts/modules-workspaces/#unique-file-path-requirement). For the googleapis the module root is defined as the `googleapis` directory. If you wish to exclude the build to only required files you may use the `includes` parameter. Here is an example `buf.yaml`:
```yaml
version: v2
modules:
  - path: googleapis
    includes:
      - googleapis/google/bigtable/v2 
      - googleapis/google/api
      - googleapis/google/longrunning
      - googleapis/google/rpc
      - googleapis/google/logging
      - googleapis/google/type
```
