### ISSUE TITLE
Allow setting the use of the new opaque API as the default

### ISSUE THREAD

**Issue by advdv** [bufbuild/buf#3555]
### Feature

I would like to enable the user of the new opaque API for the whole project instead of just per-file. The official documentation suggests how to do this with a flag on the protoc compiler: https://protobuf.dev/reference/go/opaque-faq/#enable

I think the buf way of doing that would be with a managed overwrite on a file option. But i could not figure out how to do this currently. I'm on the main branch, building from source: `go install github.com/bufbuild/buf/cmd/buf@main`. 

I've tried the following, but i'm probably misunderstand:

```yaml
version: v2
managed:
  enabled: true
  disable:
    - file_option: go_package
      module: buf.build/bufbuild/protovalidate
  override:
    - file_option: go_package_prefix
      value: github.com/crewlinker/livejobs
    - file_option: api_level # probably wrong?
      value: API_OPAQUE # probably even more wrong
```
