### ISSUE TITLE
Add Support for `google.longrunning.Operation` in Linter Rules

### ISSUE THREAD

**Issue by yuloxx** [bufbuild/buf#3588]
### Feature

**Summary** Currently, when implementing APIs that adhere to the [[Google API Design Guide](https://google.aip.dev/151)](https://google.aip.dev/151) for long-running operations, the `google.longrunning.Operation` is the recommended response type for methods that might take significant time to complete. 

sample code:

```
service BookService {
  rpc CreateBook(CreateBookRequest) returns (google.longrunning.Operation) {
    option (google.api.http) = {
      post: "/v1/{parent=publishers/*}/books"
      body: "book"
    };
    option (google.longrunning.operation_info) = {
      response_type: "Book"
      metadata_type: "OperationMetadata"
    };
  }
}
```

However, the linter issues a warning:

```
RPC response type "Operation" should be named "CreateBookResponse" or "BookServiceCreateBookResponse". (RPC_RESPONSE_STANDARD_NAME)
```

------

**Problem Statement** The Google API Design Guide states:

> Individual API methods that might take a significant amount of time to complete **should** return a [`[google.longrunning.Operation](https://github.com/googleapis/googleapis/blob/master/google/longrunning/operations.proto)`](https://github.com/googleapis/googleapis/blob/master/google/longrunning/operations.proto) object instead of the ultimate response message.

In such cases, the `google.longrunning.Operation` response type is mandatory and must not be replaced or renamed. However, the current linter behavior enforces a naming standard that contradicts this guidance, causing warnings for valid implementations.

------

**Proposed Solution** Add a configuration option in `buf.yaml` to explicitly allow the use of `google.longrunning.Operation` as a valid response type. For example:

```yaml
version: v2
name: buf.build/xxxx
lint:
  use:
    - STANDARD
  rpc_allow_google_protobuf_empty_requests: true
  rpc_allow_google_protobuf_empty_responses: true
  rpc_allow_google_longrunning_operations: true  # New option to allow Long Running Operation response type
breaking:
  use:
    - FILE
deps:
  - buf.build/googleapis/googleapis
```

When the `rpc_allow_google_longrunning_operations` option is set to `true`, the linter may:

- Recognize `google.longrunning.Operation` as a valid response type without issuing warnings.
- Ensure this does not conflict with other linting rules or naming conventions. https://github.com/googleapis/googleapis/blob/master/google/longrunning/operations.proto)

Thank you for considering this feature request!
