### ISSUE TITLE
Breaking configuration inside buf.yaml is not respected when used within a module

### ISSUE THREAD

**Issue by ln-12** [bufbuild/buf#3640]
### GitHub repository with your minimal reproducible example (do not leave this field blank or fill out this field with "github.com/bufbuild/buf" or we will automatically close your issue, see the instructions above!)

https://github.com/ln-12/buf_breaking_modules

### Commands

```shell
# Building an image for the current source set
buf build -o buf_master.bin

# Building an image for the changed source set
buf build -o buf_new.bin

# Comparing 
buf breaking buf_new.bin --against buf_master.bin
```

### Output

```shell
main/test.proto:5:1:Previously present field "1" with name "test1" on message "Test" was deleted.
```

### Expected Output

No error message from buf breaking

### Anything else?

I wanted to modify the breaking rules for my project and came across https://github.com/bufbuild/buf/issues/2043. I tried doing it as described there but had no luck. I think the issue is that the breaking rule config is only evaluated when writing it at the top level in the `buf.yaml` file but not when putting it inside a `modules` config. In my actual project I have multiple modules for which I need a different per module rule set. 

In my example, the breaking check fails if I run it as is but succeeds when I remove the comment from [the global breaking config](https://github.com/ln-12/buf_breaking_modules/blob/main/buf.yaml#L17-L23).

**Comment by doriable** [comment]
So what is going on here is that `buf.yaml` module specific configurations apply to the module _at that path._ In the case of your `buf.yaml` configuration:

```
version: v2
modules:
  - path: src/proto
    lint:
      use:
        - STANDARD
      except:
        - PACKAGE_VERSION_SUFFIX
    breaking:
      use:
        - FILE
        - FIELD_NO_DELETE_UNLESS_NUMBER_RESERVED
        - FIELD_NO_DELETE_UNLESS_NAME_RESERVED
      except:
        - FIELD_NO_DELETE
```

This applies to the module located at `src/proto`, either locally or for your Git input. So, when running it against the images, `buf_new.bin` and `buf_master.bin`, only global lint/breaking configurations can be applied.

If you run it against your Git repository, for example, then the module-specific configurations would work:

```
$ buf breaking https://github.com/ln-12/buf_breaking_modules.git --against .
```
