### ISSUE TITLE
--experimental_allow_proto3_optional

### ISSUE THREAD

**Issue by vitruvvius** [bufbuild/buf#366]
```
version: v1beta1
plugins:
  - name: java
    out: ../headers/java
  - name: protoc-gen-grpc-java
    out: ../headers/java
    path: /usr/local/bin/protoc-gen-grpc-java
  - name: protoc-gen-swift
    out: ../headers/swift
    opt: FileNaming=PathToUnderscores
    path: /usr/local/bin/protoc-gen-swift
  - name: protoc-gen-grpc-swift
    out: ../headers/swift
    opt: FileNaming=PathToUnderscores
    path: /usr/local/bin/protoc-gen-grpc-swift
  - name: grpc-ts
    out: ../headers/ts
    opt: import_style=commonjs+dts,mode=grpcweb
    path: /usr/local/bin/protoc-gen-grpc-web
  - name: js
    out: ../headers/ts
    opt: import_style=commonjs,binary
  - name: cpp
    out: '../headers/c++'
  - name: protoc-gen-cpp
    out: '../headers/c++'
```

How does one add --experimental_allow_proto3_optional as an argument to the compiler
