### ISSUE TITLE
Breaking change detector does not ignore deleting files

### ISSUE THREAD

**Issue by r-kells** [bufbuild/buf#37]
Is this expected? If so, what is the recommended way to delete a service?

Config:
```
build:
    roots:
        - proto/
lint:
    use:
        - DEFAULT
        - FILE_LOWER_SNAKE_CASE
breaking:
    use:
        - FILE
    ignore:
        - company/proto/iam/v1test
```

Steps:

- Delete: `company/proto/iam/v1test`. 
- Run: `buf check breaking --against-input .git#branch=master`

Result:

<input>:1:1:Previously present file "company/proto/iam/v1test/service.proto" was deleted.

Expected:

Breaking change detector to pass.
