### ISSUE TITLE
Ruby gRPC generation

### ISSUE THREAD

**Issue by matt-dutchie** [bufbuild/buf#370]
Hi,

I'm attempting to get Buf setup with the Ruby gRPC plugin (https://grpc.io/docs/languages/ruby/quickstart/). I'm using the following buf.gen.yaml:

```
version: v1beta1
plugins:
  - name: ruby
    out: ruby_out
    path: grpc_tools_ruby_protoc
```

See also: https://github.com/grpc/grpc/blob/master/src/ruby/tools/bin/grpc_tools_ruby_protoc

I'm receiving the following error:

```
~ buf generate
Missing input file.
Failure: plugin ruby: exit status 1.
```

I'm assuming this is due to some incompatibility between the execution context in Ruby and what the `buf` command is passing along for the input files.

In the mean time I was trying to unroll `grpc_tools_ruby_protoc` to pass along the plugin executable to protoc directly but was unable to figure out the expected way to do this in `buf.gen.yaml`.

Do you have any recommendations for how I might accomplish this and/or thoughts about how we can adjust either buf or `grpc_tools_ruby_protoc` to work out of the box?

Thanks.

**Comment by bufdev** [comment]
It appears that `grpc_tools_ruby_protoc` is a wrapper around `protoc` and `grpc_plugin_ruby`, the latter of which is the actual plugin binary. This is what you actually want:

```yaml
version: v1beta1
plugins:
  # you need to generate the message definitions as well
  # ruby is a builtin plugin
  - name: ruby
    out: ruby
  # the name doesn't really matter here, but this is the grpc generation
  - name: ruby-grpc
    out: ruby
  # this is the path to the actual ruby grpc plugin, which is part of github.com/grpc/grpc
    path: grpc_ruby_plugin
```

I've tested this and it works, let me know if there's any other issues!

**Comment by matt-dutchie** [comment]
Cool -- I ended up using `grpc_tools_ruby_protoc_plugin` ([found here](https://github.com/grpc/grpc/blob/master/src/ruby/tools/bin/grpc_tools_ruby_protoc_plugin)) --  as the path, which worked. Thanks!

**Comment by gobliggg** [comment]
Hi @matt-dutchie  can you give me an example for the path?

**Comment by johanbrandhorst** [comment]
We recently released support for remote plugins, so you can generate Ruby code with the following (no other tooling than `buf` needed!):

```yaml
version: v1
plugins:
  - remote: buf.build/protocolbuffers/plugins/ruby:v3.19.1-1
    out: ./gen/ruby
  - remote: buf.build/grpc/plugins/ruby:v1.41.1-1
    out: ./gen/ruby
```
