### ISSUE TITLE
buf breaking in pre-commit will set core.bare to 'true' and failed

### ISSUE THREAD

**Issue by Wu-Jiayang** [bufbuild/buf#3752]
### What's up?

When I run `pre-commit run --all-files` or `buf breaking --against "ssh://git@github.com/provistaai/protobuf.git#branch=main"`, It's all right. But when I run `git commit`, It will auto set core.bare to 'true' and failed.

![Image](https://github.com/user-attachments/assets/105d5679-ef86-43e4-9830-9efc2084c7df)

It's a submodule and my `.pre-commit-config.yaml` is:
```yaml
repos:
  - repo: local
    hooks:
      - id: buf-format
        name: Format Protobuf Files
        entry: buf format -w
        language: system
        files: \.proto$
        pass_filenames: false

      - id: buf-breaking
        name: Check Protobuf Breaking Changes
        entry: buf breaking --against "ssh://git@github.com/provistaai/protobuf.git#branch=main"
        language: system
        files: \.proto$
        pass_filenames: false
```
Is that a bug? What should I do? Thx a lot
