### ISSUE TITLE
Setting `go_package_prefix` forces `paths=source_relative` import behavior

### ISSUE THREAD

**Issue by chrismikehogan** [bufbuild/buf#3761]
### GitHub repository with your minimal reproducible example (do not leave this field blank or fill out this field with "github.com/bufbuild/buf" or we will automatically close your issue, see the instructions above!)

https://github.com/chrismikehogan/buf-issue-example/tree/main

### Commands

```shell
# Generates the Golang stubs with the expected final package import part (generated code already checked in)
cd expected
buf generate

# Generates the Golang stubs with the unexpected final package import part (generated code already checked in)
cd unexpected
buf generate
```

### Output

```shell
No error, issue with generated code itself
```

### Expected Output

I would expect the generated code in the `unexpected` directory to have directory structure that aligns with the prefixed `go_package` import paths.

So e.g. I would expect the file structure to be `test/foov1` and not `test/foo/v1`, since the original `go_package` option was `test/foov1`.

The directory structure I expect is found in the `expected` directory, which was generated without the `go_package_prefix`.

### Anything else?

This was discovered when setting up an internal repo that only published proto files as a go module, and that other projects -- some go, some not -- consumed to generate their proto stubs in the consumer application.

For golang consumer applications, I would prefer their generated code honor the package import paths supplied by the producing application (e.g. `/foov1` and not `/foo/v1`). I understand I can achieve this by having the producing application simply own the stub generation and not mess with `go_package_prefix` at all, but my understanding was that this was the intended use case for this config option.

I'm honestly not confident I'm simply mis-using buf for my use case (or that the internal project I'm working on simply has an unconventional proto + golang config that buf or protoc-gen-go does not support), but I've exhausted the combinations of buf and protoc options I'm aware of so wanted to submit a issue to start discussion.

Thanks for your time!

**Comment by emcfarlane** [comment]
The [managed mode docs](https://buf.build/docs/generate/managed-mode/#go) explains and walks through use cases. For your issue you may set the `go_package` to control the package explicitly, using the path to select the files.
```yaml
version: v2
managed:
  enabled: true
  override:
    - file_option: go_package
      value: github.com/chrismikehogan/buf-issue-example/unexpected/test/foov1
      path: test/foo/v1
    - file_option: go_package
      value: github.com/chrismikehogan/buf-issue-example/unexpected/test/pingv1
      path: test/ping/v1
plugins:
  - local: protoc-gen-go
    out: .
    opt: module=github.com/chrismikehogan/buf-issue-example/unexpected
  - local: protoc-gen-go-grpc
    out: .
    opt: module=github.com/chrismikehogan/buf-issue-example/unexpected
```
The `protoc-gen-go` opt is a prefix match to the `value` of the override. The `value` of the override sets the new path for the pkg. Let me know if this solves your issue!
