### ISSUE TITLE
Empty file causes buf generate failure

### ISSUE THREAD

**Issue by rauanmayemir** [bufbuild/buf#3795]
In my buf module, I have a file `acme/v1/stub.proto`:

```
syntax = "proto3";

package acme.v1;

import "google/rpc/code.proto";
import "google/rpc/error_details.proto";
import "google/rpc/status.proto";
``` 

Buf cli will crash on it with `Failure: missing "acme/v1/stub.proto"`. I'm assuming this is because there are no types in there.

**Comment by doriable** [comment]
Using `buf` version `v1.53.0`, I created a module with the file contents you have above:

```
$ tree .
.
├── buf.gen.yaml
├── buf.lock
├── buf.yaml
└── proto
    └── stub.proto

$ cat proto/stub.proto
syntax = "proto3";

package acme.v1;

import "google/rpc/code.proto";
import "google/rpc/error_details.proto";
import "google/rpc/status.proto";
```

My `buf.yaml` and `buf.gen.yaml`:

```
$ cat buf.yaml
version: v2
deps:
  - buf.build/googleapis/googleapis

$ cat buf.gen.yaml
version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: company.com/foo/bar
plugins:
  - remote: buf.build/protocolbuffers/go
    out: gen/
```

`buf generate` succeeds with generated code for me. Could you provide a repro for the issue that you are seeing?

**Comment by rauanmayemir** [comment]
Hm, both nix and brew have only 1.52.1.
Thank you, I’ll upgrade and verify.

**Comment by rauanmayemir** [comment]
@doriable I found the reason. It happens if a gen spec has `exclude_types`:

```
plugins:
  - remote: buf.build/protocolbuffers/go
    out: gen/
    exclude_types:
      - buf.validate
      - google.api.field_behavior
      - google.api.http
      - gnostic.openapi.v3
```
