### ISSUE TITLE
Buf CLI hangs indefintely

### ISSUE THREAD

**Issue by antspy** [bufbuild/buf#3847]
Hi, 

I am having problem with my `buf cli`. 
I have the following `buf.yaml` file: 

```yaml
version: v2
modules:
  - path: src
lint:
  use:
    - STANDARD
```

This works as expect, and running `buf lint src/foo/bar.proto` works correctly. 
However, I want the 'base' dir to be the workspace root dir, not `src` [0]. So I modified as such: 

```yaml
version: v2
modules:
  - path: .
lint:
  use:
    - STANDARD
```

Now calling `buf lint src/foo/bar.proto` hangs forever (5min +). My guess is that `buf` is trying to scan every folder underneath the root, which contains things like node_modules, python virtual environments, bazel output dir, etc. etc. Ok, so I tried using the `includes` property: 

```yaml
version: v2
modules:
  - path: .
     includes:
       - src 
lint:
  use:
    - STANDARD
```

This has two problems: 
1. The `yaml` configuration file does not recognize the `includes` property (`excludes` is available, but not `includes`, for some reason). This might be a red herring, as it might simply be the editor not recognizing the right format for the `yaml` file. 
2. The bigger issue is that `buf lint src/foo/bar.proto` hangs once again. It looks like the `includes` property is being ignored. 

Do you have any ideas what could be happening, or how could I debug further? 

Thanks! 

[0] I am using bazel, and bazel understands imports as starting from the root dir. So if I have to `import src/foo/bar2.proto`, I need to use `src` in the path. But `buf` would not recognize that path if I set `path: src` in the `buf.yaml` config.
