### ISSUE TITLE
C# namespace unidiomatic in managed mode

### ISSUE THREAD

**Issue by seniorquico** [bufbuild/buf#445]
I have a proto file that contains the following:

```proto
package company.platform.service_client.v1;
```

When I use protoc on the command line or buf with the following `buf.gen.yaml`:

```yaml
version: v1
plugins:
  - name: csharp
    out: out/csharp
```

... the C# namespace is generated as:

```cs
namespace Company.Platform.ServiceClient.V1 {
```

However, when I use buf with "Managed Mode" enabled:

```yaml
version: v1
managed:
  enabled: true
plugins:
  - name: csharp
    out: out/csharp
```

... the C# namespace is generated as:

```cs
namespace Company.Platform.Service_client.V1 {
```

This was unexpected. Is there a way to get the C# namespace with the PascalCase naming convention when using "Managed Mode"?
