### ISSUE TITLE
Managed Mode configuration

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#465]
There have been several feature requests for extending the [Managed Mode](https://docs.buf.build/generate/managed-mode) configuration options so that users can configure how each file option behaves (similar to the [`go_package_prefix`](https://docs.buf.build/generate/managed-mode#go_package_prefix) option).

We've discussed this at length before, and consciously decided to keep it strict and opinionated for the time being. However, we can adapt the `buf.gen.yaml` in a backwards-compatible manner to accommodate these use cases if we ever decide to.

For example, we can adopt the same style that the `lint` and `breaking` keys use (i.e. add rule and category IDs for each option):

```yaml
# buf.gen.yaml
version: v1
managed:
  use:
    - DEFAULT
  except:
    - JAVA_MULTIPLE_FILES
  ignore:
    - foo/bar.proto
  ignore_only:
    GO_PACKAGE:
      - baz/qux.proto
  java_package_prefix: "org"
```

> In this new model, the `enabled: true` value could be implicitly set if `managed.use` is non-empty.

There have also been conversations about whether we should move **Managed Mode** configuration to a separate file (e.g. `buf.managed.yaml`) so that it can be more naturally applied to other commands like `buf build`. In this world, we would need to be careful that `buf` remains ergonomic and intuitive to use.

**Comment by odsod** [comment]
Out of everything mentioned in this issue, `java_package_prefix: "org"` would be the most impactful for us, with respect to enabling migration to managed mode without breaking changes to existing generated Java code (and Java artifacts).

**Comment by amckinney** [comment]
We've decided to defer the `use`, `except`, `ignore`, and `ignore_only` approach until it's absolutely necessary (we're not yet convinced it ever will be). **Managed Mode** encourages users to consciously control what file options are set, rather than deferring to their dependencies' source.

Users can `override` file option values for specific files (as described in https://github.com/bufbuild/buf/issues/471). This looks like the following:

```yaml
# buf.gen.yaml
version: v1
managed:
  enabled: true
  override:
    JAVA_OUTER_CLASSNAME:
      google/type/latlng.proto: com.google.type.LatLngProto
```
