### ISSUE TITLE
Java managed mode and google.type.LatLng

### ISSUE THREAD

**Issue by odsod** [bufbuild/buf#471]
When turning on managed mode for Java, with a module that depends on buf.build/googleapis/googleapis and a file that imports [google/type/latlng.proto](https://github.com/googleapis/googleapis/blob/master/google/type/latlng.proto), there is a diff in the generated code causing a `cannot find symbol` error for `com.google.type.LatLngProto`.

When inspecting the generated code, the symbol has been generated as `com.google.type.LatlngProto`, most likely since the file is called `latlng.proto` and not `lat_lng.proto`:

```java
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.type.LatlngProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
        });
```

There does not seem to be any managed mode options for Java currently to override this to patch this.

**Comment by amckinney** [comment]
This one is unfortunate - as you've found, Google's `google/type/latlng.proto` clearly doesn't conform to the standard mapping that **Managed Mode** enforces. In this case, we won't be able to override exactly _how_ the `java_outer_classname` option transforms the filename into the class name (since it would affect all other files found in the same `buf generate` invocation).

Instead, I think we'll need to expose a configuration similar to the one described in #465. I imagine we'll have something along the lines of the following:

```yaml
# buf.gen.yaml
version: v1
managed:
  use:
    - DEFAULT
  ignore_only:
    JAVA_OUTER_CLASSNAME:
      - google/type/latlng.proto
```

Alternatively, we _might_ consider an `override` model, so that users can explicitly override individual file options on a per-file basis:

```
# buf.gen.yaml
version: v1
managed:
  use:
    - DEFAULT
  override:
    JAVA_OUTER_CLASSNAME:
      google/type/latlng.proto: com.google.type.LatLngProto
```

I'm not yet convinced that we should support the `override` in general though, so I'd prefer to approach this so that it's symmetrical with the `lint` and `breaking` configuration shapes. Regardless, I'll update this issue once we move forward with a solution to your problem.

**Comment by odsod** [comment]
@amckinney Sounds good, thanks for looking into this! https://github.com/bufbuild/buf/pull/473 and a way forward here will be what we need to proceed with adoption of managed mode for Java! :sunglasses:

**Comment by amckinney** [comment]
The `override` approach was released in [v0.55.0](https://github.com/bufbuild/buf/releases/tag/v0.55.0) - give it a shot and feel free to reopen if it doesn't fit your requirements.

For example,

```yaml
# buf.gen.yaml
version: v1
managed:
  enabled: true
  override:
    JAVA_OUTER_CLASSNAME:
      google/type/latlng.proto: com.google.type.LatLngProto
```
