### ISSUE TITLE
Prepend imported module file paths with module path in errors

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#490]
```
$ buf check breaking --against-input 0.0.0.0:3000/foo/bar/v1:b1-659yVmM4Ut_GZa6Nr-rJW2jT0hmbupCPNFyYr5R28aU=
buf/image/v1/image.proto exists in multiple locations: proto/buf/image/v1/image.proto buf/image/v1/image.proto
```

This actually isn't a bug - this was due to having buf.yaml for bufbuild rely on a pushed module of itself, so the file was in two locations. The error message was just crazy confusing.

This likely gets to my initial intent of external paths: prepend file paths for modules with the module path.

**Comment by TheDrewscriver** [comment]
I would say this is a major issue. This is the problem I am facing:

Even thought the buf.yaml only includes this:
deps:
  - buf.build/beta/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway

When I run 
```
buf mod update -v
DEBUG	get_config	{"duration": "459.9µs"}
DEBUG	grpcclient	dial	{"address": "dns:///api.buf.build"}
DEBUG	buf.alpha.registry.v1alpha1.ResolveService.GetModulePins	{"duration": "624.824732ms", "Client": true, "FailFast": true}
DEBUG	command	{"duration": "730.86471ms"}
```
It adds dependencies for both buf.build/beta and buf.build/googleapis

Contents on buf.lock:
```

# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: beta
    repository: googleapis
    branch: main
    commit: ac0d624de3f746c3b8ef55c74b6f5244
    digest: b1-GubXb4hZ56wTohZYDL-Muute9Jxx8J4TtIYucS30TBM=
    create_time: 2021-08-12T19:53:55.128813Z
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    branch: main
    commit: 6358935a97044c1494fe13d369ac2f3b
    digest: b1-4hxgpEmLuajuxqkZd7NMVnKipt3zqnXaTHsBEKtUOsM=
    create_time: 2021-08-13T15:04:04.653816Z
  - remote: buf.build
    owner: grpc-ecosystem
    repository: grpc-gateway
    branch: main
    commit: d1922677830c448eb65ec590f3abc734
    digest: b1-zmmsl0XlsSF4_BhZe7w9NMdImBCRtMSn68rmn9H1faQ=
    create_time: 2021-08-17T02:45:07.151993Z
```

```
buf lint
threeDS-risk-api.proto:7:8:google/api/annotations.proto exists in multiple locations: google/api/annotations.proto google/api/annotations.proto
```

Shouldn't we only be downloading the referenced dependencies, and not additional dependencies resulting in these kinda errors?
