### ISSUE TITLE
Template setup override

### ISSUE THREAD

**Issue by khorevaa** [bufbuild/buf#504]
Need setup override like this

```yaml
---
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/v8platform/protos/gen
    except:
      - buf.build/googleapis/googleapis
    override:
      "buf.build/v8platform/rasapis": "go.buf.build/v8platform/go-gen-ras/v8platform/rasapis"
      "buf.build/v8platform/serializeapis": "go.buf.build/v8platform/go-gen-ras/v8platform/serializeapis"
      "buf.build/v8platform/encodingapis": "go.buf.build/v8platform/go-gen-ras/v8platform/encodingapis"

plugins:
  - name: go
    out: ./gen
    opt: paths=source_relative
  - name: go-grpc
    out: ./gen
    opt: paths=source_relative,require_unimplemented_servers=false
  - name: grpc-gateway
    out: ./gen
    opt:
      - paths=source_relative
      - generate_unbound_methods=false
      - grpc_api_configuration=rasserverapis/grpc-rest-bindings.yml
```

This repository generate with plugins:  grpc,  grpc-gateway
Deps repository generate with plugins: go-gen-ras

**Comment by johanbrandhorst** [comment]
Hi, I'm not sure I follow exactly what you mean here. Could you elaborate on exactly what sort of option you want to add? It looks like you want to use the BSR Go module proxy mixed with local generation. Is your intention to replace some imported modules with those generated by the BSR Go module proxy?

**Comment by khorevaa** [comment]
I have 3 modules with apis with dependencies on each other.

1. serializeapies - need to build with the go-gen-ras plugin. 
2. rasapies -need to build with the go-gen-ras plugin. Depends on serializeapies 
3. rasserviceapies - need to build with the go, grpc, grpc-gateway plugins, but without the go-gen-ras plugin, while it depends on the serializeapies and rasapies modules

When i use BSR Go module proxy for rasserviceapies (template name go-grpc)  its generate broken depends for modules rasapies and  serializeapies without builded  go-gen-ras plugin.

Need override deps like this 
- "go.buf.build/v8platform/go-grpc/v8platform/rasapis": "go.buf.build/v8platform/go-gen-ras/v8platform/rasapis"
- "go.buf.build/v8platform/go-grpcv8platform/serializeapis": "go.buf.build/v8platform/go-gen-ras/v8platform/serializeapis"
or 
- "buf.build/v8platform/rasapis": "go.buf.build/v8platform/go-gen-ras/v8platform/rasapis" 
- "buf.build/v8platform/serializeapis": "go.buf.build/v8platform/go-gen-ras/v8platform/serializeapis"

**Comment by amckinney** [comment]
I see what you're trying to do now, thanks for all the additional context.

As you've already found, the template you use for a given module will be applied to **all of the module's dependencies**. In this case, the `rasserviceapies` module depends on `rasapies` and `serializeapies`, so the `go-grpc` template is applied to each module.

This is actually a constraint with respect to the Go module proxy. The URLs we create (e.g. `go.buf.build/v8platform/go-grpc/v8platform/rasserviceapies`) _must_ produce reproducible results, so you can't modify your dependencies' import paths used in the generated code for the same URL.

Plus, there isn't a good way for us to let you select exactly which dependencies should use which import paths. You would need to create a different URL for each combination of "this dependency uses THAT template, and this other dependency uses THIS one”, etc. Remote templates are meant to be agnostic to their module input - embedding this information would require that templates are built with a specific module in mind.

What you've found in the `buf.gen.yaml` `override` configuration is purely a local generation concern.

## Solution

1. You can use a `buf.gen.yaml` to generate your `rasserviceapies` module locally (overriding its dependencies to use the `go.buf.build` paths like you have above), but you won't be able to depend on this particular result of `rasserviceapies` as a `go.buf.build` resource this way - the generated code will only be available locally. It looks like this is already what you have in your snippet above.

2. We've recently rolled out a feature that will let you configure a `buf.gen.yaml` that uses _both_ local and remote plugins. In your case, you could create a `buf.gen.yaml` that references `buf.build/library/plugins/go`, `buf.build/library/plugins/go-grpc`, etc. Note that if you omit the `:<$version>` suffix, the latest version of the plugin is used.

```yaml
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/v8platform/protos/gen
    except:
      - buf.build/googleapis/googleapis
    override:
      buf.build/v8platform/rasapis: go.buf.build/v8platform/go-gen-ras/v8platform/rasapis
      buf.build/v8platform/serializeapis: go.buf.build/v8platform/go-gen-ras/v8platform/serializeapis
      buf.build/v8platform/encodingapis: go.buf.build/v8platform/go-gen-ras/v8platform/encodingapis

plugins:
  - remote: buf.build/library/plugins/go
    out: ./gen
    opt: paths=source_relative
  - remote: buf.build/library/plugins/go-grpc
    out: ./gen
    opt: paths=source_relative,require_unimplemented_servers=false
  - name: grpc-gateway
    out: ./gen
    opt:
      - paths=source_relative
      - generate_unbound_methods=false
      - grpc_api_configuration=rasserverapis/grpc-rest-bindings.yml
```

Given that you rely on local configuration for the `grpc-gateway` plugin option, I've left that to be executed locally as-is. With this you would rely on plugins stored in the BSR, but use would generate the code locally.

Please let us know if this helps!
