### ISSUE TITLE
Multi configs for buf generate

### ISSUE THREAD

**Issue by khorevaa** [bufbuild/buf#510]
A config file filled with multiple configs, which are separated by "---".

```yaml
---

version: v1
scopes:
    - ./rasserviceapis
managed:
  enabled: true
  go_package_prefix:
    default: github.com/v8platform/protos/gen
    except:
      - buf.build/googleapis/googleapis
    override:
      "buf.build/v8platform/rasapis": "go.buf.build/v8platform/go-gen-ras/v8platform/rasapis"
      "buf.build/v8platform/serializeapis": "go.buf.build/v8platform/go-gen-ras/v8platform/serializeapis"
      "buf.build/v8platform/encodingapis": "go.buf.build/v8platform/go-gen-ras/v8platform/encodingapis"
plugins:
  - name: go
    out: ./gen
    opt: paths=source_relative
  - name: go-grpc
    out: ./gen
    opt: paths=source_relative,require_unimplemented_servers=false 
---
version: v1
scopes:
    - ./rasapis
managed:
  enabled: true
  go_package_prefix:
    default: github.com/v8platform/protos/gen
    except:
      - buf.build/googleapis/googleapis
      - buf.build/v8platform/encodingapis

plugins:
  - name: go
    out: ./gen
    opt: paths=source_relative
  - name: go-ras
    opt: paths=source_relative
    out: ./gen

```

`scope` - path to root of proto directory
