### ISSUE TITLE
`buf ls-files` times out, config file roots doesn't help

### ISSUE THREAD

**Issue by srenatus** [bufbuild/buf#59]
In https://github.com/chef/automate, I've been wanting to `buf ls-files`. 

Running `buf ls-files` without a config in the top-level of the checkout, it'll run into a context timeout. (If this isn't happening on a fresh checkout, it'll have something to do with various node_modules and similar folders popping up as one works on it...)

Trying to create a buf.yaml, I've started with
```yaml
build:
  roots:
    - api
    - vendor/github.com/envoyproxy/protoc-gen-validate
    - vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis
```

....but then I'm running into errors like these,

```
api/interservice/teams/teams.proto:5:8:api/api/external/common/version/version.proto: does not exist
```
because the import statements expect top-level as an import path. So, `api/interservice/teams/teams.proto` imports `api/external/common/version/version.proto`.

It's clear that rearranging the proto files' import paths to not start with `api/` would fix the problem -- what I'm wondering about is if there's an easier way to fix this.

**Comment by bufdev** [comment]
There's a couple things you can do on the timeouts:

- Increase the timeout :-) Use `buf ls-files --timeout 2m` for example.
- Add directories to `build.excludes` https://buf.build/docs/build-configuration#excludes

On the import paths, that's actually by design - see https://buf.build/docs/build-configuration#root-requirements - what you'd want to do instinctively is 👍 

```yaml
# THIS IS AN EXAMPLE THAT IS INVALID
build:
  roots:
    - .
    - vendor/github.com/envoyproxy/protoc-gen-validate
    - vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis
```

However, the `vendor` roots are sub-directories of the `.` root, which is not allowed. You explicitly *should* update your imports, and do `protoc -I api ...` for example.
