### ISSUE TITLE
--include-imports is not respected for remote plugins

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#606]
The current remote generator does not expose a way to toggle whether or not to [include imports](https://github.com/bufbuild/core/blob/573cb12b47b21fc1096342bf3925b5410bcf57d5/internal/bufd/bufdgenerate/remote_generator.go#L64). So when we run `buf generate --include-imports` with a `remote` plugin configured, the flag is not respected and imports and not included by default.

For example,

```yaml
# buf.gen.yaml
version: v1
plugins:
  - remote: buf.build/library/plugins/go
    out: gen/proto/go
```

We need to either:
1. Expose a field in the `Generate{Plugins,Files,Template}` RPCs for `IncludeImports`.
2. Find another way to convey whether or not the `Image` should include imports.
