### ISSUE TITLE
Outdated deps warning can be misleading when run from workspace directory

### ISSUE THREAD

**Issue by johanbrandhorst** [bufbuild/buf#623]
Steps to reproduce:
1. Create a new workspace:
   ```yaml
   version: v1
   directories:
     - proto
   ```
1. Create a new module with at least one dependency in the `proto` directory:
   ```yaml
   version: v1
   name: buf.build/whatever/whatever
   deps:
     - buf.build/googleapis/googleapis
   lint:
     use:
       - DEFAULT
   breaking:
     use:
       - FILE
   ```
1. Run `buf lint` from the workspace directory:
   ```shell
   $ buf lint
   WARN    Specified deps are not covered in your buf.lock, run "buf mod update":
           - buf.build/googleapis/googleapis
   Failure: no .proto target files found # ignore this part
   ```

The misleading instructions here being that the user should run `buf mod update` inside the workspace directory, when it's really needed inside the `proto` directory.
