### ISSUE TITLE
"proto/proto" prefix in bufgen

### ISSUE THREAD

**Issue by alcidesmig** [bufbuild/buf#660]
When generating code for protobuf [+grpc] I'm getting one strange behavior.
My environment is dumped [here](https://github.com/alcidesmig/gw-grpc-json/releases/tag/buf-prefix-bug), and in resume is:
```yaml
#buf.gen.yaml
version: v1
plugins:
  - name: go
    out: proto
    opt: paths=source_relative
  - name: go-grpc
    out: proto
    opt: paths=source_relative,require_unimplemented_servers=false
  - name: grpc-gateway
    out: proto
    opt: paths=source_relative
```
```yaml
#buf.yaml
version: v1
name: buf.build/alcidesmig/go-grpc-poc
deps:
  - buf.build/googleapis/googleapis
```
And, when generating code with `buf generate -o gen/hello/. --path proto/hello.proto`, I got the output in this tree:
```
├── gen
│   └── hello
│       └── proto
│           └── proto
│               ├── hello_grpc.pb.go
│               ├── hello.pb.go
│               └── hello.pb.gw.go
```
My question is: is this `proto/proto` prefix expected? I couldn't validate this in current doc.
