### ISSUE TITLE
 Mismatched module digest

### ISSUE THREAD

**Issue by sashayakovtseva** [bufbuild/buf#661]
Hello!

I have `buf.build/beta/googleapis` in my dependencies, here is the `buf.lock` contents:
```
# Generated by buf. DO NOT EDIT.
deps:
  - remote: buf.build
    owner: beta
    repository: googleapis
    branch: main
    commit: ac0d624de3f746c3b8ef55c74b6f5244
    digest: b1-tcgu4ZoKWxrUlOynEGw-kV9iaOuDwRtJ4_17qAsU_RI=
    create_time: 2021-08-12T19:53:55.128813Z
  - remote: buf.build
    owner: beta
    repository: protoc-gen-validate
    branch: main
    commit: 82388a0a0cb04e98a203f95dfed5e84b
    digest: b1-lYgUMN58PxyCwvfQoopp40AJ-oHHjWXAzksF7v9U-U4=
    create_time: 2021-06-21T22:00:30.152545Z
```

From time to time, when I run `buf build` it updates googleapis digest to `b1-tcgu4ZoKWxrUlOynEGw-kV9iaOuDwRtJ4_17qAsU_RI=` and then fails with error:
```
Failed to "build": mismatched module digest for "buf.build/beta/googleapis": expected: "b1-GubXb4hZ56wTohZYDL-Muute9Jxx8J4TtIYucS30TBM=" got: "b1-tcgu4ZoKWxrUlOynEGw-kV9iaOuDwRtJ4_17qAsU_RI=".
```

Is there a way to fix this non deterministic behaviour? I can't quite understand, why sometimes it works fine and sometimes fails.
