### ISSUE TITLE
One plugin with multiple outputs

### ISSUE THREAD

**Issue by eljoth** [bufbuild/buf#680]
Hey there,
I am trying to use a plugin with multiple outputs to generate a client stub and I can't figure out the documentation.

I want to use the protoc-gen-ts plugin by improbable-eng.

```bash
protoc --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" --js_out="import_style=commonjs,binary:${OUT_DIR}" --ts_out="service=grpc-web:${OUT_DIR}" myproto.proto
```

How would the buf.gen.yaml look for this protoc command ?

I've already tried 
```yaml - name: ts
    path: bin/node/node_modules/.bin/protoc-gen-ts
    out: pkg/client/ts
    opt:
      - paths=source_relative
      - js_out="import_style=commonjs,binary:pkg/client/ts"
      - ts_out="service=grpc-web:pkg/client/ts"
```

but this doesn't give the expected output since only the d.ts file is generated and the .js file is missing
