### ISSUE TITLE
how can i ignore version suffix in codegen

### ISSUE THREAD

**Issue by Huangsir** [bufbuild/buf#731]
is there any config that i can use to ignore adding version suffix to the go package?

https://docs.buf.build/configuration/v1/buf-gen-yaml

![image](https://user-images.githubusercontent.com/3870517/141963621-fb58799b-cda2-4e63-a7ad-871ab56f3710.png)

e.g: 

```protobuf
syntax = "proto3";

package acme.weather.v1;

option go_package = "github.com/acme/weather/gen/proto/go/acme/weather/v1;weather";
```

want: weather  
not: weatherv1

**Comment by mfridman** [comment]
In your `buf.gen.yaml` file, do you have `managed.enabled: true` ?

---

With the following `buf.gen.yaml`:

(I'm using a remote plugin here, but it'll be effectively the same as a local one)

```yaml
version: v1
plugins:
  - remote: buf.build/library/plugins/go:v1.27.1-1
    out: internal/gen
    opt: paths=source_relative
```

and this proto:

```proto
syntax = "proto3";

package weather.v1;

option go_package = "github.com/acme/weather/gen/proto/go/acme/weather/v1;weather";

service WeatherService {
    rpc GetWeather(GetWeatherRequest) returns (GetWeatherResponse);
}

message GetWeatherRequest {
    string city_name = 1;
}

message GetWeatherResponse {
    int32 temperature = 1;
}
```

I get the following import path following code generation (`buf generate`):

```
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: proto/weather/v1/weather.proto

package weather
```

**Comment by Huangsir** [comment]
`buf.gen.yaml` looks like

```yaml
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/acme/weather/gen/proto
    except:
      - buf.build/googleapis/googleapis
```

and go_package is relate path in fact 

```protobuf
syntax = "proto3";

package weather.v1;

option go_package = "./go/acme/weather/v1;weather";

service WeatherService {
    rpc GetWeather(GetWeatherRequest) returns (GetWeatherResponse);
}

message GetWeatherRequest {
    string city_name = 1;
}

message GetWeatherResponse {
    int32 temperature = 1;
}
```

if `go_package_prefix` in config that the package name in  generated go file will become weatherv1

**Comment by amckinney** [comment]
This is the opinion that Managed Mode enforces - we currently don't expose a way to modify the version suffix behavior in general, nor do we want to. If anything, we would choose not to do anything with the `;<package_name>` option and lean on the default behavior, but you would end up having a ton of `v1` package conflicts and painfully have to import alias each one, just like the comment describes.

If you feel strongly about overriding a specific file's `go_package` value, check out the `override` option [here](https://docs.buf.build/generate/managed-mode#override-1). Although we _don't_ recommend it for your use case, you could write something along the lines of the following:

```
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/acme/weather/gen/proto
    except:
      - buf.build/googleapis/googleapis
  override:
    GO_PACKAGE:
      acme/weather/v1/weather.proto: "github.com/acme/weather/gen/proto/go/acme/weather/v1;weather"
```

Again, we recommend that you conform to the `weatherv1` convention since this is standard across all other Managed Mode users, but hopefully the above is sufficient for you otherwise.
