### ISSUE TITLE
Seems like combining the more restrictive category with rules from another less restrictive category isn't working

### ISSUE THREAD

**Issue by Umriyaev** [bufbuild/buf#732]
Hello,

Seems like combining more restrictive categories with rules from less restrictive categories isn't working as expected.

We have the following buf.yaml:

```
version: v1
breaking:
  use:
    - PACKAGE
    - FIELD_WIRE_COMPATIBLE_TYPE
  except:
    - FIELD_NO_DELETE
```

in message.proto in master we have:
```
syntax = "proto3";

package awesome_package;

message AwesomeMessage {
    bool awesome_field = 1;
}
```

we are changing the type of awesome_field to int32:
```
syntax = "proto3";

package awesome_package;

message AwesomeMessage {
    int32 awesome_field = 1;
}
```

however, breaking changes check isn't allowing this change even though we added `FIELD_WIRE_COMPATIBLE_TYPE` to the rules.

we are using v0.56.0 of bufbuild
we are running the breaking changes check as following:

```
docker pull bufbuild/buf:0.56.0
docker run --volume "$(pwd):/workspace" --workdir /workspace bufbuild/buf:0.56.0 breaking --against image.bin --debug
```

and we build the image in master as following:
```
docker pull bufbuild/buf:0.56.0
docker run --volume "$(pwd):/workspace" --workdir /workspace bufbuild/buf:0.56.0 build -o image.bin
```

**Comment by cyinma** [comment]
Hi @Umriyaev , thanks for your issue.

The rules in the `breaking.use` are an AND relationship, which means that the changes need to pass all of the rules mentioned in the `breaking.use` to pass the breaking changes check.

If you want to use a less restrictive rule, you will also need to put the original rule in the `ignore_only` / `except` part, in your case, the original rule should be `FIELD_SAME_TYPE`, so that it will use `FIELD_WIRE_COMPATIBLE_TYPE` for your type check in breaking changes check.

To play safe, you can use `ignore_only` to apply this only to the `message.proto`, so your `buf.yaml` will be like this:

```
version: v1
breaking:
  use:
    - PACKAGE
    - FIELD_WIRE_COMPATIBLE_TYPE
  ignore_only:
    FIELD_SAME_TYPE:
      - message.proto
  except:
    - FIELD_NO_DELETE
```

If you are sure that you want to apply this to all proto files, you can put it in `except`, and your `buf.yaml` will be like this:

```
version: v1
breaking:
  use:
    - PACKAGE
    - FIELD_WIRE_COMPATIBLE_TYPE
  except:
    - FIELD_NO_DELETE
    - FIELD_SAME_TYPE
```

I have tried both of them in local and worked as expected, if you have any questions please let us know!
