### ISSUE TITLE
How to generate API reference from `.proto`?

### ISSUE THREAD

**Issue by kei6u** [bufbuild/buf#741]
I would like to generate API reference from `.proto` files by using `buf` like https://github.com/pseudomuto/protoc-gen-doc.
Are there ways to do it?

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! Yes, you can use this plugin with `buf`! If you want to get an introduction to using `buf` (including how to generate code using plugins like `protoc-gen-doc`), I would recommend going through the tour in our docs: https://docs.buf.build/tour/introduction.

If you're already a bit familiar with `buf`, what you'll need to do to use `protoc-gen-doc` largely comes down to:

1. Install the plugin locally. The installation instructions given by the author suggest installing via the Go tool:
   ```
   $ go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
   ```
   Running this command will download and compile the plugin for your local system and put it in GOPATH/bin/protoc-gen-doc. You'll need to ensure this path is available on your $PATH for the next step, so you may want to run something like:
   ```
   $ export PATH=$PATH:(go env GOPATH)/bin
   ```
2. Define a `buf.gen.yaml`. For your use case, it shouldn't have to be more complicated than this:
   ```yaml
   version: v1
   plugins:
     - name: protoc-gen-doc # buf will look for this binary on the $PATH
       # path: /path/to/protoc-gen-doc # Optionally, instead of updating your $PATH in the previous step, you can specify the path to the binary explicitly here.
       out: ./gen/doc
   ```
3. Run `buf generate` providing your sources as the input. It defaults to the current directory, so if you have an existing [protobuf module](https://docs.buf.build/bsr/overview#module), you can simply run
   ```
   $ buf generate
   ```
   from the root of your module.

**Comment by bufdev** [comment]
Another option is to use the Buf Schema Registry's built-in documentation generator by the way! https://docs.buf.build/bsr/documentation

**Comment by kei6u** [comment]
@johanbrandhorst 

Thank you!

I am trying as following your instruction but, I've got the error message even though `protoc-gen-doc` exists under `~/go/bin`.

```
Failure: plugin protoc-gen-doc: could not find protoc plugin for name protoc-gen-doc
```

I've also executed `buf mod update`.

My `buf.gen.yaml` is like this.

```yaml
version: v1
plugins:
  - name: go
    out: .
    opt: paths=source_relative
  - name: go-grpc
    out: .
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false
  - name: grpc-gateway
    out: .
    opt: paths=source_relative
  - name: protoc-gen-doc
    out: .
```

Do  you have any ideas?

**Comment by johanbrandhorst** [comment]
What does `which protoc-gen-doc` show? If it shows nothing, you may have missed the step about setting your `PATH`:

```
export PATH=$PATH:(go env GOPATH)/bin
```

If you need more help, can you reach out on our Slack? https://join.slack.com/t/bufbuild/shared_invite/zt-f5k547ki-VDs_iC4TblNCu7ubhRD17w. This issue tracker isn't great for quick troubleshooting.

**Comment by kei6u** [comment]
oh, I should've provided it, too.

This is exactly same as `$GOPATH/bin/protoc-gen-doc`.

```shell
which protoc-gen-doc
/Users/keisukeumegaki/go/bin/protoc-gen-doc
```

Besides, I've joined the Slack channel.

**Comment by amckinney** [comment]
Replied in Slack, but including here for posterity - your `buf.gen.yaml` should reference `doc` (not the `protoc-gen-` prefix).

```yaml
version: v1
plugins:
  - name: go
    out: .
    opt: paths=source_relative
  - name: go-grpc
    out: .
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false
  - name: grpc-gateway
    out: .
    opt: paths=source_relative
  - name: doc
    out: .
```

**Comment by kei6u** [comment]
It works! Thanks:pray:

**Comment by houseofmercy-github** [comment]
I [had some trouble](https://github.com/pseudomuto/protoc-gen-doc/pull/450#issuecomment-1208562697) getting the `opt:` setting right with the `protoc-gen-doc` plugin.  
For the benefit of anyone else who finds there way here this is what worked for me:
  
```
version: v1
plugins:
  - name: doc
    out: ./gen/doc
    opt: html,index.html,source_relative
```
