### ISSUE TITLE
Cannot create separate client/server implementations of packages in C#

### ISSUE THREAD

**Issue by shoneefd** [bufbuild/buf#774]
Real quick, the relevant `buf.gen.yaml`:

```
plugins:
  - name: csharp
    out: csharp-abstractions
  - name: grpc-csharp
    out: csharp-client
    opt:
      - no_server
  - name: grpc-csharp
    out: csharp-server
    opt:
      - no_client
```

What I'm trying to do here is create three separate NuGet packages for internal use. The first, output to the csharp-abstractions directory, contains the generated contracts. The second, output to the csharp-client directory, contains the generated client. The third, output to the csharp-server directory, contains the generated server stub. The NuGet packages are defined such that the csharp-client & csharp-server packages depend on the csharp-abstractions package. Doing this directly with the C# tooling works, and doing the equivalent with protoc from the command line works.

However, when I attempt to use buf with this .yaml, I get this error message: `Failure: file "SaladBowlServiceGrpc.cs" was generated multiple times: once by plugin "grpc-csharp" and again by plugin "grpc-csharp"`

Right now, I can do a workaround either by using the CLI or by commenting out either the serverside or clientside portion of the .yaml, running buf, and then swapping the commented-out portion of the file to generate the other file.

We need both of these files to refer to the same service and exist in the same C# namespace. I do not need them to have the same filename or classname.

Is there a workaround for this issue? I'm pretty sure this is a reasonable use case for C#. I saw what looked like a relevant issue [here](https://github.com/bufbuild/buf/issues/760), but it's not the same issue.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. We'll need to do a bit more investigation here, I would expect this to work since the output directories are different, so I'm a bit surprised. In the meantime, can you share what your `protoc` invocation looks like? Worst case, for now, you should be able to use `buf protoc` with your old `protoc` command.

**Comment by amckinney** [comment]
I was able to reproduce this with other plugin inputs, too. For example, the following `buf.gen.yaml` fails, whereas the equivalent command for `protoc` succeeds:

```yaml
version: v1
plugins:
  - name: cpp
    out: foo
 - name: cpp
    out: bar
```

```sh
$ protoc $(buf ls-files) --cpp_out=foo --cpp_out=bar
```

The fix looks fairly simple - we don't account for the `out` directory in our validation to prevent duplicate files [here](https://github.com/bufbuild/buf/blob/0786cea8690ed81cdd1f5b31b9b5c0529ffdab74/private/pkg/app/appproto/appproto.go#L204), but we have access to that information in the layer above. We'll try to get a fix out soon!

Thanks again for the issue @shoneefd!

**Comment by amckinney** [comment]
I should also mention that the workaround (in the meantime) is to define two separate `buf.gen.yaml` templates, e.g. `buf.gen.client.yaml` and `buf.gen.server.yaml` and invoke `buf` twice:

```yaml
# buf.gen.server.yaml
version: v1
plugins:
  - name: csharp
    out: csharp-abstractions
  - name: grpc-csharp
    out: csharp-server
    opt:
      - no_client
```

```yaml
# buf.gen.client.yaml
version: v1
plugins:
  - name: grpc-csharp
    out: csharp-client
    opt:
      - no_server
```

```sh
$ buf generate --template buf.gen.client.yaml
$ buf generate --template buf.gen.server.yaml
```

> The `protoc-gen-csharp` plugin was arbitrarily assigned to `buf.gen.server.yaml`. You could have yet another `buf.gen.yaml` for this, or it could also exist in `buf.gen.client.yaml`.

This isn't ideal though, so make sure to revert it back to your original configuration once we get a fix out!
