### ISSUE TITLE
Simplify `buf.lock`

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#777]
# buf.lock

The `buf.lock` currently contains some information that isn't really needed. For example, the `branch` is being replaced with the new concept of `track`, and a commit can actually be associated with >=0 tracks at any given time.

The current structure looks like the following:

```yaml
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    branch: main
    commit: 84c3cad756d2435982d9e3b72680fa96
    digest: b1-GVZocI28gwtZCKNAO4Jd83jaE_XMjcAuEBtjnWvybO0=
    create_time: 2021-08-17T15:06:58.03881Z
```

We can simplify this all the way down to just the `remote`, `owner`, `repository`, and `commit`:

```yaml
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: 84c3cad756d2435982d9e3b72680fa96
```

We _could_ consider consolidating the `remote`, `owner`, and `repository` keys into a `name` key for terseness, but that might not buy us much - it's just slightly more visually appealing.

```yaml
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - name: buf.build/googleapis/googleapis
    commit: 84c3cad756d2435982d9e3b72680fa96
```

Regardless of what representation we go with, we should be able to keep using `v1` because we'd be using a new key (in the latter case) or simply omitting other ones that were previously used.

# Module Pins

## Client-side

In their current state, the `bufmodule.ModulePin` has a 1:1 association with the entries rendered in the `buf.lock`. If we make the changes to the `buf.lock` above, we might have an opportunity to simplify the `bufmodule.ModulePin`, too.

If we remove fields from the [buf.alpha.module.v1alpha1.ModulePin](https://github.com/bufbuild/buf/blob/7e66668a878c4fcd4b71beac727b7a344e8aa1bb/proto/buf/alpha/module/v1alpha1/module.proto#L64) (the Protobuf representation), then this is clearly a breaking change.

Unfortunately, even on the latest version of `buf`, it looks like we would have a validation error if _any_ of the values are missing in [ValidateProtoModulePin](https://github.com/bufbuild/buf/blob/68d587215467ad43db41e4440c19d1f4c811e8de/private/bufpkg/bufmodule/bufmoduleref/validate.go#L49).

So, in order to preserve old CLIs (pre 1.0), we need to continue returning the same `ModulePin` structure as-is, including [branch set to main](https://github.com/bufbuild/buf/blob/68d587215467ad43db41e4440c19d1f4c811e8de/private/bufpkg/bufmodule/bufmoduleref/validate.go#L136).

## Server-side

As expected, this same problem exists when we push a module with a simplified `buf.lock`. If the `buf.lock` does not contain all of the information required to satisfy the `buf.alpha.module.v1alpha1.ModulePin` requirements, then any module pushed by the latest CLI (i.e. `v1.0`) will be incompatible with all of the other old CLIs.

Sure, we can rely on the `buf-version` header to determine what fields should be included in the `ModulePin` response (e.g. if `>=v1.0`, then don't respond with `branch`, etc.). But even if the BSR is updated to accept the simplified `buf.alpha.module.v1alpha1.ModulePin` representation, the BSR will not have access to the fields required by the old CLIs when they resolve their dependencies (i.e. via `buf mod update`).

# What now?

The only way we can simplify the `buf.lock` and remove old values from each `deps` entry is to soft-force everyone to upgrade to `v1.0` which prevents old CLIs from interacting with modules produced by new CLIs. Note that old CLIs would continue to work with old modules.

There are clearly problems with preserving the `buf.lock` in its current state (e.g. the `branch` key is a particularly obvious example), but it's unclear if the tradeoffs are worth it. We should discuss further to see if there are other avenues that I've missed here.
