### ISSUE TITLE
buf cannot deal with subgroup repo

### ISSUE THREAD

**Issue by jony4** [bufbuild/buf#785]
when I run 

```
buf generate --verbose --debug
```
command, it returns 

```
Failure: module reference "gitlab.example.com/group/subgroup/reponame" is invalid: must be in the form remote/owner/repository:branch or remote/owner/repository:commit
```

here's my buf.yml

```yml
version: v1
name: gitlab.example.com/group/subgroup/reponame
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
  - gitlab.example.com/group/subgroup/reponame
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
build:
  excludes:
    - vendor/
```
