### ISSUE TITLE
Context deadline exceeded while downloading googleapis dependencies

### ISSUE THREAD

**Issue by handikacatur** [bufbuild/buf#824]
I experienced an error while buf is downloading dependencies.

Here is my buf.yaml
```yaml
name: buf.build/mypackage/authentication-service
version: v1beta1
build:
  roots:
    - proto/analytics
lint:
  use:
    - DEFAULT
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
```

Here is my terminal output:
```bash
buf: downloading buf.build/googleapis/googleapis:6358935a97044c1494fe13d369ac2f3b
Failure: context deadline exceeded.
```

I've updated using buf mod update but it always return context deadline exceeded while I do generate or build.

**Comment by cyinma** [comment]
Hi @handikacatur , thank you for your issue.

`buf` has a global flag `--timeout` for setting the timeout duration, which has a default value of `2m0s`, can you try to execute with a longer duration (e.g.  `buf build --timeout 5m`) to see if it works?

`googleapis` is a relatively huge dependency, depending on the internet condition, it is likely that `buf` cannot download the dependency with the default 2 minutes timeout.

**Comment by handikacatur** [comment]
Thank you for your quick reply @cyinma , I have done as you said. I set the timeout to be 5m. But it results in an error stating that the remote is unavailable. 
Here's the error looks like:
```bash
buf: downloading buf.build/googleapis/googleapis:6358935a97044c1494fe13d369ac2f3b
Failure: the server hosted at that remote is unavailable: error reading from server: read tcp 192.168.114.7:60785->35.193.118.40:443: read: connection reset by peer.
```

**Comment by amckinney** [comment]
This looks like a network issue similar to the one we saw [here](https://github.com/bufbuild/buf/issues/294#issuecomment-1002397730).

Are you able to build other modules just fine? How about a smaller one like `buf.build/acme/petapis`?

**Comment by handikacatur** [comment]
@amckinney I cloned the petapis repository and use a `buf.yaml` like this:
```yaml
version: v1
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
deps:
  - buf.build/acme/petapis
```
I do `buf build` and this is the output:
```bash
buf: downloading buf.build/acme/paymentapis:6e230f46113f498392c82d12b1a07b70
buf: downloading buf.build/acme/petapis:84a33a06f0954823a6f2a089fb1bb82e
buf: downloading buf.build/googleapis/googleapis:84c3cad756d2435982d9e3b72680fa96
Failure: context deadline exceeded.
```
I'm not using `buf.build/googleapis/googleapis` but it still downloading the dependency. Is this the default behavior of buf to download all deps although it is from another project in another directory?
Another repository seems downloaded successfully except for `buf.build/googleapis/googleapis`. When I run `buf build` again it is just downloading the googleapis.
