### ISSUE TITLE
Don't recognize google/api/annotations.proto

### ISSUE THREAD

**Issue by woshihaoren4** [bufbuild/buf#831]
proto roughly as follows：

```prot
import "google/api/annotations.proto";
import "google/protobuf/struct.proto";

service OmsService{
  rpc Create(CreateRequest) returns (Response) {
    option (google.api.http) = {
      post: "/api/v1/oms/create",
      body: "*"
    };
  }
}
```

buf.yaml：

```yaml
version: v1
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
```

The following code is generated after executing the command 'buf generate':
```go
import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "gitlab.hexcloud.cn/hicloud/schema/coreapis/script/google/api"
	_ "google.golang.org/protobuf/types/known/structpb"
	math "math"
)
```

`google/protobuf/struct.proto` into `google.golang.org/protobuf/types/known/structpb` is correct

but `google/api/annotations.proto` cannot become `_ "google.golang.org/genproto/googleapis/api/annotations"` 
wrong became my own package  `_ "gitlab.hexcloud.cn/hicloud/schema/coreapis/script/google/api"`

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! Could you share your `buf.gen.yaml`? It looks to me like you're overriding the `go_package` option in your `googleapis` dependency. Do you perhaps need to exclude this if you're using managed mode? https://docs.buf.build/tour/use-managed-mode#remove-modules-from-managed-mode.

**Comment by JacobSMoller** [comment]
Hey @bufdev i'm seeing something similar for the annotations package for Java generated code. 

With the following buf.gen.yaml
```yaml
version: v1
managed:
  enabled: true
  java_package_prefix: com.foobar.ocs
  go_package_prefix:
    default: github.com/foobar/dp-ocsapis/gen/proto/go
    except:
      - buf.build/googleapis/googleapis
plugins:
  - name: grpc-java
    out: gen/proto/java
  - name: java
    out: gen/proto/java
  - name: go
    out: gen/proto/go
    opt: paths=source_relative
  - name: go-grpc
    out: gen/proto/go
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false
  - name: grpc-gateway
    out: gen/proto/go
    opt:
      - paths=source_relative
      - logtostderr=true
      - generate_unbound_methods=true
```
The generated java code has: 
- `com.foobar.ocs.google.api.AnnotationsProto.getDescriptor()`
- `registry.add(com.foobar.ocs.google.api.AnnotationsProto.http)`
- `com.foobar.ocs.google.api.AnnotationsProto.getDescriptor()`

Using the following override fixes the issue, but it seems it should work without that override.
```yaml
  override:
    JAVA_PACKAGE:
      google/api/annotations.proto: "com.google.api"
```

E.g I have some protos using `import "google/protobuf/wrappers.proto";`

And for them i correctly get `com.google.protobuf.WrappersProto.getDescriptor()` instead `com.foobar.google.protobuf.WrappersProto.getDescriptor()`

Maybe its working as intended and I'm just missing something.
