### ISSUE TITLE
Importing buf.build/beta/envoy will conflict with googleapis

### ISSUE THREAD

**Issue by kindermoumoute** [bufbuild/buf#842]
When I run `buf generate` using version `1.0.0-rc10` building with the following deps:
```
deps:
  - buf.build/googleapis/googleapis
  - buf.build/envoyproxy/protoc-gen-validate
  - buf.build/beta/envoy
```

Will end up with this error:
```
my_proto.proto:9:8:google/api/annotations.proto exists in multiple locations: google/api/annotations.proto google/api/annotations.proto
```

<details>
   <summary>buf.lock</summary>

  ```
  # Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: beta
    repository: envoy
    branch: main
    commit: b504ea3e4b0e4a67a5a725e4bc9e6ab6
    digest: b1-yx04pc4ko-5CD5wzrNhfWhauhnB8GeurIbT4ZgEQWV4=
    create_time: 2021-08-09T14:37:20.385129Z
  - remote: buf.build
    owner: beta
    repository: googleapis
    branch: main
    commit: 4c646e03d3f240c7adee783061d00ff6
    digest: b1-KgltUGRRcmgG_U2MlDUMv3MmnTEdKdEJszcRTYSBj-k=
    create_time: 2021-08-09T14:21:27.570209Z
  - remote: buf.build
    owner: beta
    repository: opencensus
    branch: main
    commit: 5f5f8259293649d68707d2e5b6285748
    digest: b1-myYwcdM0Xu05qIwhiy4eWEcARYUuZZ1vTbYvrrHu1mU=
    create_time: 2021-03-03T20:50:42.079743Z
  - remote: buf.build
    owner: beta
    repository: opentelemetry
    branch: main
    commit: 549da630ffe24b53be3983fcee3bb346
    digest: b1-HVAvWKH61BF6TdZSbHRhrD2SUuC0V7uAlZgCRimGPLI=
    create_time: 2021-08-09T14:24:57.923964Z
  - remote: buf.build
    owner: beta
    repository: prometheus
    branch: main
    commit: a91b42d18a994cd4b07b37f365f87cf9
    digest: b1-uKmv58fyoNwJI855qg7UEagfdyUl6XNPsFAdDoi57f4=
    create_time: 2021-06-23T20:16:58.410272Z
  - remote: buf.build
    owner: beta
    repository: protoc-gen-validate
    branch: main
    commit: 82388a0a0cb04e98a203f95dfed5e84b
    digest: b1-lYgUMN58PxyCwvfQoopp40AJ-oHHjWXAzksF7v9U-U4=
    create_time: 2021-06-21T22:00:30.152545Z
  - remote: buf.build
    owner: beta
    repository: xds
    branch: main
    commit: 45f850b92541434cbde4aece01bc7d53
    digest: b1-QZUL5DC6-nVgMMlajH_hlImwghg5HjRsqlEAOl0dZgI=
    create_time: 2021-08-09T14:37:06.872899Z
  - remote: buf.build
    owner: envoyproxy
    repository: protoc-gen-validate
    branch: main
    commit: dc09a417d27241f7b069feae2cd74a0e
    digest: b1-Ml8P8Frdpw3OwpExAAPdylRY3Drdoz0lwMe104zLBEk=
    create_time: 2021-12-17T23:06:23.975454Z
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    branch: main
    commit: 0039142542b74d11b0ae5a1e9fd4d523
    digest: b1-AzPoqjtlLpx5dVojvgRauI1re5i4LPsghzU0KO-16o4=
    create_time: 2022-01-05T15:03:17.46488Z
  ```
</details>
