### ISSUE TITLE
Buf fails to find google/type/date.proto

### ISSUE THREAD

**Issue by raminqaf** [bufbuild/buf#886]
I am using buf version `1.0.0-rc11`, and my `buf.yaml` file looks like this:
```yml
version: v1
breaking:
  use:
    - FILE
build:
  excludes:
    - module1/build
    - module2/build
lint:
  use:
    - DEFAULT
  ignore:
    - google/protobuf/timestamp.proto
    - google/type/date.proto
```
Each `module1` and `module2` folder contain a proto file. Both of these files import the [googleapis](https://github.com/googleapis/googleapis/tree/master/google/type) at the beginning:
```proto
import "google/protobuf/timestamp.proto";
import "google/type/date.proto";
```
after running the command `buf lint`, I get the following error:
```
module1/src/main/proto/v1/module1.proto:10:8:google/type/date.proto: does not exist
```
It seems that the linter does not have a problem with the import `google/protobuf/timestamp.proto` but with the second one.
The only way to go through this problem is to comment out the `google/type/date.proto`, which is not a proper solution.

**Comment by cyinma** [comment]
Hi @raminqaf , thanks for your issue.

To depend on the `googleapis`, you will need to add the dependency to the `deps` in your `buf.yaml`, and your `buf.yaml` will be like this:

```
version: v1
deps:
  - buf.build/googleapis/googleapis
breaking:
  use:
    - FILE
build:
  excludes:
    - module1/build
    - module2/build
lint:
  use:
    - DEFAULT
  ignore:
    - google/protobuf/timestamp.proto
    - google/type/date.proto
```

After adding the dependency, you will need to run `buf mod update` to update your dependency, and you should be successfully running `buf lint` after that.

For more detail, you can take a look on https://docs.buf.build/tour/add-a-dependency

Please let us know if you have any other question!

**Comment by bufdev** [comment]
- `google/protobuf/timestamp.proto` is part of the Well-Known Types, a common set of [files](https://github.com/bufbuild/wellknowntypes/tree/main/v3.17.3/google/protobuf) that are included with both `protoc` and `buf` itself.
- `google/type/date.proto` is part of googleapis, as you point out. To depend on the googleapis, you will need to add the dependency to the deps in your buf.yaml, and your buf.yaml will be like this:

```yaml
version: v1
deps:
  - buf.build/googleapis/googleapis
breaking:
  use:
    - FILE
build:
  excludes:
    - module1/build
    - module2/build
lint:
  use:
    - DEFAULT
```

You do not need to ignore these files as they are not part of your local sources, so they won't come up in lint.

After adding `buf.build/googleapis/googleapis` to your `buf.yaml`, you need to run `buf mod update`. See https://docs.buf.build/bsr/usage#add-a-dependency for more details
