### ISSUE TITLE
Add versions to config for top-level, lint, breaking

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#90]
```yaml
version: v1beta1
build:
  roots:
    - .
lint:
  version: lint-v1beta1
  use:
    - DEFAULT
breaking:
  version: breaking-v1beta1
  use:
    - WIRE
```

This will:

- Lock down the config version.
- Lock down the lint rule set, regardless of config version.
- Lock down the breaking rule set, regardles of config version.

Warnings should be printed if these are not set.
