### ISSUE TITLE
Can't find google/api/annotations.proto

### ISSUE THREAD

**Issue by titpetric** [bufbuild/buf#922]
I'm having some weird issue with buf which I don't know how to resolve:

```
buf generate --template example/buf.gen.yaml --path example
example/src/upload.proto:7:8:google/api/annotations.proto: does not exist
```

example/buf.yml:

```yaml
version: v1
name: buf.build/go-bridget/twirp-php81-gen
deps:
  - buf.build/googleapis/googleapis
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
```

example/buf.gen.yaml.

```yaml
version: v1
plugins:
  - name: twirp-php81
    opt: namespace=Twirp
    out: example/gen
```

example/upload/upload.proto:

```yaml
syntax = "proto3";

package com.upload;
option go_package = "./upload";

import "google/api/annotations.proto";

service UploadService {
	rpc FileGet(FileGetRequest) returns (FileGetResponse) {
		option (google.api.http) = {
			get: "/upload/v1/file/{fileID}"
		};
	}
}

message FileGetRequest {
	string sessionID = 1;
	int64 fileID = 2;
}
message FileGetResponse {
	string url = 1;
}
```

buf.lock
```yaml
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: 6bb3f83f899f4e62a215f84b36c8009c
```

I just can't figure it out, must be something I'm not seeing... running rc12... I do have another project that successfully imports `google/protobuf/timestamp.proto`, and I've checked the schema registry to verify I'm not losing my mind, the google/api/annotations.proto is there. It is: https://buf.build/googleapis/googleapis/file/main/google/api/annotations.proto
