### ISSUE TITLE
External files for remote plugins

### ISSUE THREAD

**Issue by thepabloaguilar** [bufbuild/buf#952]
Hello guys, I'm writing a `protoc` plugin and searching to publish it as a `buf` remote plugin but my plugin needs an external file in order to work! By the description of what a remote plugin is I think it's not possible to get files from the project, right?

Plugin link: https://github.com/faunists/deal-go

**Comment by lrewega** [comment]
You are correct, a remote plugin can only access what is provided by a [`CodeGeneratorRequest`](https://buf.build/beta/wellknowntypes/docs/main/google.protobuf.compiler#google.protobuf.compiler.CodeGeneratorRequest), as well as anything included in the plugin's container image. See the section on "Hosted Plugins": https://docs.buf.build/bsr/remote-generation/overview#hosted-plugins.

You _might_ be able to provide a multi-line configuration through an `opt` string, if your plugin supported that, but I wouldn't recommend that. I haven't tested this, but it should work in theory:

```yaml
- remote: buf.build/faunists/plugins/deal-go
  out: gen/go
  opt: >
    contract.json={ 
       "name": "my contract",
       "services": ...
```

The `opt` string would then be available in `CodeGeneratorRequest.parameter`.
