### ISSUE TITLE
Use Buf with --plugin from node_module

### ISSUE THREAD

**Issue by g3david405** [bufbuild/buf#979]
I am now generating javascript grpc code. Example is as following:
protoc --grpc_out=./ --plugin=protoc-gen-grpc=./node_modules/.bin/grpc_tools_node_protoc_plugin -I ./proto ./proto/*.proto.  
How can I use Buf to do this?
Thanks!!

**Comment by smallsamantha** [comment]
Thanks for the question!! Please check out our docs on replacing protoc with buf https://docs.buf.build/how-to/replace-protoc-with-buf

**Comment by smallsamantha** [comment]
Also check out the [Remote Plugin Execution docs](https://docs.buf.build/bsr/remote-generation/remote-plugin-execution), because this is an ideal use case! You'd end up with a `buf.gen.yaml` file looking something like:
```
version: v1
managed:
  enabled: true
plugins:
  - remote: buf.build/grpc/plugins/node:v1.11.2-1
    out: gen/js
    opt:
      - import_style=commonjs

```
