### ISSUE TITLE
Lock in plugin to specific major version

### ISSUE THREAD

**Issue by jon-whit** [bufbuild/buf#994]
Is there a way to lock into a plugin of a specific major version and get any minor/patch updates automatically?

I'd like to do something like:

```
# buf.gen.yaml
version: v1
plugins:
  - remote: buf.build/protocolbuffers/plugins/go:v1 # get latest v1 plugin (maximize minor and patch versions)
    out: proto/
    opt: paths=source_relative
```

**Comment by amckinney** [comment]
Using a major semantic version prefix isn't supported right now, but you can omit the `v1` component entirely to always get the latest version. It's technically possible that we would publish a new `buf.build/protocolbuffers/plugins/go` that violates compatibility with previous versions, but that's not our intention - ideally all of the versions are within the same major version range so that users can confidently depend on the latest.

If we ever need to publish a new major version, we'll be able to decide between two approaches:
* Publish the plugin under a new name (like Go's module compatibility strategy).
    * In this case we might have a `buf.build/protocolbuffers/plugins/go2` or something along those lines.
* Add support for the major semantic version prefix like you've described.

With all that said, it's usually a good idea to pin to a specific version of the plugin you want to use and update them manually. gRPC is a little notorious for introducing [breaking changes in minors](https://github.com/grpc/grpc-go/issues/3798), so it's sometimes out of your control even if the major version aligns. Plus, it's a really nice to ensure that the code you're generating is predictable and reproducible (as described in [our docs](https://docs.buf.build/bsr/remote-generation/remote-plugin-execution)).

In this case, I'd actually suggest using the following:
```yaml
# buf.gen.yaml
version: v1
plugins:
  - remote: buf.build/protocolbuffers/plugins/go:v1.27.1-1
    out: proto/
    opt: paths=source_relative
```

**Comment by jon-whit** [comment]
Thanks for the background context. For now I'll just lock in an explicit version.

It may also be nice to have a github-action or something that could report an update to a protobuf dependency. Or if there was a sub-command of buf that could report an update is a available for a dependent package. For example `buf outdated` could return the outdated packages and a subsequent `buf upgrade <package>` could upgrade it. Just a thought?

**Comment by amckinney** [comment]
Keep an eye out for the new `plugin` key introduced [here](https://github.com/bufbuild/buf/pull/1277). We don't plan to support the semantic version upgrade experience you're suggesting yet (i.e. behavior like `^v1` or `^v1.1` in other package managers), but we _are_ going to support resolving the latest _revision_, which previously occupied the `-<X>` suffix in the version.

Put simply, you'll be able to write the following and get the latest revision of `v1.27.1` (notice the `-1` suffix is missing):

```yaml
# buf.gen.yaml
version: v1
plugins:
  - plugin: buf.build/protocolbuffers/plugins/go:v1.27.1
    out: proto/
    opt: paths=source_relative
```
